### ISSUE TITLE
[Nested git repos] Parent git repository changes are displayed wrong

### ISSUE THREAD

**Issue by kseniamurex** [atom/tree-view#932] opened 2016-08-31 10:15 UTC
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? (1.9.9)
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? : the issue is partly related to [this thread](https://discuss.atom.io/t/nested-git-repositories-and-the-ignored-look-in-the-tree/2262)
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description
I'm working with a lot of nested git repos, like the guys from [this thread](https://discuss.atom.io/t/nested-git-repositories-and-the-ignored-look-in-the-tree/2262). Let's say it's something like this: ![screenshot - 31 08 2016 - 12 52 28](https://cloud.githubusercontent.com/assets/21336215/18124712/1b9cae98-6f7c-11e6-82fc-24359ad79be9.png)
 Sure, it would be nice if this feature mentioned on Discuss will be supported, but as we don't have it, I partly solved the problem with the following trick:
1. Add subrepos to the project first.
2. Then add the parent repo.

So I can check my subrepos and it works fine and sometimes the changes are even shown correctly inside of the parent repo! But the parent repo changes aren't shown at all:
![screenshot - 31 08 2016 - 12 58 20](https://cloud.githubusercontent.com/assets/21336215/18124724/2e9835ee-6f7c-11e6-96c3-a9ff684a8df5.png)

When I add the parent repo, changes aren't dispalyed. If I now open a changed file, the tree shows that it was changed, but only this opened file, so I have to open them all. Now if I switch to any other window, the tree of the parent repo redraws, and the changes aren't shown again.

### Steps to Reproduce

1. Create nested git repos.
2. Add the subrepo to the project.
3. Add the parent repo to the project.

**Expected behavior:** Both parent and child repo changes are dispalyed in the tree view.

**Actual behavior:** Child repo changes are displayed, parent's are not. If you open a changed file its changes become displayed. If you switch to another window, the changes aren't displayed again.

### Versions

`Atom    : 1.9.9`
`Electron: 0.37.8`
`Chrome  : 49.0.2623.75`
`Node    : 5.10.0`

`Linux version 3.13.0-95-generic (buildd@lgw01-58) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016`

**Comment by lee-dohm** [comment] 2016-08-31 18:35
From what I can tell, this is a duplicate of https://github.com/atom/tree-view/issues/91. If I'm mistaken, please update the repro steps to be more clear as to what problem you're asking for us to solve.

**Closed by lee-dohm** 2016-08-31 18:35 UTC

**Comment by kseniamurex** [comment] 2016-09-01 07:53
@lee-dohm I think it sure is related, but differs a bit.
The #91 issue is about repo is displayed as dirty even if it is clean. My case is that parent repo is displayed clean even if it is dirty. 
Here is what I want to have: 
![screenshot - 01 09 2016 - 10 52 00](https://cloud.githubusercontent.com/assets/21336215/18159613/30e4cf68-7032-11e6-9620-577a4c15e0d4.png)
And that is what I actually have:
![screenshot - 01 09 2016 - 10 52 11](https://cloud.githubusercontent.com/assets/21336215/18159622/40314c30-7032-11e6-9547-dc74e512791e.png)

**Comment by lee-dohm** [comment] 2016-09-01 16:58
I suspect that they'll be fixed by the same change (or at least should be). Please add your repro case to the other Issue and I'll update the title.

**Comment by kseniamurex** [comment] 2016-09-02 08:43
Done! Thank you.
