### ISSUE TITLE
Hide VCS Ignored Files also ignores everything in ".npmignore"

### ISSUE THREAD

**Issue by firstdoit** [atom/tree-view#845] opened 2016-05-23 11:44 UTC
![image](https://cloud.githubusercontent.com/assets/1633518/15469660/04dea820-20ec-11e6-84d0-ff2abac1b9d1.png)

Apparently [here](https://github.com/atom/tree-view/blob/5c0871c1828b48a5ab083296d9e647e2477f2a21/lib/directory.coffee#L99) the path is incorrectly tagged as ignored:

```coffee
  # Is the given path ignored?
  isPathIgnored: (filePath) ->
    if atom.config.get('tree-view.hideVcsIgnoredFiles')
      repo = repoForPath(@path)
      return true if repo? and repo.isProjectAtRoot() and repo.isPathIgnored(filePath)

    if atom.config.get('tree-view.hideIgnoredNames')
      for ignoredPattern in @ignoredPatterns
        return true if ignoredPattern.match(filePath)

    false
```

**Comment by 50Wliu** [comment] 2016-05-23 16:19
Are you sure?  It doesn't look like files such as `.eslintrc` and `.travis.yml` are being ignored.

**Comment by lee-dohm** [comment] 2016-05-24 05:25
I can't reproduce this using Atom v1.9.0-dev-2cfc4ee on Mac OS X 10.11.5. Here's what I tried.

1. Open terminal
1. Change directory to my local Atom repository
1. Launch Atom with `atom .`
1. Ensure that "Hide Ignored Names" is **enabled**
1. Ensure that "Hide VCS Ignored Files" is **disabled**
1. Take screenshot

<img width="298" alt="screen_shot_2016-05-23_at_10_17_43_pm" src="https://cloud.githubusercontent.com/assets/1038121/15492888/d2a8bc94-2134-11e6-9987-7159bd1f8bf0.png">

1. Add empty `.npmignore`
1. Restart Atom to ensure that change is taken into account
1. Take screenshot

<img width="696" alt="screen_shot_2016-05-23_at_10_18_18_pm" src="https://cloud.githubusercontent.com/assets/1038121/15492915/0d11851e-2135-11e6-94c8-356900648b00.png">

1. Add `*.md` to `.npmignore`
1. Restart Atom to ensure that change is taken into account
1. Take screenshot

<img width="618" alt="screen_shot_2016-05-23_at_10_18_53_pm" src="https://cloud.githubusercontent.com/assets/1038121/15492945/469a2f02-2135-11e6-9a99-8cb7a884002b.png">

**Comment by firstdoit** [comment] 2016-05-24 11:09
Nice! Thanks for trying to reproduce. And thanks to that I was able to realize that apparently it's actually the negation that's not working in `.gitignore` itself:

![image](https://cloud.githubusercontent.com/assets/1633518/15501886/906f2c2e-21b0-11e6-9e85-d82e7ca9c301.png)

![image](https://cloud.githubusercontent.com/assets/1633518/15501895/a068ab28-21b0-11e6-9263-b25b50f56e63.png)

Notice that when I remove `lib/` and `bin/` from ignore it goes back to showing `src/{lib,bin}/`.

So apparently the `!src/bin/` is not being taken into consideration?

**Comment by 50Wliu** [comment] 2016-05-24 11:50
In that case this seems to be a duplicate of #196.

**Closed by 50Wliu** 2016-05-24 11:50 UTC
Labels: more-information-needed

**Comment by firstdoit** [comment] 2016-05-24 11:52
Cool! Thanks :)
