### ISSUE TITLE
v0.183.0 breaks certain context menu items

### ISSUE THREAD

**Issue by Galadirith** [atom/tree-view#555] opened 2015-08-19 20:11 UTC
Certain context menu items seem to no longer work. For example both ['Markdown Preview'](https://github.com/atom/markdown-preview/blob/42eb71da984232faaba2a5f75d30a1d8e1d138cf/menus/markdown-preview.cson#L19) and ['Beautify File'](https://github.com/Glavin001/atom-beautify/blob/72e4384cf815e633e580ffdad8847f355e3e7c89/menus/atom-beautify.cson#L7) do not show up in the context menu. 

- **`v0.183.0`**
![v0 183 0](https://cloud.githubusercontent.com/assets/1201875/9367621/7c80cad6-46b6-11e5-99b1-de4460798bbd.gif)

- **`v0.182.0`**
![v0 182 0](https://cloud.githubusercontent.com/assets/1201875/9367655/a8c69dd2-46b6-11e5-90c9-cf0592dfc21d.gif)

I have tested that the issue does not appear to exist for `v0.182.0`. From my own experiments the problem seems to be selecting leaf elements of the `.tree-view`. For example `.tree-view .file` appears to work fine.

When running in safe mode 'Markdown Preview' still does not show up in the context menu.

Thanks so much for all the amazing work on Atom :smile:

**Comment by kevinsawicki** [comment] 2015-08-19 23:26
@saschagehlich @nathansobo this looks to have possibly regressed via the drag and drop work done in #543

**Comment by Galadirith** [comment] 2015-08-19 23:28
It looks as though the style [`.tree-view .entry .name`](https://github.com/atom/tree-view/blob/6f5ab9eab4f58087c25ad337dc62a2cf62b9157b/styles/tree-view.less#L49-L51) add in 6f5ab9e is the problem. Removing it cures the issue, but I don't know what else that style affects. Thanks @kevinsawicki for the super quick response.

**Comment by saschagehlich** [comment] 2015-08-20 08:31
I made some changes to the CSS to fix the hovering issue mentioned [here](https://github.com/atom/tree-view/pull/543#issuecomment-129742134). I honestly never used any of the custom context menu items. But I'll look into that now

**Comment by Galadirith** [comment] 2015-08-20 10:34
@saschagehlich Thanks for taking a look into this, really appreciate it.

**Comment by saschagehlich** [comment] 2015-08-21 11:59
Pinging @nathansobo @kevinsawicki @mnquintana

**Comment by cakebake** [comment] 2015-08-21 13:55
+1

**Comment by Galadirith** [comment] 2015-08-22 09:32
Thank you so much for the super fast response @saschagehlich @nathansobo @kevinsawicki @izuzak, its great to have this back in master.

**Comment by izuzak** [comment] 2015-09-13 14:42
As far as I can tell -- this was fixed in https://github.com/atom/tree-view/issues/556 and I'm unable to reproduce this problem. Let me know if this is still an issue for anyone.

**Closed by izuzak** 2015-09-13 14:42 UTC
Labels: bug

**Comment by cakebake** [comment] 2015-09-14 07:58
Works properly again :)
