### ISSUE TITLE
Tree view hiding folders not ignored in .gitignore

### ISSUE THREAD

**Issue by cfrancesco** [atom/tree-view#1291] opened 2018-12-04 10:28 UTC
I'm using version 1.29.0. I am not able to consistently reproduce the behavior at the moment.

What happens is that some folders, without a noticeable pattern (to me), are hidden in treeview. The only way to display them is to disable "Hide VCS Ignored Files".

The only recurrent thing I'm observing that this seems to happen more often when I have two project with similar folder structure (some folders with same names). In one of them the .gitignore contains the following (amongst other lines):

```
# Ignore everything
/*
/*/

# Git the following
!/src
!/scripts
```

and in the other, these folders are directly not ignored (so NOT ignore everything + add exceptions).

Specifically, in the second project, the script folder is not shown in the tree structure, but when disabling the Hide VCS, it shows up and it tracks modifications to the file: the file names in the folder become orange when they are modified.

As soon as I am able to reproduce this more accurately, I will update the issue.

**Comment by rsese** [comment] 2018-12-05 06:15
Thanks for the report!

Based on your description, I think this is a duplicate of https://github.com/atom/tree-view/issues/196 so you can subscribe there for updates if you'd like.

If you think this issue is different, please fill out the issue template details and we'll take a look.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-12-05 06:15 UTC
