### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefinedTypeError: Cannot read property 'objec...

### ISSUE THREAD

**Issue by stwupton** [atom/tree-view#1078] opened 2017-04-22 16:08 UTC
[Enter steps to reproduce:]

1. Occurs when right clicking a project folder in the tree-view and then clicking "Remove Project Folder".

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.215.1

### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:\scoop_apps\apps\atom\1.16.0\resources\electron.asar\browser\objects-registry.js:41:28)
    at EventEmitter.<anonymous> (C:\scoop_apps\apps\atom\1.16.0\resources\electron.asar\browser\rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\scoop_apps\apps\atom\1.16.0\resources\electron.asar\browser\api\web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\scoop_apps\apps\atom\current\resources\electron.asar\renderer\api\remote.js:210

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (C:/scoop_apps/apps/atom/1.16.0/resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (C:/scoop_apps/apps/atom/1.16.0/resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:/scoop_apps/apps/atom/1.16.0/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:/scoop_apps/apps/atom/current/resources/electron.asar/renderer/api/remote.js:210:13)
    at undefined.remoteMemberFunction (C:/scoop_apps/apps/atom/current/resources/electron.asar/renderer/api/remote.js:111:18)
    at ReopenProjectMenuManager.updateWindowsJumpList (/app.asar/src/reopen-project-menu-manager.js:111:16)
    at ReopenProjectMenuManager.update (/app.asar/src/reopen-project-menu-manager.js:79:12)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at HistoryManager.didChangeProjects (/app.asar/src/history-manager.js:77:20)
    at HistoryManager.addProject (/app.asar/src/history-manager.js:95:12)
    at /app.asar/src/history-manager.js:36:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Project.module.exports.Project.removePath (/app.asar/src/project.js:314:22)
    at TreeView.module.exports.TreeView.removeProjectFolder (/app.asar/node_modules/tree-view/lib/tree-view.js:1214:31)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:311:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:23.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-one-dark-syntax.theme-atom-material-ui)
     -0:12.7.0 tree-view:remove-project-folder (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-material-ui 1.3.9 
atom-typescript 11.0.2 
busy-signal 1.3.0 
file-icons 2.1.3 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
minimap 4.27.1 
multi-wrap-guide 0.28.4 
platformio-ide-terminal 2.5.0 
Zen 0.16.4 
```

**Comment by 50Wliu** [comment] 2017-04-22 18:30
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#11692. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-22 18:30 UTC
