### ISSUE TITLE
Add option to prevent accidentally moving folder

### ISSUE THREAD

**Issue by miftahafina** [atom/tree-view#835] opened 2016-05-15 13:05 UTC
Please add option to prevent accidentally move folder with drag-n-drop, especially for 'careless' programmer like me.

**Comment by thomasjo** [comment] 2016-05-15 14:13
What would such a feature be? I'm not aware of any IDE (or other relevant software for that matter) with any special "feature" to prevent accidentally moving folders when dragging and dropping.

**Comment by miftahafina** [comment] 2016-05-15 14:58
Sorry, I mean 'option', not 'feature'.

**Comment by thomasjo** [comment] 2016-05-15 15:00
Just to be sure we're on the same page; you want an option to **disable** the drag and drop feature entirely?

**Comment by miftahafina** [comment] 2016-05-15 15:03
Yes, I want it.
But of course, I wish the 'drag-n-drop' is enabled by default.

**Comment by thomasjo** [comment] 2016-05-15 15:08
@atom/feedback What do we think about this? In general I'm against adding functionality like this. We definitely don't need *more* checkboxes for tiny stuff like this.

I'm fairly sure we can find a way to kill the drag and drop functionality via the init script (or perhaps via style tweaking)... I propose we find such a workaround and close this as `wontfix`.

**Comment by lee-dohm** [comment] 2016-05-16 16:50
I'd be open to making it harder to accidentally drag and drop things if we had an example of a situation that caused an accidental drag action. I think the best solution is to make drag and drop require a very deliberate action and make it very visible.

@miftahafina do you have an example of a situation that caused an accidental drag-and-drop action that we can reproduce?

**Comment by miftahafina** [comment] 2016-05-17 00:23
For example when I use laptop without 2 fingers gesture to scroll, so I have to press left click and drag the scroll bar manually. But, sometime I move the file into other folder accidentally.

**Comment by lee-dohm** [comment] 2016-05-17 20:16
I feel like the answer to that is to make the scroll bar bigger when you're in that situation so that it isn't as easy to miss.

@simurai do you have any suggestions for how to do that? Is there a way to make the scroll bar grow on hover?

**Comment by BinaryMuse** [comment] 2016-05-17 20:36
I'm in agreement that more checkboxes isn't the right approach here. In addition to @lee-dohm's suggestion, perhaps we can maintain an operation history so you can "undo" in the tree view easily

**Comment by simurai** [comment] 2016-05-18 00:18
> make the scroll bar bigger

Adding the following to `styles.less` should work. But on OS X only if you enable "Show scroll bars: Always".

```css
.scrollbars-visible-always .tree-view-scroller::-webkit-scrollbar {
  width: 20px;
}
```

> I'm fairly sure we can find a way to kill the drag and drop functionality via the init script (or perhaps via style tweaking)

You should be able to disable dragging with:

```css
.tree-view [draggable="true"] {
  -webkit-user-drag: none;
}
```

It might could be combined with an init script to temporarily enable dragging by pressing `cmd` or so. Then you'd still be able to drag, just not as easy.

**Comment by lee-dohm** [comment] 2016-05-19 16:18
Thanks so much for the solution @simurai :grinning: Since dragging can be disabled by a simple `styles.less` change, I'm going to close this.

**Closed by lee-dohm** 2016-05-19 16:18 UTC
Labels: enhancement, more-information-needed

**Comment by cstockton** [comment] 2016-10-22 00:39
@simurai I know this is an old issue, but I was just about ready to flip my desk over this time. I have developed a paranoia for these "instant drags" that occur sometimes without me really noticing. Sometimes I'll see a glimpse of the handle and not be sure if anything actually moved or not.. and end up having to sort through a rsync dry run against my backup partitions to be sure I didn't delete anything. Then just now I saw a popup saying "Cross device copying is not supported" in a little "instant drag" and I decided I was going to solve this once and for all, even if it meant writing a plugin or drinking myself into a coma. After digging around I came across this thread, before my drag and drop insanity got too out of hand.

Those three glorious lines of CSS are fantastic and I thank you sir.

**Comment by kennblvnp** [comment] 2018-11-09 12:07
Hi @simurai ! What are the exact steps to do this??

**Comment by rsese** [comment] 2018-11-09 18:37
@kennblvnp - the steps @simurai mentioned are macOS specific and still seem to work (I just tried it out):

1. From the command palette run `Application: Open Your Stylesheet`
2. Add and save the CSS @simurai mentioned above:

```css
.tree-view [draggable="true"] {
  -webkit-user-drag: none;
}
```

As also mentioned, on macOS you need to have `System Preferences > General > Show Scroll Bars` set to `Always` for this to work.

If you have any trouble, please reach out on the [message board](https://discuss.atom.io/) or the [Atom Slack](http://atom-slack.herokuapp.com).

**Comment by kennblvnp** [comment] 2018-11-10 10:46
@rsese thank you very much! but im using windows...
