### ISSUE TITLE
Renaming a file removes opened file from the editor

### ISSUE THREAD

**Issue by TimvdLippe** [atom/tree-view#931] opened 2016-08-29 13:36 UTC
I am not sure if this is an issue with tree-view or the core Atom editor, but since the action is performed in tree-view I decided to post the issue here.

When I rename a file in the tree-view, once I hit enter, the file is correctly renamed. However, if that specific file is opened in my editor, the file is closed. What I would expect to happen is that the file is not closed, but instead only the header (name) of the file is changed to reflect to the new file name.

**Comment by Ben3eeE** [comment] 2016-08-29 13:46
I am unable to reproduce this on Windows 7 using Atom 1.9.9, can you:

1. Reproduce the issue in safe mode? `atom --safe`.
2. Provide the output of `atom --version` and `apm --version`.
3. Specify which OS you are using.
4. Specify which file you are renaming? Is it an `ImageEditor` or `TextEditor` that gets closed for example?

**Comment by TimvdLippe** [comment] 2016-08-29 13:52
1. Yes
2. Atom v1.9.6, Electron 0.37.8, Chrome 49.0.2623.75, Node 5.10.0
3. Ubuntu 16.04
4. I am renaming a Java file from `foo.java` to `bar.java`. I am not sure what you mean with the Editor classes, but the file I previously have opened in my editor view gets closed. Hopefully that is enough information to reproduce.

**Comment by 50Wliu** [comment] 2016-08-29 15:59
This is a duplicate of #264 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-29 15:59 UTC

**Comment by TimvdLippe** [comment] 2016-08-29 16:04
Oops sorry, I actually searched the issues list for quite a while to make sure it was not a duplicate. Will subscribe there!
