### ISSUE TITLE
Introduce option for disabling moving files and/or folders 

### ISSUE THREAD

**Issue by jbergstroem** [atom/tree-view#996] opened 2016-11-30 20:29 UTC
I've more than once moved a folder into another by mistake. Having an option that disables similar options in the tree view would be awesome!

**Comment by 50Wliu** [comment] 2016-11-30 21:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #588. In line with the comments on #623, we're going to focus on improving the UX of drag-and-drop as the solution, rather than a setting to disable this functionality.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-11-30 21:14 UTC

**Comment by benyanke** [comment] 2017-07-31 15:55
>  we're going to focus on improving the UX of drag-and-drop as the solution, rather than a setting to disable this functionality.

Why not both? One is a short term fix which has little impact on those who don't want it, and the other is a longer-term feature add which can peacefully coexist with the shortterm fix.

**Comment by benyanke** [comment] 2017-08-01 14:09
Since the Atom team seems firm about refusing to add this functionality....

I'm new to atom packages, but if it gets an install base, I'd happy to keep this very simple fork up to date, with a hardcoded disable of drag and drop. In any case, it's working on the current version for current use.

I'll keep an eye on the download counts in the atom package store to see if I decide to go with ongoing maintenance (which could perhaps even be scripted, since it's a search/replace for true/false).

https://github.com/benyanke/tree-view-no-drag
https://atom.io/packages/tree-view-no-drag

**Comment by benyanke** [comment] 2017-09-20 20:21
Note, to those who followed this thread:

> Given that we're not going to take on significant work on the tree view any time soon, adding this checkbox, while less than ideal, feels like the right thing now.
> I can't re-open this PR because the source repo is gone, but we'd accept a good PR adding this. I'll reopen #588.

[source](https://github.com/atom/tree-view/pull/623#issuecomment-330957065)
