### ISSUE TITLE
File-icon service set too late in some cases

### ISSUE THREAD

**Issue by hgGeorg** [atom/tree-view#653] opened 2015-11-18 08:13 UTC
Occurs at least on Windows: 
* When you open a folder using the right-click context menu, the service is set too late and the tree view will show default icons. Collapsing and re-expanding folders will update icons correctly afterwards.
* When (re-)starting Atom with an existing project will also cause this issue to occur.

**Comment by hgGeorg** [comment] 2015-11-19 10:17
@glangford the file-icon package (as of version 1.6.11) doesn't provide a file-icon service yet. Said package uses the data-name attribute on the element to determine which icon to insert.

**Comment by glangford** [comment] 2015-11-19 11:26
> the file-icon package (as of version 1.6.11) doesn't provide a file-icon service yet. It uses the data-name attribute on the element to determine which icon to insert.

@hgGeorg Ah - thanks for clarifying.

**Comment by glangford** [comment] 2015-11-19 12:07
@hgGeorg I am researching this and learning as I go, so this is not necessarily authoritative. :smile: But here are some links which may have useful info:

Use console to debug activation and the activationEvents key
<https://discuss.atom.io/t/unable-to-use-console-log/3134/7>

Async provided and consumed services
<https://discuss.atom.io/t/provided-and-consumed-services-are-now-async-is-it-a-good-idea/19788>

**Comment by acontreras89** [comment] 2016-04-24 00:29
Huh... I believe atom/tree-view/issues/732 is a duplicate of this issue. There you can find an explanation on the problem and a solution to it, which is already part of PR atom/tree-view/pull/756.

**Comment by lee-dohm** [comment] 2016-04-24 00:38
Thanks @acontreras89! Closing this as a duplicate of #732.

**Closed by lee-dohm** 2016-04-24 00:38 UTC
Labels: bug

**Comment by Alhadis** [comment] 2016-04-29 11:36
Is the icons service meant to affect directories too? Because it only seems to be firing for *files*, not folders. :|

<img width="174" alt="screen shot 2016-04-29 at 9 35 40 pm" src="https://cloud.githubusercontent.com/assets/2346707/14914978/5720403c-0e52-11e6-80c3-46daa7d63612.png">

I'm integrating the new API into the [File Icons](https://github.com/DanBrooker/file-icons) package, and the folders shouldn't be showing any icons in the screenshot.

**Comment by lee-dohm** [comment] 2016-04-29 20:34
> Is the icons service meant to affect directories too?

No, it is only intended to fire for files.

**Comment by Alhadis** [comment] 2016-04-30 11:23
Well, I suppose it makes sense. Fortunately, File Icons only has a grant total of four directory-related icon rules that're easily embedded in CSS. At least this will simplify the package's configuration.
