### ISSUE TITLE
Repos not detected if they are subfolders

### ISSUE THREAD

**Issue by akonwi** [atom/tree-view#655] opened 2015-11-19 03:07 UTC
This is an [issue raised in my package](https://github.com/akonwi/git-plus/issues/312).

I know the underlying git knowledge comes from `atom.project` and I think I understand why `project` doesn't check for nested repos like this. Would it make sense for this package to do it's own repo search and management? This is a similar question for status-bar as well. I don't want to add this functionality to my package if it isn't also reflected in the other places where git info is shown.

**Comment by noirbizarre** [comment] 2016-01-18 12:03
Any progress on this one ?
I have the same issue on Atom 1.4

**Comment by mnquintana** [comment] 2016-01-18 23:02
This looks like a duplicate of https://github.com/atom/atom/issues/2203 – feel free to subscribe there for updates.

**Closed by mnquintana** 2016-01-18 23:02 UTC
