### ISSUE TITLE
Right-click on file/directory doesn't highlight until after action is taken

### ISSUE THREAD

**Issue by cbcoutinho** [atom/tree-view#978] opened 2016-11-08 16:56 UTC
I sometimes right-click on a directory in the tree-view to either add/delete a file, or remove a project directory. If another file/directory is highlighted, right-clicking on a file opens up a context menu; however it isn't clear if it's related to the originally highlighted file/directory or the one I right-clicked on. This has the unintended consequence of not being sure what will happen:

- Am I deleting the previous directory, or this file?
- Am I adding a file here or somewhere else?

Thankfully, deleting sometime comes up with a dialog box clearing up the confusion, but I don't think this is consistent with what I would expect from the tree-view.

After you make a selection, the correct file/directory is highlighted, but I think it should be highlighted before you make an action. Is it possible to highlight the file/directory at the same time as opening up the context menu?

I made a quick gif to show you what I mean - notice what is highlighted and what I right-click:

![output](https://cloud.githubusercontent.com/assets/12901868/20108345/0d60132e-a5dc-11e6-9c60-d6580262de5a.gif)

**Comment by Ben3eeE** [comment] 2016-11-08 17:06
Thanks for contributing. This is a duplicate of https://github.com/atom/atom/issues/2991. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-08 17:06 UTC

**Comment by cbcoutinho** [comment] 2016-11-08 17:09
You're right, I wasn't able to find it in tree-view package, thanks for linking to the issue on the atom repo.

**Comment by Ben3eeE** [comment] 2016-11-08 17:29
You're welcome. It is not always easy to find the duplicates 🙂
