### ISSUE TITLE
Doesn't show git status when file is selected

### ISSUE THREAD

**Issue by kekumu** [atom/tree-view#197] opened 2014-07-26 15:50 UTC
When a file is selected in Tree View, it highlights it like any other file, and you can no longer see the git status.
When the file is actively selected:
![untitled 3](https://cloud.githubusercontent.com/assets/423812/3711560/387c8e90-14dc-11e4-88cd-498c89bb02e6.png)
When the file has focus in the editor:
![untitled 2](https://cloud.githubusercontent.com/assets/423812/3711559/387bff52-14dc-11e4-992d-2f1194a4cb6e.png)

**Comment by VanCoding** [comment] 2015-03-08 20:24
+1

**Comment by lee-dohm** [comment] 2015-03-12 16:14
This isn't a bug in the tree view, but in the theme itself. A modified file has the class `status-modified`. A selected file has the additional class `selected`. The theme is responsible for determining a proper way to style a selected and modified file that makes sense to the user, the Tree View package doesn't have any control over that. (Or at least shouldn't exercise any control over that.)

For example, the [One Dark UI Theme](https://atom.io/themes/one-dark-ui) shows a modified and selected file "properly":

![screen shot 2015-03-12 at 9 06 56 am](https://cloud.githubusercontent.com/assets/1038121/6622036/51704648-c897-11e4-9373-aba01e965d7e.png)

I've opened up atom/atom-dark-ui#43 and atom/atom-light-ui#21 to track this. I'd recommend closing this issue. What do you think @izuzak? (I didn't want to close it out of hand since it has been open for so long.)

**Comment by izuzak** [comment] 2015-03-12 16:18
@lee-dohm Ahh, thanks for investigating -- I didn't even think of that. Yeah, opening an issue on Atom-owned themes sounds like a good idea :+1:. I'd still keep this open until that's fixed in the themes because users will probably look here and try to find an open issue about this. So, keeping it open until the problem is resolved should help users find issues and not open duplicates. We've been discussing this internally recently and we'll probably add some guidelines to the contributing guide in Atom (of course, through a PR so that we can discuss this with the community first).

Thanks again! :heart:

**Comment by simurai** [comment] 2015-03-14 01:08
Should be fixed in the next release of the Atom dark + light themes.

**Closed by simurai** 2015-03-14 01:08 UTC
Labels: blocked, enhancement
