### ISSUE TITLE
Keybindings not working where DE keyboard layout differs from EN

### ISSUE THREAD

**Issue by KonradHoeffner** [atom/tree-view#746] opened 2016-02-22 10:46 UTC
I use German keyboard layout and Atom doesn't react on the keybinding for Toggle Treeview (`CTRL-\`). With the mouse it works. When I press `CTRL-\` (actually `CTRL-AltGr-ß`), the keybinding resolver shows `ctrl-[`. Similarily, other letters that require Shift or AltGr are misregistered as well, while they work perfectly when typing in the editor itself. I assume that the keybindings are hardcoded for the EN or US keyboard layout.

I use Atom 1.5.3 on Arch Linux 4.4.1-2 installed via AUR.

P.S.: The issue is not solved by using https://atom.io/packages/keyboard-localization as suggested by the FAQ.

**Comment by lee-dohm** [comment] 2016-02-22 22:58
Thanks for reporting! This is a duplicate of https://github.com/atom/atom-keymap/issues/35. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-22 22:58 UTC
