### ISSUE TITLE
shadow text

### ISSUE THREAD

**Issue by charlespeters** [atom/tree-view#363] opened 2015-02-10 00:23 UTC
getting shadow text in my treeview

![screenshot 2015-02-09 19 19 44](https://cloud.githubusercontent.com/assets/4588060/6118975/474791da-b091-11e4-95da-b218b9e41375.png)

atom version 0.177.0
os x yosemite 10.10.2

**Comment by 50Wliu** [comment] 2015-02-10 00:50
Duplicate of #4924, please subscribe there for updates.

**Closed by 50Wliu** 2015-02-10 00:50 UTC
