### ISSUE TITLE
Tree View Unhides When Switching Between Split Panes

### ISSUE THREAD

**Issue by eviljoe** [atom/tree-view#796] opened 2016-04-06 14:03 UTC
I have my tree view hidden when I am using split panes too add more horizontal space.  I also have the "Auto Reveal" option enabled.  Whenever I move between split-panes, the tree view becomes visible again.  The auto reveal option should not make the tree view visible if it is hidden.

**Steps To Recreate**
1. Enable the "Auto Reveal" tree view option
2. Open a file
3. Split Atom's view using the `Pane: Split Right` command
4. Open a different file in the right pane
5. Hide the tree view using the `Tree View: Toggle` command
6. Click between the different open panes
   - The tree view will become visible

This behavior happens in safe mode too.

**Comment by durz** [comment] 2016-04-11 05:22
This also happens when switching between tabs, not just switching between split-panes.

**Comment by Ben3eeE** [comment] 2016-06-01 14:57
Is this a duplicate of https://github.com/atom/tree-view/issues/738? I can reproduce all cases in both issues with Auto reveal on but #738 does not mention Auto reveal.

**Comment by ZuBB** [comment] 2016-09-06 13:18
pls fix this

**Comment by Arcanemagus** [comment] 2017-04-04 20:10
@Ben3eeE This is a direct duplicate of https://github.com/atom/tree-view/issues/738#issuecomment-223133421, and fixing this/that comment would likely fix #738 as a whole since I'm guessing when the filer of #738 said "opens" they meant "becomes un-hidden".

**Comment by vraravam** [comment] 2017-04-13 21:49
My usecase is slightly different: I want the tree-view to be open all the time, but with the "auto-reveal" feature, the tree-view captures focus. When I open a file or switch the active text editor, all I was to happen is to reveal the file, but the focus should still remain on the text editor.

**Comment by mupchrch** [comment] 2017-05-14 20:51
This same issue happens when you create a new, empty editor (File > New File). It is annoying to have the tree-view open on its own for a file that isn't even in the tree.

**Comment by alejandrolacasa** [comment] 2017-09-28 09:17
What's the status of this? It is very annoying when working on small screens... I cannot have 3 panes at the same time because of the size of the tree file :(

**Comment by Ben3eeE** [comment] 2017-09-28 09:21
@alejandrolacasa Did you try disabling the `Auto Reveal` setting in the tree-view package settings?

**Comment by alejandrolacasa** [comment] 2017-09-28 09:52
Yes, sure, but then the files are not "revealed" when opening them or switching between tabs. The behaviour I expect is that the files are revealed when switching between them, even if the tree is hidden, but not to make the tree appear if I hidden it on purpose.

This is how VSCode works for instance, and I think it makes sense that way... As I said, working on small screens is kind of difficult if you cannot hide the file tree sometimes...

**Comment by iolsen** [comment] 2018-02-07 21:15
This change was reverted due to test flakiness introduced.

**Comment by 50Wliu** [comment] 2018-02-07 23:10
To clarify: the change itself was not reverted.  But tree-view specs are currently failing which we'll need to sort out before adding this to atom/atom.

**Comment by Ben3eeE** [comment] 2018-03-22 06:31
Closing because https://github.com/atom/tree-view/pull/1225 has been merged addressing the flakiness.

**Closed by Ben3eeE** 2018-03-22 06:31 UTC
Labels: bug, triaged
