### ISSUE TITLE
Tree view focuses on reveal regardless of setting.

### ISSUE THREAD

**Issue by phyllisstein** [atom/tree-view#1070] opened 2017-04-17 20:29 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Hey Atomizers! I hope this isn't a dupe of the infamous #858, but I'm having some trouble with `tree-view@0.217.0-3`. I installed the new beta with Tree View's "Auto Reveal" setting enabled and "Focus on Reveal" disabled. Heretofore, that's always meant that switching from one file to another would show its location in the tree without pulling focus from my editor, which I understand to be the expected behavior. But as of this version, the editor consistently loses focus when I open or change files, and I wind up focused on the tree.

Here's a quick safe-mode screencast illustrating the issue:

![2017-04-17 16_23_15](https://cloud.githubusercontent.com/assets/2207980/25103352/322bb8da-238a-11e7-8cc6-449352a06a23.gif)

As you can see, it doesn't seem to affect tab clicks, but it does affect opening files and navigating with <kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>[</kbd>/<kbd>]</kbd>.

I'd be grateful for any guidance you can provide! Please let me know if I can furnish any more troubleshooting data.

### Steps to Reproduce
1. Enable "Auto Reveal" in Tree View and disable "Focus on Reveal."
2. Double-click a file in Tree View to open it. Observe that the editor loses focus.
3. Open another file, and refocus the editor.
4. Click the first file's tab. Observe that the editor does not lose focus.
5. Use the "Previous/Next Tab" keyboard shortcuts to navigate to the second file's tab. Observe that the editor loses focus.

**Expected behavior:** The editor should stay focused throughout.

**Actual behavior:** `tree-view` steals focus when navigating with the keyboard or opening new files.

**Reproduces how often:** 100%

### Versions
```
❯ atom --version
Atom    : 1.17.0-beta2
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

❯ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.12.2

❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Zbornak
      User Name: Daniel P. Shannon (daniel)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 3:57
```

### Additional Information
💖

**Comment by 50Wliu** [comment] 2017-04-17 20:52
Looks like a regression caused by #1056. /cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment] 2017-04-17 21:13
Oh wow; sorry about that. Fixing now.

**Comment by maxbrunsfeld** [comment] 2017-04-17 22:06
Fixed via https://github.com/atom/tree-view/pull/1056/commits/c8cb0be3a350a33480bbab6b1144d4facc416314. We'll release a beta hotfix soon.

**Closed by maxbrunsfeld** 2017-04-17 22:06 UTC
Labels: bug, regression

**Comment by phyllisstein** [comment] 2017-04-17 22:47
Fabulous, thanks so much for responding so quickly and helpfully!
