### ISSUE TITLE
Allow Tree-View when no file/folder

### ISSUE THREAD

**Issue by monkeymonk** [atom/tree-view#68] opened 2014-03-04 17:51 UTC
Because I usually drag a project folder inside the Tree-View... but for now that open a new window Editor. That's mean I have an editor with my project folder and the tree-view and a editor with nothing...

**Comment by metalim** [comment] 2015-01-14 19:44
No idea what should it show, when there's no file, but when there IS a file, then - folder containing that file.

**Comment by monkeymonk** [comment] 2015-01-14 21:00
In `Sublime Text`, we have a simple empty pane.
![Uploading Capture d’écran 2015-01-14 à 21.59.00.png . . .]()

**Comment by xenio** [comment] 2015-01-18 10:49
I agree, tree view should be open also with no files, it is a simple behaviour of finding the start of the code always on the same position. If I start Atom without any files the code start on the left side of the screen and it is very annoying on large screen.

**Comment by ricardograca** [comment] 2015-01-23 11:29
Well, I just completely wiped my Atom installation and user configuration and reinstalled Atom from scratch (two times) because I thought there was some bug in my configuration preventing the tree view from opening. When even the "Toggle Tree View" command does nothing, it sure looks like a bug.

**Comment by kfix** [comment] 2015-03-20 19:06
I have this at the end of my `init.coffee` to deal with this/my quirky behavior:

```
#bare opens of atom.app should bring up the file tree
if not atom.project.getPath()
  atom.project.setPath(atom.config.get('core.projectHome'))
  atom.commands.dispatch(atom.workspaceView.element, 'tree-view:show')
```

**Comment by mnquintana** [comment] 2015-04-13 16:18
From https://github.com/atom/atom/issues/6179#issuecomment-92413675, it might be worth showing a notification if you try opening the tree view with no project folder added. That way it won't seem broken if nothing happens.

**Comment by ricardograca** [comment] 2015-04-13 17:00
Or just open an empty tree view since that's probably the expected behavior.

**Comment by thedaniel** [comment] 2015-04-13 17:09
> Or just open an empty tree view since that's probably the expected behavior.

Yes, and perhaps the tree view could have an empty state like the panes do that display a message.

**Comment by mnquintana** [comment] 2015-04-13 17:10
> Yes, and perhaps the tree view could have an empty state like the panes do that display a message.
:+1: That sounds good

**Comment by RacerDelux** [comment] 2015-11-13 15:49
Going to poke this along, I just ran into this issue as well, waisted a couple hours of work time before I figured out what was wrong. Really something that needs to be added.

**Comment by dcrockwell** [comment] 2015-11-28 09:24
Getting caught by this problem myself on Windows 7. Even when opening from Explorer, Atom cannot toggle the treeview with `Ctrl+\`, however it can be toggled via the drop-down menu.

**Comment by Swivelgames** [comment] 2016-06-11 21:29
Two years later: `Open`

I just spent nearly hour opening and closing Atom, trying to toggle via Context and Key Shortcut, looking at various Atom config files, and perusing. 😯 

Any chance this ~~enhancement~~ **bug** will be addressed any time soon? It's quite frustrating...

**Comment by metalim** [comment] 2016-06-14 09:18
@Swivelgames Yes. Use Sublime :triumph:

**Comment by jamezpolley** [comment] 2016-06-14 21:59
The title of this enhancement is "Allow tree view when no open file/folder", but I think that's overly specific.

The problem I had is that I was telling the tree view to open (via the usual keyboard shortcut, but also via the command palette) and nothing was happening.

Having the tree view open up would have been one way to solve this; but a  "Cannot show tree view, no open file" error message would have worked nicely as well.

I'd suggest change this from an enhancement to a bug along the lines of "No user feedback when tree view can't be opened". That bug might be solved by an enhancement to "Allow tree view when no open file/folder", but there might also be a simpler solution to the bug.

**Comment by chakrihacker** [comment] 2016-07-10 16:31
I am having the same issue in ubuntu 16.04 and my other lappy with 14.04 runs perfectly please help

**Comment by huckl3b3rry87** [comment] 2016-09-18 20:12
Is there a solution for this?

**Comment by mda6** [comment] 2017-01-06 00:50
Open since 2 years ago? This is funny.. but it scares me enough to go back to sublime - that such a small thing is not resolved YET.. i know, it's allot of stuff to work on to the atom devs but.. still.. i just wanted a polished awesome text editor..

**Comment by deiga** [comment] 2017-01-10 13:33
@huckl3b3rry87 @mda6 @chakrihacker You are very welcome to donate your time and make a fix for this :)

**Comment by lazychino** [comment] 2017-02-15 05:13
maybe showing the home folder by default if no file or folder is opened

**Closed** 2019-06-20 15:36 UTC
Labels: enhancement
