### ISSUE TITLE
"tree-view": hideVcsIgnoredFiles overridden on update

### ISSUE THREAD

**Issue by RachelScodes** [atom/tree-view#924] opened 2016-08-17 18:22 UTC
Pretty simple really. Most options in config file remain intact when atom updates, but `hideVcsIgnoredFiles` gets re-set to false every time atom is updated.

Is this by design?

**Comment by 50Wliu** [comment] 2016-08-17 19:35
No, it is not by design.  Can you paste the output of `apm list --installed` here?

**Comment by RachelScodes** [comment] 2016-08-17 19:46
sure thing. It's happened whenever a single package is updated, or when I update atom itself.

```
Built-in Atom Packages (89)
├── about@1.5.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.0
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.198.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.0
├── language-csharp@0.12.1
├── language-css@0.36.2
├── language-gfm@0.86.0
├── language-git@0.13.0
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.22.0
├── language-javascript@0.119.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.52.0
├── language-shellscript@0.22.3
├── language-source@0.9.0
├── language-sql@0.21.1
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.8
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.64.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.2
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.2
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.238.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.46.0
├── symbols-view@0.113.0
├── tabs@0.98.1
├── timecop@0.33.1
├── tree-view@0.208.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (17) /Users/rachel/.atom/packages
├── aligner-ruby@1.5.0
├── aligner-scss@1.1.0
├── color-picker@2.2.2
├── emmet@2.4.3
├── linter@1.11.16
├── linter-csslint@1.3.2
├── linter-htmlhint@1.3.0
├── linter-jshint@2.1.0
├── linter-php@1.2.0
├── linter-tidy@2.2.0
├── minimap@4.24.7
├── neon-syntax@0.3.6
├── php-cs-fixer@2.5.9
├── react@0.16.0
├── script@3.9.0
├── terminal-plus@0.14.5
└── wakatime@6.0.10

└── (empty)

```

**Comment by austinthecoder** [comment] 2016-08-22 15:57
This just happened for me also. I think it may be the first time it's happened. Here's my info:

Atom version: 1.9.9
OS X: 10.11.6

```
Community Packages (25) /Users/austin/.atom/packages
├── 2-dark-syntax@0.1.1
├── atom-beautify@0.29.10
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.3.3
├── atom-monokai@0.10.4
├── base16-ocean-dark-syntax@1.0.1
├── burn@0.2.1
├── duotone-dark-syntax@1.0.0
├── fruits-syntax@0.0.7
├── gruvbox@1.0.5
├── ir-black-k-syntax@0.1.0
├── ir-black-syntax@0.2.0
├── language-elixir@0.15.0
├── language-haml@0.24.0
├── material-syntax@0.5.0
├── monokai-verbose-syntax@0.1.1
├── no-caffeine-syntax@0.17.2
├── nucleus-dark-ui@0.9.1
├── polaris-syntax@0.1.0
├── predawn-syntax@1.0.2
├── predawn-ui@1.0.2
├── rspec@0.3.2
├── seti-syntax@1.0.1
├── seti-ui@1.3.1
└── unity-ui@2.1.5

└── (empty)
```

**Comment by RachelScodes** [comment] 2016-08-22 21:00
@50Wliu any comments? 
@austinthecoder you had no atom packages installed?

**Comment by lee-dohm** [comment] 2016-08-23 02:59
@RachelScodes I can't reproduce this using Atom v1.9.9 on Mac OS X 10.11.6. I also leave `tree-view.hideVcsIgnoredFiles` enabled and have never seen this spontaneously get disabled on update or at any other time. Can you give us any more information as to how your configuration might be different than normal?

**Comment by lee-dohm** [comment] 2016-08-23 03:00
Also, did you know that if you highlight the Tree View and press `i`, it toggles this setting? Is it possible that occasionally you accidentally press `i` when the Tree View is focused?

**Comment by RachelScodes** [comment] 2016-08-24 17:38
@lee-dohm I know about the `i` keyboard shortcut. Perhaps I wasn't clear in my original issue, but this is after updating atom, upon re-opening the app - when no keys have been pressed - noticing that files and directories are missing from tree-view, and opening the config file to see it's been set to false after updating.

I thought it might have to do with the `script` or `terminal-plus` packages, but Austin had the same issue without either package. I'll document my befores & afters and update this thread the next time it happens.

**Comment by austinthecoder** [comment] 2016-08-25 15:15
@RachelScodes By "atom package" do you mean built-in package? That list was the result of running `apm list --installed`. Here's `apm list` which includes the built-in packages:

```
Built-in Atom Packages (89)
├── about@1.5.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.0
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.198.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.0
├── language-csharp@0.12.1
├── language-css@0.36.2
├── language-gfm@0.86.0
├── language-git@0.13.0
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.22.0
├── language-javascript@0.119.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.52.0
├── language-shellscript@0.22.3
├── language-source@0.9.0
├── language-sql@0.21.1
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.8
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.1
├── metrics@0.53.1
├── notifications@0.64.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.2
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.2
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.238.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.47.1
├── symbols-view@0.113.0
├── tabs@0.98.1
├── timecop@0.33.1
├── tree-view@0.208.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (25) /Users/austin/.atom/packages
├── 2-dark-syntax@0.1.1
├── atom-beautify@0.29.10
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.3.5
├── atom-monokai@0.10.4
├── base16-ocean-dark-syntax@1.0.1
├── burn@0.2.1
├── duotone-dark-syntax@1.0.0
├── fruits-syntax@0.0.7
├── gruvbox@1.0.5
├── ir-black-k-syntax@0.1.0
├── ir-black-syntax@0.2.0
├── language-elixir@0.16.0
├── language-haml@0.24.0
├── material-syntax@0.5.0
├── monokai-verbose-syntax@0.1.1
├── no-caffeine-syntax@0.17.2
├── nucleus-dark-ui@0.9.3
├── polaris-syntax@0.1.0
├── predawn-syntax@1.0.2
├── predawn-ui@1.0.2
├── rspec@0.3.2
├── seti-syntax@1.0.1
├── seti-ui@1.3.2
└── unity-ui@2.1.5

└── (empty)
```

**Comment by lee-dohm** [comment] 2016-08-31 18:14
@RachelScodes A new version of Atom was released today. Let us know if the problem reoccurred.

**Comment by RachelScodes** [comment] 2016-08-31 22:15
@lee-dohm all good for me now! 👍

**Comment by mangatinanda** [comment] 2016-09-01 06:34
I was unaware of _pressing `i` toggles this setting_ and searching all over the internet to fix this. Thanks @lee-dohm you are a lifesaver 👍

**Comment by lee-dohm** [comment] 2016-09-01 17:01
Thanks @RachelScodes for the quick response. Since this appears to be fixed, I'm going to close the Issue. Thanks again!

**Closed by lee-dohm** 2016-09-01 17:01 UTC
Labels: more-information-needed, needs-reproduction
