### ISSUE TITLE
tree-view is not aware of linked working trees

### ISSUE THREAD

**Issue by RomuloPBenedetti** [atom/tree-view#940] opened 2016-09-09 13:45 UTC
It appears Atom can't figure linked working trees exists as a completely different branch.

**Comment by lee-dohm** [comment] 2017-02-07 00:07
Thank you for reaching out!

I'm not sure what you mean by "linked working trees". Can you give some more information and preferably some steps to reproduce the problem?

**Comment by RomuloPBenedetti** [comment] 2017-02-07 12:22
https://git-scm.com/docs/git-worktree

**Comment by lee-dohm** [comment] 2017-02-07 16:56
Thank you for the information. This isn't something that we're going to be able to work on in the near future. For that reason, I'm going to close this issue. If we do decide to work on it in the future, we'll reopen it. Because it isn't a use case that are willing to support right now, we won't be accepting pull requests for this functionality at this time either.

Thanks very much for your interest in Atom!

**Closed by lee-dohm** 2017-02-07 16:56 UTC
Labels: more-information-needed
