### ISSUE TITLE
tree-view becomes visible when switching to another tab and 'auto reveal' is on

### ISSUE THREAD

**Issue by ZuBB** [atom/tree-view#936] opened 2016-09-06 13:10 UTC
STR
* set 'auto reveal' on
* open two different files
* hide tree with cmd+\
* switch to another tab (I use `gT` in vim mode)

AR: tree becomes visible
EX: tree remain hidden

**Comment by Ben3eeE** [comment] 2016-09-06 13:13
This is a duplicate of https://github.com/atom/tree-view/issues/796

**Closed** 2016-09-06 13:17 UTC
