### ISSUE TITLE
Tree View won't update Git status of files/dirs containing chars with accents...

### ISSUE THREAD

**Issue by quenio** [atom/tree-view#586] opened 2015-10-05 11:56 UTC
If you have a directory or file on your Git repo with an accented character, the Git status doesn't get updated on the Tree View. In the case of directories, all files under that directory won't have their Git status updated as well.

Notice in the attached screenshots that the files had already been committed, but the status is still showing as added.

I suspect this must be happening with non-ASCII characters in general.

![screen shot 2015-10-05 at 08 55 42](https://cloud.githubusercontent.com/assets/66532/10279792/ec0dd5fe-6b3e-11e5-9360-e62659612eb5.png)
![screen shot 2015-10-05 at 08 55 55](https://cloud.githubusercontent.com/assets/66532/10279794/f11fcb6a-6b3e-11e5-9c91-691830f03a6d.png)

**Comment by 50Wliu** [comment] 2015-10-05 12:00
Duplicate of atom/atom#1890, please subscribe there for updates.

**Closed by 50Wliu** 2015-10-05 12:00 UTC
