### ISSUE TITLE
TreeView doesn't save settings.

### ISSUE THREAD

**Issue by raffael** [atom/tree-view#331] opened 2015-01-17 19:41 UTC
I'm faced with the problem that I need to re-enable "Hide Ignored Files" whenever Atom starts. What can I do to find the cause here?

**Comment by izuzak** [comment] 2015-02-11 20:06
@raffael A good way to start debugging this is to update to the latest version of Atom and start Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode). If you can still reproduce the problem -- let us know and share which steps exactly reproduce the problem. If you can't reproduce the issue -- it's probably a package causing this behavior.

**Comment by kevinsawicki** [comment] 2015-07-29 16:58
Closing this out since more details weren't provided and this wasn't reproducible.

Please comment if you still see this happening on Atom 1.0.3+, thanks.

**Closed by kevinsawicki** 2015-07-29 16:58 UTC
Labels: more-information-needed
