### ISSUE TITLE
"Show on Right Side" is broken in Atom 1.17.0

### ISSUE THREAD

**Issue by danielmackey** [atom/tree-view#1103] opened 2017-05-18 14:03 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In Atom 1.17.0 (on Mac), "Show On Right Side" no longer renders the tree view on the right side. 

### Steps to Reproduce

1. Download Atom 1.17.0 from atom.io
2. In Settings > Packages > Tree View, toggle on "Show On Right Side"
3. Open a folder/project directory

**Expected behavior:** [What you expect to happen]

I expect that the tree view panel would be on the right side of the window.

**Actual behavior:** [What actually happens]

It stays in its default location on the left side.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time

### Versions

macOS: 10.12.5
Atom: 1.17.0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0
apm: 1.17.0
npm: 3.10.5
node: 6.9.5 x64
python: 2.7.10
git: 2.11.0
tree-view: 0.217.0-7

**Comment by Zireael07** [comment] 2017-05-18 14:19
Duplicate of #1084 

See FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762/1

**Closed** 2017-05-18 15:11 UTC
