### ISSUE TITLE
Tree View "Hide Ignored Names" not working.

### ISSUE THREAD

**Issue by lexicalunit** [atom/tree-view#380] opened 2015-02-20 17:08 UTC
![nothidden](https://cloud.githubusercontent.com/assets/1903876/6305429/c6f1f4d6-b8f0-11e4-9219-dab7afbec650.png)

```
$ apm list | grep tree
├── tree-view@0.157.0
```

```
$ atom --version
0.180.0
```

```
$ cat ~/.gitignore_global | grep pyc
*.pyc
```

And from within the repository which is being displayed in the screen shot:

```
$ cat .gitignore | grep pyc
*.pyc
```

**Comment by izuzak** [comment] 2015-02-20 17:10
Can you share a link to the project so that we can try to reproduce this? Can you reproduce this for _any_ project and _any_ file, or is it happening only for some projects and some files?

**Comment by lexicalunit** [comment] 2015-02-20 17:16
Sure, I'll make an example repo, one sec.

**Comment by lexicalunit** [comment] 2015-02-20 17:22
https://github.com/lexicalunit/test-tree-view

![vs](https://cloud.githubusercontent.com/assets/1903876/6305657/827f8898-b8f2-11e4-9a22-4e0fe9797c52.png)

More details! So it looks like it works when I open the directory that is the repository itself, but not if I open a directory containing that repository. Generally I keep all my repositories in a `~/source` tree and open that parent directory so that it's easy to jump from one repository to another and back again.

**Comment by izuzak** [comment] 2015-02-20 17:25
>  So it looks like it works when I open the directory that is the repository itself, but not if I open a directory containing that repository. 

See, that wasn't so hard. :smile: Closing as a duplicate of https://github.com/atom/atom/issues/2203.

**Closed by izuzak** 2015-02-20 17:25 UTC
Labels: more-information-needed

**Comment by izuzak** [comment] 2015-02-20 17:26
Also, see a recent issue https://github.com/atom/tree-view/issues/375 and a suggested improvement https://github.com/atom/tree-view/pull/376.

**Comment by lexicalunit** [comment] 2015-02-20 18:30
Right on :)
