### ISSUE TITLE
display the file list sorted by time modified

### ISSUE THREAD

**Issue by xu4wang** [atom/tree-view#893] opened 2016-07-20 03:50 UTC
Hello, sometimes when working with a project, I want to know which file/files I modified recently.  

Is it possible for tree-view to display the files sorted by modification time?

Thanks, Xu

**Comment by 50Wliu** [comment] 2016-07-20 13:47
This is a duplicate of #343 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-20 13:47 UTC
