### ISSUE TITLE
"Hide VCS Ignored Files" not saved in config.cson in MacOS

### ISSUE THREAD

**Issue by meventi-stephan** [atom/tree-view#1236] opened 2018-03-21 19:31 UTC
When "Hide VCS Ignored Files" option is set in MacOS in newest Atom IDE 1.25.0 and Atom is closed and opened the setting is lost. If i'm opening config.cson I see following setting:
`"tree-view": {}`

When i makes the same setting in Windows i see following setting in config.cson:
`  "tree-view":
    alwaysOpenExisting: true`

Perhaps this is the problem ...

**Comment by rsese** [comment] 2018-03-21 23:39
Thanks for the report - I'm unable to reproduce with macOS 10.12.6 and Atom 1.25 - my steps:

1. `atom --safe`
2. Check `Settings > Packages > tree-view > Hide VCS Ignored Files`
3. Quit Atom `cmd-q`
4. `atom --safe`

If I check the tree-view settings, `Hide VCS Ignored Files` is checked and if I open `config.cson` I see:

```
  "tree-view":
    hideVcsIgnoredFiles: true

```

Can you reproduce with these steps? Also, what version of macOS are you running?

As a side note, it's super helpful for us if you can fill out the issue template as much as possible.

**Comment by 50Wliu** [comment] 2018-07-31 23:09
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/tree-view/issues/1236#issuecomment-375130987. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by 50Wliu** 2018-07-31 23:09 UTC
Labels: more-information-needed
