### ISSUE TITLE
Tree view ignores directories that contain exceptions

### ISSUE THREAD

**Issue by cbcoutinho** [atom/tree-view#982] opened 2016-11-10 12:36 UTC
I have a git project that is collecting a number of vtk examples that each contain an empty build directory

```
learn_vtk
├── Cylinder
│   ├── build
│   ├── CMakeLists.txt
│   ├── Cylinder.cs
│   ├── Cylinder.cxx
│   ├── Cylinder.py
│   └── Cylinder.tcl
├── DistanceBetweenPoints
│   ├── build
│   ├── CMakeLists.txt
│   ├── DistanceBetweenPoints.cs
│   ├── DistanceBetweenPoints.cxx
│   └── DistanceBetweenPoints.py
.
.
.
```

Since there are a number of example directories, keeping track of individual .gitignore files is cumbersome. The .gitignore file at the root of the project I'm using looks like this

```
*/build/*
!*/build/.gitignore
```

This results in a successful git clone, with empty build directories, but they are still hidden in tree-view

In the tree view, the empty build directories are hidden, even though they are valid and each contain an empty `.gitignore` file. Can you make the `Hide VCS ignored files` option smart enough to recognize these exceptions?

Thanks again!

**Comment by AndreaGriffiths11** [comment] 2017-02-03 22:07
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/196. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by AndreaGriffiths11** 2017-02-03 22:07 UTC
Labels: bug, git
