### ISSUE TITLE
Uncaught Error: Cannot find module 'dialog'Error: Cannot find module 'dialog'    at Function.Module._resolveFilename (module.js:351:15)    at Function.Module._load (module.js:293:25)    at Module.require (module.js:380:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)    at EventEmitter.emit (events.js:119:17)    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)    at EventEmitter.emit (events.js:119:17)

### ISSUE THREAD

**Issue by mloncaric** [atom/tree-view#398] opened 2015-03-10 11:22 UTC
[Enter steps to reproduce below:]

1. Right click on a file
2. and select Delete

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.164.0

### Stack Trace

Uncaught Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)

```
At /Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77

Error: Cannot find module 'dialog'
Error: Cannot find module 'dialog'
    at Function.Module._resolveFilename (module.js:351:15)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/lib/rpc-server.js:128:79)
    at EventEmitter.emit (events.js:119:17)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/browser/api/lib/web-contents.js:99:23)
    at EventEmitter.emit (events.js:119:17)
    at metaToValue (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:77:15)
    at Object.exports.require (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:157:34)
    at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app/src/atom.js:705:23)
    at TreeView.module.exports.TreeView.removeSelectedEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:895:19)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:remove (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/main.js:84:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
    at jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:80:67)
```

### Commands

```
  2x -1:10.4 core:move-right (atom-text-editor.editor.is-focused)
  8x -1:09.4 core:select-right (atom-text-editor.editor.is-focused)
     -1:07.5 core:select-left (atom-text-editor.editor.is-focused)
  4x -1:06.4 core:copy (atom-text-editor.editor.is-focused)
     -1:04.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:52.5 core:paste (atom-text-editor.editor)
  3x -0:43.1 core:backspace (atom-text-editor.editor)
     -0:35.7 core:save (atom-text-editor.editor)
     -0:33.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.3 core:move-left (atom-text-editor.editor.is-focused)
     -0:31.4 core:save (atom-text-editor.editor.is-focused)
     -0:26.4 core:close (atom-text-editor.editor.is-focused)
     -0:13.6 core:save (atom-text-editor.editor)
     -0:10.5 editor:delete-to-beginning-of-line (atom-text-editor.editor)
     -0:08.0 core:save (atom-text-editor.editor)
     -0:00.6 tree-view:open-selected-entry (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "background-tips",
      "atom-jshint",
      "language-objective-c",
      "autoflow",
      "autosave",
      "bookmarks",
      "styleguide",
      "spell-check",
      "snippets",
      "release-notes",
      "package-generator",
      "language-yaml",
      "language-xml",
      "language-toml",
      "language-source",
      "language-shellscript",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-make",
      "language-java",
      "language-go",
      "language-gfm",
      "language-clojure",
      "language-c",
      "welcome",
      "wrap-guide",
      "language-latex",
      "deprecation-cop",
      "meteor-api"
    ],
    "themes": [
      "neutron-ui",
      "neutron-syntax"
    ]
  },
  "tree-view": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-beautify, v0.21.4
atom-cli-diff, v0.8.0
emmet, v2.3.4
neutron-syntax, v0.6.2
neutron-ui, v0.3.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-03-10 15:05
Duplicate of #399, please subscribe there for updates.

**Closed by 50Wliu** 2015-03-10 15:05 UTC
