### ISSUE TITLE
Keep modified/orange color for selected item

### ISSUE THREAD

**Issue by VanCoding** [atom/tree-view#245] opened 2014-10-20 09:29 UTC
When one clicks on an item in the tree view, it gets marked as "selected" with a blue background. Sadly, in this case, the text is always white, even if I modify the file contents. To see if it's marked as "modified", I either have to click on another file or folder (which does also open the file/folder, wich I don't want), or scroll the file to see if some lines are marked as modified, added or deleted, which is also not comfortable.

If it just would keep the colors green and orange, that would be awesome :)

**Comment by izuzak** [comment] 2015-03-04 20:10
I think this is a duplicate of https://github.com/atom/tree-view/issues/197, so closing this in favor of that issue. :v:

**Closed by izuzak** 2015-03-04 20:10 UTC
Labels: enhancement
