### ISSUE TITLE
Squashed directory does not get un-squashed when a file is created inside of it

### ISSUE THREAD

**Issue by forivall** [atom/tree-view#985] opened 2016-11-14 07:16 UTC
![bug-replication-vid](https://cloud.githubusercontent.com/assets/760204/20256218/e4467b8a-a9f6-11e6-8e4b-8f47ce57dc07.gif)

Replication shown in gif above:
```
mkdir -p foo/bar && touch foo/bar/baz
# squashed directory appears in tree view
touch foo/biz
# no way to see biz in tree view
```
then collapse and uncollapse the directory, foo/bar is unsquashed, and biz can be viewed.

I encountered this issue when cloning a git repository with `npm-clone` inside of a project folder.

**Comment by Ben3eeE** [comment] 2016-11-14 07:31
Thanks for the report. This is a duplicate of https://github.com/atom/tree-view/issues/702. You can subscribe there for updates.

**Closed by Ben3eeE** 2016-11-14 07:31 UTC

**Comment by forivall** [comment] 2016-11-17 00:25
Thanks, I didn't find 702 because "collapsed" is a pretty overloaded term and couldn't find it in search. Squashed is what's used in the code, but I didn't find anything through searching that.

Naming things is hard.

**Comment by Ben3eeE** [comment] 2016-11-17 07:19
I believe collapsed is the name in the issue because that is the name of the setting that enables this.
