### ISSUE TITLE
Duplicate folder items on save

### ISSUE THREAD

**Issue by xeor** [atom/tree-view#787] opened 2016-03-25 20:45 UTC
This issue is new for me. I did not see this earlier today, even on the same version.

I have a directory structure like this:

* ./src
  * ./app
    * ./api/service - the api folder is empty now, containing only a service folder
    * ./block
    * ./home
    * app.ts
    * other app.ts files

Earlier today, when I hit cmd+s or click file>save inside a file in `./src/app/*.*`, 2 extra folders of the `api/service` path is showing up. They act as normal folders in the tree-view, but they are duplicates.

Normal view after atom startup
<img width="234" alt="" src="https://cloud.githubusercontent.com/assets/682676/14053474/d16b2182-f2d1-11e5-8ac7-54c7d5d109fb.png">

After saving 2 times inside a app.ts (even tho I didnt change it)
<img width="223" alt="" src="https://cloud.githubusercontent.com/assets/682676/14053501/0034e688-f2d2-11e5-9ba2-4a4dce7d373e.png">

Note that the duplicate folders also show up if I create a new file called eg `test.md`. As long as it is inside the same folder.

The same thing is happening when I run atom with `--safe`
I can't think of anything I've done differently before and after this started happening. I started fresh with an atom installation about a week ago.

I am currently able to replicate this 100%, so I can do some debugging if necessary. The console log is not showing anything.

* atom -v: 1.6.0
* os: osx 10.11.3

**update 1**
This also happens when I type `atom.workspace.saveActivePaneItem()` in the console.

**update 2**
If I places a break at subtree modification of the tree-view, this is the function and when the 2 ghost folders are being added.
<img width="1228" alt="" src="https://cloud.githubusercontent.com/assets/682676/14053926/3c251dd6-f2d5-11e5-9ad6-466f106555e9.png">

**update 3**
If I rename the `service` folder inside the `api` folder to eg `service2`. The problem goes away. Renaming the `api` folder does not make the problem go away.

**update 4**
This problem also went away if I unchecked the `Collapse directories` option (which is unchecked as default), in the `tree-view` plugin settings.
I also noticed when experimenting with this problem that collapsed folders collapses if they are opened when I save. That problem might or might not be related. But it looks like the whole `collapse directories` option is a little flaky when saving a document.

**Comment by lee-dohm** [comment] 2016-03-26 23:47
This sounds like a duplicate of https://github.com/atom/tree-view/issues/705.

**Comment by 50Wliu** [comment] 2016-03-28 13:02
Yeah, definitely looks like a duplicate of #705, so closing in favor of that issue.

**Closed by 50Wliu** 2016-03-28 13:02 UTC
