### ISSUE TITLE
UX - Add a Project Folder by dragging folder from Explorer (outside Atom)

### ISSUE THREAD

**Issue by nahuelhds** [atom/tree-view#795] opened 2016-04-04 14:42 UTC
I'm a Windows user.
Having my tree-view opened in Atom, I'd like to be able to drag a folder from Explorer and drop it inside the tree view. The action would be to add the dragged folder to the tree-view as a "Project Folder"

**Steps which explain the enhancement**
1. Open Explorer
2. Drag a folder. Say: D:\example\project
3. Drop inside the tree-view

**Current and suggested behavior**
Current: nothng
Suggested: add the folder (D:\example\project) as a Project Folder

**Why would the enhancement be useful to most users**

I think it'd be easy to add Project Folders when working with several directories that are not close but they're related

**Screenshots and GIFs**
1. Explorer folder and Atom behind
   ![image](https://cloud.githubusercontent.com/assets/1885647/14251511/c6baebf2-fa59-11e5-96cf-9c07339a21b4.png)
2. Dragging the folder
   ![image](https://cloud.githubusercontent.com/assets/1885647/14251584/16759b9c-fa5a-11e5-8ded-3dce9421b27f.png)
3. Suggested result
   ![image](https://cloud.githubusercontent.com/assets/1885647/14251625/40a83bd6-fa5a-11e5-8baa-3e432b5d7a7d.png)

**Atom Version:** 1.6.2
**OS and Version:** Windows 10, 64bits

**Comment by Ben3eeE** [comment] 2016-11-03 08:53
This is a duplicate of https://github.com/atom/tree-view/issues/480. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-11-03 08:53 UTC
