### ISSUE TITLE
Allow replacing of files in tree view [Feature Request]

### ISSUE THREAD

**Issue by matt3224** [atom/tree-view#1249] opened 2018-05-10 15:29 UTC
I run into this daily, if I drag a file like example.png into a directory that already has an example.png file Atom says something like "Failed to move entry... already exists" which is fair enough.

However it would be massively helpful if instead it could ask "A file called example.png already exists do you want to replace the file or keep both", or cancel.

Thanks!

**Comment by Ben3eeE** [comment] 2018-08-09 07:41
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/860. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-08-09 07:41 UTC

**Comment by mrleblanc101** [comment] 2018-09-23 17:47
Will this ever ship ?
