### ISSUE TITLE
Doesn't keep position setting between sessions

### ISSUE THREAD

**Issue by lmartins** [atom/tree-view#241] opened 2014-10-15 08:27 UTC
Hi,

The plugin is showing a couple of issues on my machine:

1. It doesn't keep the position setting between sessions. I have to move it to the right every time I launch Atom
2. Is says it's disabled, but still works and even shows the time spent on launching the plugin:
https://www.dropbox.com/s/d2ekecdmknzl84f/Screenshot%202014-10-15%2009.27.13.png?dl=0

Update:
Another weird behaviour, if I open a new window with my normal settings active (sidebar at the right), this happens:
https://www.dropbox.com/s/aa7d9qjag2jwujm/Screenshot%202014-10-15%2010.50.49.png?dl=0

Thanks.

**Comment by k98kurz** [comment] 2016-02-01 08:25
-bump-

This happened to me as well. Having my UI switch randomly was the single most infuriating event to interfere with productivity after my switch from Sublime. <swears num=50 /> It took me forever to even figure out it was this package rather than something like "navigator" or "file" or "project viewer" or some name that more accurately describes the functionality/purpose.

**Comment by lee-dohm** [comment] 2016-02-01 20:47
Seeing as we didn't get any additional communication on this bug and I can't reproduce any of the original complaints on the latest version of Atom, I'm going to close this.

@k98kurz Can you please open a new Issue with the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Steps to reproduce the behavior?

**Closed by lee-dohm** 2016-02-01 20:47 UTC
Labels: bug
