### ISSUE TITLE
Collapse single-childed directory chains

### ISSUE THREAD

**Issue by lloeki** [atom/tree-view#374] opened 2015-02-17 15:04 UTC
Say I have:

```
foo
└── bar
    └── baz
        └── qux.txt
```
It'd be nice it the tree view could optionally collapse single-childed directory chains, resulting in this:

```
foo ∕ bar ∕ baz
└── qux.txt
```

GitHub does this, and that's really useful e.g when you have some namespaced/nested thingies in Rails.

**Comment by lee-dohm** [comment] 2015-02-18 03:40
This is a duplicate of #125, just a different separator character in the resulting collapsed view. I think your title is better though.

**Closed by lee-dohm** 2015-02-18 03:40 UTC
Labels: enhancement
