### ISSUE TITLE
Highlight opened files (or mute unopened)

### ISSUE THREAD

**Issue by ProLoser** [atom/tree-view#950] opened 2016-10-05 22:52 UTC
It would be nice if I could differentiate in the tree view which files are already opened. I know there are plugins that make a distinct panel or show the opened files separately from the tree view but I'd merely like to be able to see them within the context of my tree.

**Comment by Ben3eeE** [comment] 2016-10-13 20:36
Closing as a duplicate of https://github.com/atom/tree-view/issues/36. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-13 20:36 UTC

**Comment by ProLoser** [comment] 2016-10-13 20:43
This is not a duplicate, please reopen. 

That issue uses a separate pane ABOVE the tree. This is not what I want. I would like to see the files that are open in my tree with bold font or brighter text or different background, similar to git integration. I don't want to see a redundant flat list of files.

**Comment by ProLoser** [comment] 2016-10-13 21:02
This is an example of what I'm describing, or alternatively bolding the text all the way up the tree (or muting the text of other files). This is not the same as making a new panel as described by the other issue, which takes up more vertical real-estate and pushes down the tree and shows files out of context of their path.

![screen shot 2016-10-13 at 1 58 58 pm](https://cloud.githubusercontent.com/assets/67395/19366864/85ea6c02-914d-11e6-91c8-56ac94a7a907.png)

**Comment by lee-dohm** [comment] 2016-10-14 14:59
@ProLoser Because this is an alternate visualization of the same information, I agree with @Ben3eeE that this is a duplicate. Please add your proposal to the other Issue and we'll evaluate them both together. Having the same discussion twice with only a slight difference in presentation would not be a good use of the team's time.

**Comment by ProLoser** [comment] 2016-10-14 18:24
You've locked the other issue so I can't.

**Comment by ProLoser** [comment] 2016-10-14 18:25
In fact, it looks like you locked it due to +1's and apparently that prevent's people from adding the response emoticons in the new Github UI.

**Comment by simurai** [comment] 2016-10-15 04:26
I tend  to agree with @ProLoser. It is an alternative visualization, but the visualization **is different** (2 lists vs 1 list with highlighting).

At the same time I don't think it's something with high priority. And not sure if it should be part of core. Maybe `package-idea`?

**Comment by ProLoser** [comment] 2016-10-15 22:49
Yeah it may make sense as a separate package.

**Comment by axelpale** [comment] 2018-12-22 21:52
This feature would be useful in code refactoring: one could open the set of files that take part in certain process of the program. If those inter-related files are scattered around the directory hierarchy, that is a sign of yo-yo code antipattern. Highlighting would make this antipattern easier to perceive. 

**Hypothesis:** this feature pushes programmers to unconsciously structure their code better, regardless whether they know about the antipattern or not. **Why?** Programmers usually work on a certain feature. If files of the feature are scattered around the project the tree-view looks a bit nastier because scattered highlights bring a visual nuisance. In contrast, visually more grouped highlights give pleasure to order-seeking minds of a programmer (Simplicity brings pleasure for people in general). Therefore programmers would tend to structure their coding experience to feel more beautiful.
