### ISSUE TITLE
'Search in Directory' option missing from folder context menu

### ISSUE THREAD

**Issue by surdu** [atom/tree-view#1090] opened 2017-05-05 11:19 UTC
When I right-clicked a directory in tree-view I used to get an option like "Search in Directory".

Now, that option appears to be missing:
<img width="271" alt="screen shot 2017-05-05 at 14 16 09" src="https://cloud.githubusercontent.com/assets/11520795/25743506/7090c298-319d-11e7-84df-75c0f39e2997.png">

Versions:
**Os:** OS X El Capitan v10.11.6 (15G1217)
**Atom:**  v1.17.0-beta4 x64 (Safe Mode)
**tree-view:** v0.217.0-5

**Comment by Ben3eeE** [comment] 2017-05-05 12:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/find-and-replace/issues/887. The fix has been cherry picked to beta so it will go out in the next beta hotfix release Atom `1.17.0-beta5`.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-05-05 12:24 UTC

**Comment by surdu** [comment] 2017-05-05 14:48
Sorry, keep forgetting to search closed issues 😞

**Comment by Ben3eeE** [comment] 2017-05-05 20:43
It happens 🙂
