### ISSUE TITLE
Right-clicked items are not highlighted until after context-menu closes

### ISSUE THREAD

**Issue by olmokramer** [atom/tree-view#812] opened 2016-04-19 15:24 UTC
Picture > 1000 words:

![tree-view-focus](https://cloud.githubusercontent.com/assets/3612514/14644001/d4feb9d4-0650-11e6-973c-014b45cd72db.gif)

The file I'm right-clicking in the video isn't highlighted until after the context menu has disappeared. This is quite inconvenient, because in some cases I'm unsure that I clicked the correct item. An example in the video is when I click between the `2=2` and `2=10` items.

**Atom** 1.9.0-dev-c95412b
**OS** Debian (testing)

**Comment by Ben3eeE** [comment] 2016-05-16 13:37
@lee-dohm https://github.com/atom/atom/issues/2991 duplicate? Going from the discussion there it is not limited to the tree-view?

**Comment by lee-dohm** [comment] 2016-05-16 17:31
Yep, this is a duplicate of atom/atom#2991. Since there has been so much discussion there, I'll leave that one open. (This is potentially a problem with right-click in general too.)

Thanks @Ben3eeE for finding the dupe and @olmokramer for reporting the problem!

**Closed by lee-dohm** 2016-05-16 17:31 UTC
Labels: bug
