### ISSUE TITLE
Atom opens a file like a directory

### ISSUE THREAD

**Issue by Serkan-devel** [atom/tree-view#944] opened 2016-09-17 18:56 UTC
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
When I open a text file over "open with atom" it will open a non existent directory with the same filename

### Steps to Reproduce

1. Select a file and open with atom

**Expected behavior:** It should open the selected file

**Actual behavior:** It displays a directory with the same filename
![2016-09-17-203911_1366x768_scrot](https://cloud.githubusercontent.com/assets/16866642/18610302/fe8a6a70-7d18-11e6-8ff8-e7a5f2048f99.png)

### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Linux Kachel 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 50Wliu** [comment] 2016-09-17 22:15
Is this reproducible in safe mode (`atom --safe`)?

**Comment by Serkan-devel** [comment] 2016-09-18 06:30
Running <code>atom --safe /var/www/html/index.html</code>
![2016-09-18-082904_1366x768_scrot](https://cloud.githubusercontent.com/assets/16866642/18613385/0d51a7e2-7d7a-11e6-83f4-d8290eb21b2d.png)
It actually does

**Comment by Ben3eeE** [comment] 2016-09-18 06:52
Since it doesn't reproduce in safe mode that indicates that there is problem with one of your installed community packages and not with the tree-view.

**Comment by Serkan-devel** [comment] 2016-09-18 10:19
I've only installed the minimap package and the atom-material-ui as community theme. Everything else was pre-installed

**Comment by 50Wliu** [comment] 2016-09-18 15:41
As this is non-reproducible in safe mode I'm closing this.

**Closed by 50Wliu** 2016-09-18 15:41 UTC
Labels: linux, more-information-needed, needs-reproduction
