### ISSUE TITLE
"Hide VCS Ignored Files" option doesn't work when opening parent dir

### ISSUE THREAD

**Issue by OmgImAlexis** [atom/tree-view#1042] opened 2017-03-08 00:48 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Hide VCS Ignored Files" isn't working if I open a parent dir of a dir with a .gitignore in it.

For example if I run `atom ~/code/undash`, that dir contains `client` and `server` both of which have a `.gitignore` file as well as a `.git` dir yet everything is shown normally and nothing is greyed out. If I just open the client and server directory the correct files get greyed out.

### Versions
```
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.0
```

### Additional Information

This may be a dupe or similar issue as https://github.com/atom/tree-view/issues/542

![screen shot 2017-03-08 at 11 16 37 am](https://cloud.githubusercontent.com/assets/6525926/23684780/b82ee664-03f0-11e7-82cd-8f7772650b01.png)
![screen shot 2017-03-08 at 11 16 06 am](https://cloud.githubusercontent.com/assets/6525926/23684779/b82efe24-03f0-11e7-9b0e-645d68987088.png)

**Comment by 50Wliu** [comment] 2017-03-08 00:52
This is in fact a duplicate of https://github.com/atom/atom/issues/2203.

**Closed by 50Wliu** 2017-03-08 00:52 UTC
