### ISSUE TITLE
Hide VCS Ignored File does not respect ~/.gitignore

### ISSUE THREAD

**Issue by fulldecent** [atom/tree-view#375] opened 2015-02-18 15:45 UTC
Moved from https://github.com/atom/atom/issues/5592

The setting is shown below. This is the great place where I put stuff like

 > .DS_Store
 > *~
 > *.swp

![screen shot 2015-02-17 at 2 55 54 pm](https://cloud.githubusercontent.com/assets/382183/6236065/4f193c7c-b6b5-11e4-8b77-779db4045ed9.png)

![screen shot 2015-02-18 at 10 45 15 am](https://cloud.githubusercontent.com/assets/382183/6250353/3c4c711c-b75b-11e4-97b6-c62d309d9f02.png)

**Comment by izuzak** [comment] 2015-02-18 16:07
@fulldecent I'm having trouble reproducing this. See what I'm doing:

![ignore](https://cloud.githubusercontent.com/assets/38924/6250643/a44b79a0-b78f-11e4-856e-25e99cda6a8e.gif)

.DS_Store is ignored from `~/.gitignore`, not `.gitignore`, and is correctly hidden when toggling the config option. 

Can you provide the exact steps which reproduce the issue for you in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-modep) (preferably, together with a link to a public repository we can clone to follow those steps), as well as other [debugging information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)?

Also, just to confirm -- the folder you're looking at in that second screenshot is a Git repository, correct?

**Comment by izuzak** [comment] 2015-02-18 16:09
> Also, just to confirm -- the folder you're looking at in that second screenshot is a Git repository, correct?

If this isn't true, then you're probably reporting this: https://github.com/atom/atom/issues/2203

**Comment by fulldecent** [comment] 2015-02-18 16:52
Ah yes! Sorry about that. My "project" folders *contain* the VCS folder.

Created a patch to document this.

**Comment by acontreras89** [comment] 2015-06-18 18:53
Since this issue is part of https://github.com/atom/atom/issues/2203, shouldn't it be closed?

**Comment by bj0** [comment] 2015-06-19 17:46
I was seeing this if I created the global .gitignore after opening Atom.  After restarting atom, the global ignores were hidden.

**Comment by FallingBullets** [comment] 2015-06-30 13:55
I'm still seeing hidden files in all folders opened in the sidebar other than the first one.

**Comment by benogle** [comment] 2015-10-12 23:33
Closing as a dupe of https://github.com/atom/atom/issues/2203

**Closed by benogle** 2015-10-12 23:33 UTC
Labels: more-information-needed
