### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/ray.foote/Documents/Biologistex/biolife/src/portal/viewship/templates/viewship/index.html'

### ISSUE THREAD

**Issue by fierlion** [atom/tree-view#366] opened 2015-02-11 21:28 UTC
[Enter steps to reproduce below:]

1. copied (cmd-C) code-formatted text from https://thinkster.io/django-angularjs-tutorial/
2. closed several file tabs in atom in quick succession.
3. cmd-V in atom editor.

**Atom Version**: 0.178.0
**System**: Mac OS X 10.10.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.154.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/ray.foote/Documents/Biologistex/biolife/src/portal/viewship/templates/viewship/index.html'

```
At fs.js:503

Error: ENOENT, no such file or directory '/Users/ray.foote/Documents/Biologistex/biolife/src/portal/viewship/templates/viewship/index.html'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:422:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:329:27)
  at TreeView.module.exports.TreeView.pasteEntries (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:922:58)
  at space-pen-div.atom.commands.add.tree-view:paste (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:270:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -0:00.6 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "*.pyc"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-02-15 12:12
I'm pretty sure this is a duplicate of https://github.com/atom/tree-view/issues/356. The steps to reproduce you listed don't reproduce the issue for me, and the stack trace you provided shows that something was pasted in the tree view (not the editor).

I'm able to get the same stack trace by following the steps in https://github.com/atom/tree-view/issues/356:

1. copy a file in the tree view
2. delete that file
3. try to paste the file in the tree view

**Closed by izuzak** 2015-02-15 12:12 UTC
Labels: bug
