### ISSUE TITLE
Drag+drop project folders into Atom

### ISSUE THREAD

**Issue by SpectralKH** [atom/tree-view#1024] opened 2017-01-18 19:43 UTC
Not 100% sure if tree-view is the right package for this, but Atom really needs to improve here;
You cannot drag+drop a folder into an Atom window if there already is a project folder - Not even if you specifically drop it in the tree-view.
Neither can you drag folders onto the Atom icon to add them as project folders (Possibly macOS specific).

**Comment by 50Wliu** [comment] 2017-01-19 00:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #480. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-19 00:05 UTC
