### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/wangshiyuan/Developer/python/flask/microblog-version-0.1/__init__.pyc'

### ISSUE THREAD

**Issue by wangshiyuan88** [atom/tree-view#364] opened 2015-02-10 02:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.148.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/wangshiyuan/Developer/python/flask/microblog-version-0.1/__init__.pyc'

```
At fs.js:580

Error: ENOENT, no such file or directory '/Users/wangshiyuan/Developer/python/flask/microblog-version-0.1/__init__.pyc'
  at Error (native)
  at Object.fs.renameSync (fs.js:580:18)
  at Object.fsPlus.moveSync (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/node_modules/fs-plus/lib/fs-plus.js:221:17)
  at TreeView.module.exports.TreeView.pasteEntries (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:859:32)
  at space-pen-div.atom.commands.add.tree-view:paste (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:250:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at Ipc.<anonymous> (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/window-event-handler.js:70:67)
  at Ipc.emit (events.js:110:17)
  at process.<anonymous> (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:118:17)
  at Ipc.sendSync (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/window-event-handler.js:141:33)
  at HTMLDocument.handler (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Users/wangshiyuan/Developer/Tool/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -2:03.9 editor:newline (atom-text-editor.editor)
     -2:01.3 core:save (atom-text-editor.editor)
 38x -1:48.6 core:backspace (atom-text-editor.editor)
  2x -1:32.3 core:move-left (atom-text-editor.editor)
     -1:28.3 core:save (atom-text-editor.editor)
     -1:11.6 core:select-all (atom-text-editor.editor)
     -1:10.8 core:paste (atom-text-editor.editor)
     -1:09.4 core:save (atom-text-editor.editor)
     -0:48.9 core:backspace (atom-text-editor.editor)
  7x -0:47.4 core:move-right (atom-text-editor.editor)
     -0:45.4 core:backspace (atom-text-editor.editor)
     -0:44.1 core:save (atom-text-editor.editor)
     -0:04.0 core:backspace (atom-text-editor.editor)
  7x -0:03.3 core:move-right (atom-text-editor.editor)
     -0:01.4 core:backspace (atom-text-editor.editor)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.2
color-picker, v1.4.3
html-helper, v0.2.3
linter, v0.10.0
linter-csslint, v0.0.11
linter-javac, v0.1.3
linter-jscs, v1.4.9
linter-pylint, v0.2.0
linter-tidy, v0.0.1
minimap, v3.5.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-02-10 02:33
This looks like a duplicate of #360

**Closed by kevinsawicki** 2015-02-10 02:33 UTC
