### ISSUE TITLE
Color project in tree when status is modified

### ISSUE THREAD

**Issue by IanLee1521** [atom/tree-view#809] opened 2016-04-15 21:33 UTC
It would be a nice addition if when the status of any files in a project were modified, the project would colorize (?) accordingly. The current behavior means that when I have multiple projects / Git repos that are all collapsed at the top level, I can't tell which have modifications in them without expanding the trees.

This is handled now in [directory-view.coffee#L59](https://github.com/atom/tree-view/blob/492e344149bd42755d90765607743173bb9b7c0a/lib/directory-view.coffee#L59) and [file-view.coffee#L27](https://github.com/atom/tree-view/blob/492e344149bd42755d90765607743173bb9b7c0a/lib/file-view.coffee#L27) for directory and file respectively. I'm thinking that whatever logic is used for the directory tree is probably the closest and just needs to be adapted to effect the root directory.

I've created a mock-up of what I think this could look like by adding the styling directly to the `.header.list-item`:

``` html
<div class="header list-item" style="color: #ff982d;"><span class="name icon icon-repo" data-name="foo" title="foo" data-path="/Users/Ian/foo">foo</span></div>
```

![image](https://cloud.githubusercontent.com/assets/828452/14575336/f6953ebc-0315-11e6-9ab6-e6f6d7009161.png)

I also tried digging into the source code to see how I might be able to make a pull request, but this is my first look at coffee script, and I don't quite understand what I'm looking at... :stuck_out_tongue: 

Versions:
- Atom 1.7.1
- Tree View 0.205.0
- Mac OS X 10.11.4

**Comment by IanLee1521** [comment] 2016-05-17 04:08
Recommended labels: `enchancement` and `git`

**Comment by rsese** [comment] 2017-02-23 20:30
I came across this issue while searching for something else but I think this looks like a duplicate of https://github.com/atom/tree-view/issues/564?  If I'm mis-understanding let me know but otherwise, you may want to subscribe there for updates.

**Closed by rsese** 2017-02-23 20:30 UTC

**Comment by IanLee1521** [comment] 2017-02-25 17:41
That's @rsese, that does look like the same issue. Cheers.
