### ISSUE TITLE
tree-view not cooperating "Show On Right Side"

### ISSUE THREAD

**Issue by davnajork** [atom/tree-view#1119] opened 2017-05-25 06:32 UTC
![screen shot 2017-05-24 at 11 26 52 pm](https://cloud.githubusercontent.com/assets/26757747/26438539/82de8a1c-40d8-11e7-918d-fa53d5899ee2.png)

My tree-view is **not** being displayed on the **RHS** despite my configuration in the settings.

**Comment by Zireael07** [comment] 2017-05-25 06:49
Duplicate of #1084 

Also you haven't filled out the template...

**Closed** 2017-05-25 07:13 UTC

**Comment by davnajork** [comment] 2017-05-25 07:59
Very helpful, thanks....
