### ISSUE TITLE
Uncaught Error: EACCES: permission denied, scandir <not-readable-folder>

### ISSUE THREAD

**Issue by scale-gmbh-it** [atom/tree-view#777] opened 2016-03-18 07:12 UTC
1. Open any file locating within a folder with non-readable other folders
2. Tree-View won't open, showing the following error message.

I tried opening the file `/home/xxx/file-to-edit.txt` either with "open with..." or by drag&drop.
The `/home/xxx/.dbus` folder is owned by root:root with chmod 0700.

**Atom Version**: 1.7.0-beta0
**System**: Ubuntu 14.04.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.203.2
### Stack Trace

Uncaught Error: EACCES: permission denied, scandir '/home/xxx/.dbus'

```
At fs.js:856

Error: EACCES: permission denied, scandir '/home/xxx/.dbus'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:497:28)
    at Object.fsPlus.listSync (/usr/share/atom-beta/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:171:18)
    at Directory.module.exports.Directory.squashDirectoryNames (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:379:23)
    at new Directory (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:28:25)
    at Directory.module.exports.Directory.getEntries (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:256:30)
    at Directory.module.exports.Directory.reload (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:312:20)
    at Directory.module.exports.Directory.expand (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory.js:356:12)
    at tree-view-directory.DirectoryView.expand (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory-view.js:177:24)
    at tree-view-directory.DirectoryView.initialize (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/directory-view.js:81:21)
    at TreeView.<anonymous> (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:599:16)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:604:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:105:12)
    at TreeView.View [as constructor] (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/tree-view.js:56:45)
    at Object.module.exports.createView (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/main.js:105:25)
    at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle (/usr/share/atom-beta/resources/app.asar/node_modules/tree-view/lib/main.js:32:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom-beta/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom-beta/resources/app.asar/src/atom-environment.js:1085:28)
    at EventEmitter.outerCallback (/usr/share/atom-beta/resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:00.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "tree-view": {
    "squashDirectoryNames": true
  }
}
```
### Installed Packages

``` coffee
# User
gutter-shadow, v0.6.0
highlight-selected, v0.11.2
language-ldif, v0.3.0
language-puppet, v0.18.0
minimap, v4.21.0
minimap-git-diff, v4.2.0
minimap-split-diff, v0.3.0
project-manager, v2.7.6
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

Proposed solution:
Step over folders which are not readable but mark them within the tree.
E.g. in italic font or with a small lock besides the name.

**Comment by 50Wliu** [comment] 2017-09-11 20:40
Fixed by #761.  Looks like tree-view wasn't updated on atom/atom for a while, but I can confirm that it's fixed in Atom 1.19.x.

**Closed by 50Wliu** 2017-09-11 20:40 UTC
Labels: bug, uncaught-exception
