### ISSUE TITLE
Tree view blanks out

### ISSUE THREAD

**Issue by littlebee** [atom/tree-view#709] opened 2016-01-20 23:05 UTC
Hey guys,

I've been having this problem where the treeview blanks out on me.  It only happens when working in my ginormous work repo.  It blanks out everything after an arbitrary file.  

Atom 1.4.0
OSX 10.10.5

Interesting quirk:  If I drag atom to my external monitor, the whole tree is visible again.  Weird, huh?

**Comment by 50Wliu** [comment] 2016-01-21 00:37
@littlebee Can you by any chance upload a picture of what you're seeing?  Does the entire Tree View disappear, or just a portion of it?  What UI theme are you using?  And finally, does this still happen in safe mode (`atom --safe`)?  Sorry for all the questions, just trying to get all the needed info :smile:.

**Comment by littlebee** [comment] 2016-01-21 02:19
sorry, I forgot to add that.   Just the bottom portion of it.  Files and tree visible above a certain point that seems arbitrary.  
<img width="766" alt="settings_ __users_bwilkerson_projects_zulily_htdocs_ems" src="https://cloud.githubusercontent.com/assets/593784/12469624/49848bda-bfa2-11e5-9b66-8f8644d418e3.png">
<img width="376" alt="upordownindicator_cjsx_ __users_bwilkerson_projects_zulily_htdocs_ems" src="https://cloud.githubusercontent.com/assets/593784/12469629/51b24180-bfa2-11e5-8041-c561e42d0e24.png">

**Comment by littlebee** [comment] 2016-01-21 02:22
I'm also using the sync-settings package, so you can check out my other settings here:  https://gist.github.com/littlebee/34a60734de79f6f78c56

Thanks for the fast reply!

**Comment by 50Wliu** [comment] 2016-01-21 02:33
Ok.  In that case I want to say that this is a duplicate of atom/one-dark-ui#109 and has been fixed in the 1.5.0 betas.  As a temporary workaround you can apply the following to your `styles.less` file:
```less
.tree-view::before {
  transform: none;
}
```

**Closed by 50Wliu** 2016-01-21 02:33 UTC
Labels: more-information-needed

**Comment by littlebee** [comment] 2016-01-23 19:50
cool!  thank you.   this just approached annoyance overload :)
