### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by dengpengks** [atom/tree-view#328] opened 2015-01-16 03:09 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Mac OS X 10.9.5
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.147.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:360

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:360:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:337:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:291:19)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:487:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:414:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -4:06.8 core:copy (atom-text-editor.editor)
     -3:54.4 core:select-all (atom-text-editor.editor)
     -3:53.8 core:copy (atom-text-editor.editor)
     -3:05.6 core:select-all (atom-text-editor.editor)
     -3:05.0 core:copy (atom-text-editor.editor)
  5x -0:38.1 core:select-up (atom-text-editor.editor)
     -0:36.5 core:copy (atom-text-editor.editor)
     -0:09.3 core:select-all (atom-text-editor.editor)
     -0:08.6 core:copy (atom-text-editor.editor)
     -0:00.6 core:select-all (atom-text-editor.editor)
     -0:00.0 core:copy (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.2.2
jsformat, v0.7.10
language-jade, v0.3.0
seti-ui, v0.3.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-01-16 13:48
Duplicate of atom/atom#307, please subscribe there for updates.

**Closed by 50Wliu** 2015-01-16 13:48 UTC
