### ISSUE TITLE
tree-view:show not working if no project folder

### ISSUE THREAD

**Issue by SpectralKH** [atom/tree-view#1025] opened 2017-01-18 19:45 UTC
I don't see why this wouldn't work. If you were able to do this, you could right-click to tree-view and click "Add project folder," which is only convenient. What about fixing that - Otherwise, why not?

**Comment by 50Wliu** [comment] 2017-01-19 00:06
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #68. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-01-19 00:06 UTC
