### ISSUE TITLE
On restart, Project folder persists in Tree view even after it is removed before closing application.

### ISSUE THREAD

**Issue by ankitaggarwal011** [atom/tree-view#508] opened 2015-07-07 14:14 UTC
**Configuration**
* System: Windows 7 (x64).
* Atom: 1.0.0 (Pre-built zipped package).
* No third-party packages.
* The same issue happens with atom --safe (Safe mode).

**Steps to reproduce**
* Open any project folder in Atom.
* Remove the project folder from tree view.
* Close the Atom application.
* Reopen the Atom application.

The removed Project folder in the Tree view persists even after it was removed before the Atom application was closed.

Since, after the project is removed from tree view, it is not supposed to come up again without specifying, I doubt that this is by design.

Can anybody confirm this behavior? Thanks!

**Comment by Ben3eeE** [comment] 2016-10-06 18:00
This sounds like a duplicate of https://github.com/atom/atom/issues/12495. I am closing this in favor of that one since it has more discussion. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-06 18:00 UTC
Labels: bug, needs-reproduction
