### ISSUE TITLE
[Feature Request] Allow permanent deletion of files instead of moving to trash

### ISSUE THREAD

**Issue by nonnymoose** [atom/tree-view#1289] opened 2018-11-25 17:40 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I would like to be able to permanently delete files from the tree view instead of moving them to the trash, similar to Nautilus's implementation in which the user may enable a second delete option, "Delete Permanently", beneath "Move to Trash" and mapped to <kbd>Shift</kbd>+<kbd>Del</kbd>.

### Steps to Reproduce

1. Right click on a file in Tree View
2. Locate "Delete"

**Expected behavior:** A "Delete Permanently" option is located beneath "Delete"

**Actual behavior:** There is no "Delete Permanently" option

**Reproduces how often:** Always

### Versions

```
Atom    : 1.32.2
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.4.1
node 11.2.0 x64
python 2.7.15
git 2.19.2
```
Arch Linux, installed from release `2018-11-01`, all packages up to date at time of writing

**Comment by rsese** [comment] 2018-11-27 06:40
Thanks for contributing!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/856 - see Lee's comment here for more context /cc https://github.com/atom/tree-view/issues/856#issuecomment-357325782.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-27 06:40 UTC

**Comment by nonnymoose** [comment] 2018-11-27 12:44
Whoops! Sorry about that. I did try to ensure that I wasn't creating a duplicate, but that one was a little too subtle for me :wink:
