### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by danielpennypacker** [atom/tree-view#300] opened 2014-12-31 22:53 UTC
[Enter steps to reproduce below:]

1. All I did was save a go package and this kept coming up!? not sure why 

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Users/drp/.atom/packages/autocomplete-plus/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/Users/drp/.atom/packages/autocomplete-plus/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:22.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:21.7 editor:select-to-first-character-of-line (input.hidden-input)
  2x -0:21.3 editor:select-to-end-of-word (input.hidden-input)
     -0:20.4 core:move-down (input.hidden-input)
  2x -0:20.1 editor:move-to-end-of-word (input.hidden-input)
  4x -0:19.6 editor:move-to-beginning-of-word (input.hidden-input)
     -0:18.7 editor:select-to-beginning-of-word (input.hidden-input)
     -0:18.4 core:copy (input.hidden-input)
     -0:18.1 core:move-up (input.hidden-input)
  5x -0:18.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:16.8 editor:select-to-end-of-line (input.hidden-input)
     -0:16.5 core:paste (input.hidden-input)
     -0:15.5 core:save (input.hidden-input)
 11x -0:13.2 core:backspace (input.hidden-input)
  2x -0:03.4 core:save (input.hidden-input)
     -0:00.0 core:copy (input.hidden-input)
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
autocomplete-gocode, v0.5.0
autocomplete-plus, v0.22.14
go-plus, v3.0.11

# Dev
No dev packages
```

/cc @atom/core

**Comment by izuzak** [comment] 2015-01-02 20:40
Duplicate of atom/atom#4421.

**Closed by izuzak** 2015-01-02 20:40 UTC
