### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by railsocial** [atom/tree-view#325] opened 2015-01-13 20:28 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/Users/maxmacpro/Downloads/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -5:47.2 core:backspace (input.hidden-input)
     -5:46.9 core:save (input.hidden-input)
     -0:00.0 core:copy (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-neon-ui",
      "neon-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-neon-ui, v0.37.1
neon-syntax, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-01-13 20:28
Duplicate of atom/atom#4421 and atom/atom#307.

**Closed by kevinsawicki** 2015-01-13 20:28 UTC
