### ISSUE TITLE
"Split <direction>" option currently provides no real functionality for directories

### ISSUE THREAD

**Issue by jarle** [atom/tree-view#1189] opened 2017-10-05 13:44 UTC
### Description
When right clicking a directory in tree-view, and selecting `Split <direction>`, an empty pane is opened. 

### Steps to Reproduce

Right click a directory in tree-view and select any of the "split"-options. The dispatched handler will be the [atom-core](https://github.com/atom/atom/blob/d623a412435564955ab13474fa2bf9a4aaa22ec2/menus/linux.cson#L222-L230) binding which create a new pane inside tree-view.

**Expected behavior:**

Two variants:
1. (Either) I don't expect these options (split on directory context menu)
1. (Or) I expect all files in the directory to be opened in separate tabs in the direction of the split.

**Actual behavior:**
Atom opens an empty pane _inside_ tree-view, making the options superfluous.

**Comment by Ben3eeE** [comment] 2017-10-05 14:14
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14201. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-10-05 14:14 UTC
