### ISSUE TITLE
"Hide VCS Ignored Files" option hide files unmatched with pattern in .gitignore

### ISSUE THREAD

**Issue by bugdanov** [atom/tree-view#902] opened 2016-08-01 03:36 UTC
Hi !

With `**/.*` in .gitignore, it should hide only the "hidden files" whose names are beginning with "." except the files explicitely added to the project with "git add -f"

But when I open a folder with this pattern in .gitignore, I see only an empty tree.

Now when I add one or more file in the directory they are shown in the tree. But those that were already here when I did open the folder are still not listed.

After trying to figure out what was happening I've been redirected here :-)

Thanks in advance !

**Comment by AndreaGriffiths11** [comment] 2017-02-07 00:37
I was able to reproduce this using Atom v1.13.1 on Mac OS X 10.12.3.

**Comment by wjk** [comment] 2017-03-10 23:39
@AndreaGriffiths11 I'm also seeing this, albeit under slightly different circumstances. I have the line `*/` in my gitignore, which Git correctly treats as ignoring only directories. However, as far as I can tell, Atom treats this as `*` instead, hiding all items inside the affected directory from the tree view. I have to override this behavior by using the `!` prefix to explicitly negate files I want included, despite this being redundant as far as Git itself is concerned.

I'm using Atom 1.15.0, on macOS 10.12.3.

**Comment by overboen** [comment] 2017-04-11 15:29
Here's a screenshot of the issue I'm having. In the .gitignore, I have it ignoring `**/target/`, but instead of just ignoring a directory called `target`, it's ignoring any directory with target in its name.

This is in Atom version 1.15.0 and tree-view version 0.214.1 running on Windows 7.

![atombug_gitignore_0](https://cloud.githubusercontent.com/assets/6709318/24916839/f86d89ea-1ea0-11e7-8d37-9025c94e8426.PNG)

![atombug_gitignore_1](https://cloud.githubusercontent.com/assets/6709318/24916840/f87528ee-1ea0-11e7-9776-bc4a14959d48.PNG)

**Comment by overboen** [comment] 2017-04-11 16:15
After looking through some of the tree-view and git-utils code, it looks like the gitignore logic is handled by a dependency on [libgit2](https://github.com/libgit2/libgit2). There is an issue reported over there that seems to be related to this.

https://github.com/libgit2/libgit2/issues/3224

**Comment by 50Wliu** [comment] 2018-07-31 03:08
This appears to be fixed now that Atom is using libgit2 0.27.0.  I can no longer reproduce on Atom 1.31.0-dev-9654502fc.

**Closed by 50Wliu** 2018-07-31 03:08 UTC
Labels: bug, git, triaged
