### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by steko** [atom/tree-view#278] opened 2014-12-12 11:29 UTC
Uncaught TypeError: Unable to watch path

**Atom Version**: 0.157.0
**System**: linux 3.17.4-301.fc21.x86_64
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.137.0
### Steps To Reproduce
1. newly installed 0.157.0
2. open folder of local git repo
3. try to open file by clicking on it in the tree-view
### Stack Trace

```
At /usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:364:109)
  at File.module.exports.File.willAddSubscription (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:101:14)
  at File.willAddSubscription (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61)
  at File.module.exports.File.onDidChange (/usr/local/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:85:12)
  at TextBuffer.module.exports.TextBuffer.subscribeToFile (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1085:44)
  at TextBuffer.module.exports.TextBuffer.setPath (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:277:14)
  at new TextBuffer (/usr/local/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:100:14)
  at Project.module.exports.Project.buildBuffer (/usr/local/share/atom/resources/app/src/project.js:463:16)
  at Project.module.exports.Project.bufferForPath (/usr/local/share/atom/resources/app/src/project.js:438:63)
  at Project.module.exports.Project.open (/usr/local/share/atom/resources/app/src/project.js:392:19)
  at Workspace.module.exports.Workspace.openUriInPane (/usr/local/share/atom/resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/usr/local/share/atom/resources/app/src/workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/usr/local/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:637:31)
  at TreeView.module.exports.TreeView.entryClicked (/usr/local/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:381:18)
  at tree-view-file.<anonymous> (/usr/local/share/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/usr/local/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/usr/local/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

/cc @atom/core

**Comment by Koltharius** [comment] 2015-01-07 11:45
same error version 0.165.0

**Comment by masterviana** [comment] 2015-01-07 17:53
same error

**Comment by Koltharius** [comment] 2015-01-08 23:20
the error persist, I can't open any file. please fix it =(

**Comment by Koltharius** [comment] 2015-01-09 10:23
I followed instructions on this page to solve it https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path:

On a terminal, do:

 sudo sysctl fs.inotify.max_user_watches=32768

then restart Atom. If it solves your problem, make it permanent by doing:

echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_user_watches

**Comment by ubilli** [comment] 2015-01-22 05:26
Thanks @Koltharius  for the help, it worked for me.

**Comment by slang800** [comment] 2015-02-05 16:20
error still exists in 0.177

**Comment by izuzak** [comment] 2015-02-11 20:29
@steko @masterviana @slang800 Have you tried the approach mentioned in https://github.com/atom/tree-view/issues/278#issuecomment-69316940, after updating to the latest version of Atom?

**Comment by slang800** [comment] 2015-02-11 20:32
@izuzak: yep, the workaround @Koltharius mentioned works for me

**Comment by izuzak** [comment] 2015-02-12 13:21
Going to close this then, thanks @slang800. If the instructions above don't help someone -- please feel free to leave a comment.

**Comment by slang800** [comment] 2015-02-12 14:37
Eh... that's a nice _workaround_, but it's still very broken and shouldn't be causing that error when using the default `max_user_watches` setting. Or, if it really is required, something should at least be added to the installation instructions to mention that the setting needs to be changed.

**Comment by izuzak** [comment] 2015-02-12 14:41
@slang800 Have you read https://github.com/atom/atom/issues/2082 ?

**Comment by jmm** [comment] 2015-02-12 19:29
@izuzak The approach mentioned in the comment you linked to definitely hasn't solved the problem for me, through Atom 0.174.0. I don't understand why you would close the issue after one day based on feedback from one user who isn't even the original reporter. I have read atom/atom#2082. See also atom/atom/issues/4849 atom/node-pathwatcher/issues/39.

**Comment by izuzak** [comment] 2015-02-12 19:59
@jmm Three different users on this thread mentioned that approach fixed the problem for them, no users mentioned that the approach didn't work for them, and the original reporter didn't respond for over a month to this comment: https://github.com/atom/tree-view/issues/278#issuecomment-69316940. Does that explain why I closed the issue?

Can you clarify which issue exactly you are seeing? The issue https://github.com/atom/atom/issues/4849 isn't closed, and doesn't seem to be the same issue as this one. As far as I can tell, these users are _not_ on a samba share. Is there a reason why we should have two issues open for that problem?

**Comment by jmm** [comment] 2015-02-12 20:24
@izuzak 

> Does that explain why I closed the issue?

Sort of. Seems like a highly optimistic interpretation to me. You consider the `inotify.max_user_watches=32768` setting to be an acceptable and permanent solution to this problem (assuming it actually even works)?

> Can you clarify which issue exactly you are seeing?

I'm seeing the issues I describe in atom/atom#4849 and atom/node-pathwatcher#39, and now when it happens I get a dialog telling me to report it here (which I'll do the next time it happens after I upgrade Atom, unless it's miraculously fixed).

> The issue atom/atom#4849 isn't closed, and doesn't seem to be the same issue as this one.

Who can say? (Maybe you can, but I can't.) This error keeps morphing and jumping around.

> As far as I can tell, these users are not on a samba share. Is there a reason why we should have two issues open for that problem?

For me it's a huge headache and it's persisted for months through every version of Atom I've used and some of the issues like atom/node-pathwatcher#39 have been languishing for months with no action.

I have no idea if the samba share is relevant. But I tried the approach you pointed to on the system running the samba server to no avail.

**Comment by jmm** [comment] 2015-02-12 20:46
Just happened again with Atom 0.179.0 / Win 7 x64. Popup dialog referred me to this issue. I've already tried [this idea](https://github.com/atom/tree-view/issues/278#issuecomment-69316940) (on the Ubuntu system running the samba server that I'm loading some files from).

**Comment by izuzak** [comment] 2015-02-12 20:51
@jmm Are you able to create a new issue from Atom when you see that exception or would you like us to reopen this one?

**Comment by jmm** [comment] 2015-02-12 21:02
@izuzak When it's been showing up since 0.174.0 it alternates between referring me to this issue and inviting me to open a new one. Earlier today it invited me to open a new one, then I upgraded to 0.179.0 and got the error right away, referring me to this issue.

**Comment by izuzak** [comment] 2015-02-12 21:07
> I have no idea if the samba share is relevant. 

Just to make sure I understand, are/were you able to reproduce the issue for local files only?

**Comment by jmm** [comment] 2015-02-12 22:07
> Just to make sure I understand, are/were you able to reproduce the issue for local files only?

I'm not sure if it's ever happened when trying to open local files. Most of the time I'm opening files from the samba share. There are no consistent steps to reproduce, so I can't just try it either.

Thanks for reopening the issue.

**Comment by slang800** [comment] 2015-02-12 22:28
I'm able to reproduce this every time I set my `max_user_watches` to the default 2^15, I'm not using samba or dropbox (as people described in the #2082), and I'm only opening local files.

**Comment by izuzak** [comment] 2015-02-13 09:09
@jmm Does that mean that you tried to reproduce the problem with only local files and wasn't able to, or that you didn't even try to do that? 

If the latter is true, would you be willing to invest some time into confirming the assumption that this doesn't happen for you when you work with local files only (e.g. open and save a bunch of files and projects)? From what you've described, when you work with samba files -- the error happens on a daily basis, so trying to work with local files for a while should trigger the issue (an hour or two, the more the better). Confirming that assumption might be helpful in understanding the different sources of these problems, and in that way push the issue forward. Since this particular issue with network drives affects a small number of users and you seem to be having luck in triggering it on a daily basis (even though not reliably) -- you're in a unique position to offer help.

**Comment by izuzak** [comment] 2015-02-13 09:13
@slang800 That's why I was saying that I believe that @jmm is experiencing a different issue (which manifests with the same stack trace) -- you're using local files and the suggested workaround works for you, while @jmm is using network files and the workaround doesn't work for him.

I've reopened the issue so please feel free to add any information which might be helpful in resolving the problems.

**Comment by slang800** [comment] 2015-02-13 17:24
@izuzak - yeah, that's what I thought - I just wanted to clarify the issue I'm having since my inital report was really vague.

Also, I'm trying to see what processes are using up inotify watches to check if this is really atom's fault. I found a few places that reccomended this command: `for foo in /proc/*/fd/*; do readlink -f $foo; done | grep inotify | sort | uniq -c | sort -nr`, but the results that I get from that only show about 40 watches being used... far lower than the 8000-something default. I tested this after changing back to the default limit and making sure I could reproduce the error at the same time that I ran the aforementioned command, but it only reports around 40 watches.

I tried enabling debugging for inotify with `echo 1 >> /sys/kernel/debug/tracing/events/syscalls/sys_exit_inotify_add_watch/enable`, and then tailing `/sys/kernel/debug/tracing/trace`. Doing this, I saw a bunch of watches being added by `Chrome_FileThre-4853` (about 300). So, I closed chrome, ran `pkill chrome` to get rid of the background processes, then tested atom and found that (with the default watches limit) the issue no longer existed.

I can't blame chrome because I haven't found a reliable way of testing how many watches are being used by each process, but I can say that this issue isn't entirely atom's fault. So I think the next step in investigating this would be to find out how to count the number of watches being used by each process on the system. If we find that the 8000-something watches are actually being exhaused for a good reason, then I'd feel good about asking users to rise the limit, and maybe asking for the default to be changed.

**Comment by jmm** [comment] 2015-02-18 14:25
@izuzak

> @jmm Does that mean that you tried to reproduce the problem with only local files and wasn't able to, or that you didn't even try to do that?

I tried briefly after it happened the usual way (opening files from the samba share).

> If the latter is true, would you be willing to invest some time into confirming the assumption that this doesn't happen for you when you work with local files only (e.g. open and save a bunch of files and projects)? From what you've described, when you work with samba files -- the error happens on a daily basis, so trying to work with local files for a while should trigger the issue (an hour or two, the more the better).

I can't imagine I'd be able to devote that much time to trying to debug this, especially without any consistent steps to try following, and it would be difficult if not impossible to simulate my normal usage pattern using local files instead. When it happens the usual way I'll try opening some local files and see if it kicks in at all, but I don't think it will. When it happens the usual way I've sometimes tried working around it by switching from opening the files via UNC paths to opening them via a mapped drive. I think I've had mixed results with that.

> Confirming that assumption might be helpful in understanding the different sources of these problems, and in that way push the issue forward. Since this particular issue with network drives affects a small number of users and you seem to be having luck in triggering it on a daily basis (even though not reliably) -- you're in a unique position to offer help.

Does Atom generate log files or anything that would provide further insight?

**Comment by izuzak** [comment] 2015-02-18 14:39
> > (an hour or two, the more the better).
> I can't imagine I'd be able to devote that much time to trying to debug this,

That's unfortunate, but thanks for giving it a thought.

> it would be difficult if not impossible to simulate my normal usage pattern using local files instead.

Out of curiosity, what do those patterns look like exactly and why are they difficult to reproduce with local files? 

> Does Atom generate log files or anything that would provide further insight?

I'm not aware of such logs. Do you have any specific suggestions about what exactly could be logged in addition to the stack trace?

**Comment by jmm** [comment] 2015-02-18 19:21
> Out of curiosity, what do those patterns look like exactly

Opening files and folders, checking code in and out with git, cloning repos with git, `npm install`, etc. etc.

> why are they difficult to reproduce with local files?

Because my whole development stack (web, database, and application servers, code repos, build tools, etc.) are running on the system that runs the samba server.

> Do you have any specific suggestions about what exactly could be logged in addition to the stack trace?

No, no idea. I thought Atom might generate some more debugging data since the stack traces are obviously inadequate to track down the problem.

What do these errors relate to, on a high level -- monitoring the file system for changes?

**Comment by mark-hahn** [comment] 2015-03-25 02:06
I'm stuck on this.  I'm opening a local folder but it is the dropbox folder so that may have something to do with it.  I'll copy it to another folder and try again but I really need to use dropbox.

BTW, changing this to a warning instead of an exception would be nice.

**Comment by MarcMcIntosh** [comment] 2015-04-18 00:23
i used to get this smae problem in an other project when grunt was watching to mny files.

**Comment by ThomasG77** [comment] 2015-06-01 15:56
I was unable to solve the issue with changing only config with:

    sudo sysctl fs.inotify.max_user_watches=32768

Echoing variables related to inotify with `sudo sysctl -a |grep inotify`, I found other variables.

In my case, the way to solve was changing

    sudo sysctl fs.inotify.max_user_instances=256

to

    sudo sysctl fs.inotify.max_user_instances=128

**Comment by MarcMcIntosh** [comment] 2015-06-04 22:53
Could the hugepage settings effect the number filesbeing watched?

cat  /proc/sys/vm/nr_hugepages 
cat /sys/kernel/mm/transparent_hugepage/enabled 

grep Huge /proc/meminfo
grep PageTables /proc/meminfo

https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt
https://shk.io/2015/03/22/transparent-huge-pages/

**Closed** 2021-07-24 13:31 UTC
Labels: bug, needs-reproduction, network, uncaught-exception
