### ISSUE TITLE
VCS ignored .pyc file still shown in treeview

### ISSUE THREAD

**Issue by michaelaye** [atom/tree-view#684] opened 2015-12-28 23:45 UTC
As attached screenshot shows, `.pyc` files are still shown in the treeview, even so my .gitignore file has this:
```bash
*.py[cod]
```
which is coming from the standard Github Python ignore file. (so, shouldn't be a surprise)

So, the filtered files are shown in dark grey, but I would remove them completely from sight in Atom, isn't that possible?

<img width="220" alt="screenshot 2015-12-28 16 40 06" src="https://cloud.githubusercontent.com/assets/69774/12027320/bda10346-ad81-11e5-96ed-155d99b88a59.png">

**Comment by 50Wliu** [comment] 2015-12-28 23:59
Hi @michaelaye, you can make the Tree View hide ignored files by pressing `i` while the tree view is active (you can also enable it within the Tree View settings, but I find the keyboard shortcut easier :smile:).

**Comment by michaelaye** [comment] 2015-12-29 00:03
Pressing `i` is not working here. And I can't see a setting in Tree View (version 0.198.0) that would control if an ignored file is shown or not. "Hide VCS Ignored Files" is activated.

**Comment by michaelaye** [comment] 2015-12-29 00:09
If invoked via the command palette also nothing changes in the tree-view.

**Comment by 50Wliu** [comment] 2015-12-29 01:33
Hmm, that's weird.  Are you sure you aren't seeing this (I apologize in advance for the light theme)?
![tree-view-hide-vcs-ignored-files](https://cloud.githubusercontent.com/assets/2766036/12028233/1eed1b60-ada2-11e5-929d-996848a9ecd9.png)

In addition, can you reproduce this in safe mode (`atom --safe`)?  Thanks!

**Comment by michaelaye** [comment] 2015-12-31 02:48
I don't understand what you mean by "you aren't seeing this". As I stated that hook is active for me, but the VCS Ignored Files are only greyed out as you can see from above screenshot, instead of being invisible.

**Comment by michaelaye** [comment] 2015-12-31 02:50
I just reproduced it in safe mode as well.

**Comment by 50Wliu** [comment] 2015-12-31 03:15
Sorry, I missed the part where you said the option was already enabled.  If you change the `.gitignore` contents to read merely `*.pyc`, does that fix the issue (probably won't since `__pycache__` also isn't hidden, but it's worth a try)?

**Comment by michaelaye** [comment] 2016-01-03 04:28
I'm not at my office Mac currently, but FYI, everything works at my laptop with the same plugins (I think). So maybe something is just 'broken' with my office iMac setup? Some file in bad state or something like that? Can I flush some cache or similar things to reset the status of the plugin somehow?

**Comment by 50Wliu** [comment] 2016-01-03 16:55
> Can I flush some cache or similar things to reset the status of the plugin somehow?

Try renaming the `~/.atom` folder to something like `~/.atom-backup`.  That will reset your Atom configuration to all the defaults (though I'm surprised that safe mode didn't fix it).

**Comment by ijanos** [comment] 2016-02-28 18:51
Hi, I can reproduce this. 

Create a directory inside a git repository and start atom with `atom .` inside that directory. tree-view will display ignored files in that directory in grey and not hide them. 

If you think this is a different bug, I will kindly open a new issue for it.

**Comment by lee-dohm** [comment] 2016-02-29 22:39
@ijanos That's not a bug, there is a performance problem with that in degenerate cases. Specifically the problem is that some people have their home directory set as a git repository. Then if they open anything under their home directory that isn't a repository, there's a huge slow down while Atom tries to keep track of modified/added/etc status for every file in their home directory.

**Comment by ijanos** [comment] 2016-03-01 06:50
I see your point but I still think there is a bug somewhere. In my use-case tree-view will list ignored files grey but not hide them. If the feature is disabled how does it know which file should be grey?

**Comment by cabloo** [comment] 2016-04-22 23:02
I am experiencing the same issue as above. My folder structure (from the root of the git repository):

```
themes/default
    .gitignore
    public/
```

Contents of `themes/default/.gitignore`:

```
/public
```

Tree View does NOT show the `themes/default/public` directory (as expected) when I open the root folder of the git repository. But it does show the public directory (unexpected) when I open the `themes` or `themes/default` folder. This public directory is greyed out - so Tree View is obviously aware that the file is `.gitignore`'d, but it's still showing it.

It appears to me that whatever fixes these degenerate cases (I think it's checking whether or not the root of the git directory is the current directory) is negatively affecting normal use cases as well.

**Comment by lee-dohm** [comment] 2016-04-22 23:22
@michaelaye Were you able to reproduce the problem? Or is it fixed for you now?

**Comment by lee-dohm** [comment] 2016-04-22 23:23
@cabloo That is a different symptom of https://github.com/atom/atom/issues/2203

**Comment by michaelaye** [comment] 2016-04-22 23:29
Sorry, i stopped using Atom, too many issues for me.

**Comment by lee-dohm** [comment] 2016-04-22 23:32
Thanks for the response @michaelaye.

Since we don't have a repro case for this, I'm closing the issue. If anyone has specific steps to reproduce this (which aren't atom/atom#2203) please open a new Issue.

**Closed by lee-dohm** 2016-04-22 23:32 UTC
Labels: bug, git, more-information-needed, needs-reproduction
