### ISSUE TITLE
Can not delete file on tree view V.1.5.3

### ISSUE THREAD

**Issue by Peelz** [atom/tree-view#753] opened 2016-03-04 10:47 UTC
I can not right-click and delete file or folder on treeview .This problem appear only my window 7 ,but working on my Linux mint17 . I'm tried to re-install ,but still not working .

**Comment by Zireael07** [comment] 2016-03-04 11:34
Duplicate of tree view#666?

**Comment by 50Wliu** [comment] 2016-03-04 12:35
Yes.  This issue has been fixed in Atom 1.7.0.

**Closed by 50Wliu** 2016-03-04 12:35 UTC
