### ISSUE TITLE
Somehow I wound up with 2 tree views

### ISSUE THREAD

**Issue by kmdavis** [atom/tree-view#280] opened 2014-12-12 18:34 UTC
As you can see in the screenshot below, I have 2 treeviews, but only 1 shows up in settings. The one visible in settings was marked as Disabled, but when I enabled it, I got 2 tree views. I don't know where the other one lives. Both have identical markup, btw.

![screen shot 2014-12-12 at 1 31 00 pm](https://cloud.githubusercontent.com/assets/132806/5417013/30d150ec-8203-11e4-8e13-76428b965a95.png)

**Comment by dstroot** [comment] 2015-01-05 19:40
I am seeing *exactly* the same issue!  Will investigate further...

**Comment by izuzak** [comment] 2015-02-11 19:54
Yep, I was able to reproduce the double tree view by installing sublime-tabs and re-enabling the tree view package (it's disabled after installing sublime-tabs).

If anyone can reproduce this in the latest version of Atom in safe mode -- let us know. Closing this :v:

**Closed by izuzak** 2015-02-11 19:54 UTC

**Comment by pori** [comment] 2016-01-28 18:39
Just got this in `1.4.1`. Though, I am not sure if it's entirely a bug considering the root tree view icons are different. What do they mean? I can't find documentation specifying a distinction.

<img width="902" alt="screen shot 2016-01-28 at 1 31 39 pm" src="https://cloud.githubusercontent.com/assets/3485555/12654795/c558f97c-c5c3-11e5-993c-626a1b810c72.png">

Starting in safe made fixes the problem. This has happened on multiple occasions, however.

**Comment by lee-dohm** [comment] 2016-01-28 18:44
Since starting in Safe mode fixes the problem, it is almost assuredly a package you have installed that is creating the second tree view.

**Comment by pori** [comment] 2016-01-28 18:49
Gotcha. Which one of these is the proper tree-view? The one on the right?

**Comment by lee-dohm** [comment] 2016-01-28 19:03
I assume so ... but I can't be sure.
