### ISSUE TITLE
Text rendering issue

### ISSUE THREAD

**Issue by seaside98** [atom/tree-view#493] opened 2015-06-25 20:52 UTC
This happens to me every now and then. I will try to find a way to consistently replicate the issue.
![screen shot 2015-06-25 at 3 49 32 pm](https://cloud.githubusercontent.com/assets/6372893/8365300/d1f050b2-1b51-11e5-87a8-8dd7991b4693.png)

**Comment by mnquintana** [comment] 2015-06-25 22:46
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4924 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-25 22:46 UTC
