### ISSUE TITLE
Gitignore overrides not handled correctly

### ISSUE THREAD

**Issue by hermanbergwerf** [atom/tree-view#971] opened 2016-11-02 23:42 UTC
I have these lines in my root `.gitignore` (among many others):
```
build/
!/lib/build/
```

The second line is supposed to override the first line. Which is working successfully with the git CLI. However in Atom the directory and all its files still appear grayed out.

**Comment by AndreaGriffiths11** [comment] 2017-02-03 22:50
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/196. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by AndreaGriffiths11** 2017-02-03 22:50 UTC
