### ISSUE TITLE
Failed to activate the tree-view package

### ISSUE THREAD

**Issue by ZuBB** [atom/tree-view#991] opened 2016-11-23 09:33 UTC
[Enter steps to reproduce below:]

I do not have exact one, but my best guess is that this happened after this: seems it happens when reopen atom with changed file in project that has been deleted..

System: Ubuntu 16.04
Atom Version: 1.12.4
tree-view: v0.210.0

Stack Trace
```
Failed to activate the tree-view package

At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at Directory.module.exports.Directory.subscribeToRepo (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:116:42)
    at new Directory (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:51:12)
    at TreeView.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:570:23)
    at TreeView.module.exports.TreeView.updateRoots (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:587:10)
    at TreeView.module.exports.TreeView.initialize (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:106:12)
    at TreeView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new TreeView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:56:45)
    at Object.module.exports.createView (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:105:25)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/tree-view/lib/main.js:22:14)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

config 

```
"*":
  "atom-beautify":
    _analyticsUserId: ..
  autosave:
    enabled: true
  core:
    autoHideMenuBar: true
    disabledPackages: [
      "autosave"
      "archive-view"
      "go-to-line"
      "language-c"
      "language-clojure"
      "language-csharp"
      "language-java"
      "language-make"
      "language-mustache"
      "language-objective-c"
      "language-perl"
      "language-php"
      "welcome"
      "language-toml"
      "language-property-list"
      "image-view"
      "bookmarks"
    ]
    projectHome: "~/work/"
  editor:
    fontSize: 21
    showIndentGuide: true
  "exception-reporting":
    userId: ..
  linter:
    errorPanelHeight: 26
  "sync-settings":
    _analyticsUserId: ...
    _lastBackupHash: ...
    gistId: ...
    personalAccessToken: ...
  "tree-view":
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
    squashDirectoryNames: true
  "vim-mode":
    useClipboardAsDefaultRegister: false
    useSmartcaseForSearch: true
  welcome:
    showOnStartup: false
  whitespace:
    ensureSingleTrailingNewline: false
```

**Comment by ZuBB** [comment] 2016-11-23 09:34
this is kind of continuation of https://github.com/atom/tree-view/issues/895

**Comment by ZuBB** [comment] 2016-11-23 09:39
@50Wliu I guess https://github.com/atom/tree-view/issues/671 in my case is related/happens after this.

the whole story seems to be next

* go to /tmp
* clone any package there
* open atom with some existing proj
* add folder from step \#2 to project
* hack some file from that new folder but do not save
* close atom
* kill that folder in /tmp
* reopen atom and start getting bugs

**Comment by kadecole** [comment] 2017-02-10 15:28
I had the same problem. 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.213.1


### Stack Trace

Failed to activate the tree-view package

```
At ENOENT: no such file or directory, lstat '/Users/kcole/Library/Caches/com.github.atom.ShipIt/update.cTF7SdD'

Error: ENOENT: no such file or directory, lstat '/Users/kcole/Library/Caches/com.github.atom.ShipIt/update.cTF7SdD'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/Users/kcole/Library/Caches/com.github.atom.ShipIt/update.cTF7SdD/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/app.asar/src/native-compile-cache.js:53:23)
    at /app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:41)
    at /app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/atom-space-pen-views/lib/main.js:18:28)
    at /app.asar/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:19:10)
    at /app.asar/node_modules/tree-view/lib/tree-view.js:1494:4)
```

### Commands

```
     -0:05.5.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
ansible-vault 0.3.1 
atom-jinja2 0.6.0 
change-case 0.6.3 
git-plus 7.2.2 
language-ansible 0.2.1 
split-diff 1.1.1 
```

**Comment by markellisdev** [comment] 2017-02-11 19:22
[Enter steps to reproduce:]

I attempted to open a .py file from the Finder.

Atom: 1.14.1 x64
OS: Mac OS X 10.11.6
Thrown From: tree-view package

ENOENT: no such file or directory, lstat '/Users/*********/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE'

```
Error: ENOENT: no such file or directory, lstat '/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at Object.<anonymous> (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:41)
    at Object.<anonymous> (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
    at Module._compile (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:18:28)
    at Object.<anonymous> (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:19:10)
    at Object.<anonymous> (/Users/markellis/Library/Caches/com.github.atom.ShipIt/update.GdXLpeE/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1494:4)
```

**Comment by Kendos-Kenlen** [comment] 2017-04-01 14:43
Hi,

I have the same problem with a fresh version of atom (no .atom), it happens on first opening.

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Failed to activate the tree-view package
Module did not self-register.
Hide Stack Trace
Error: Module did not self-register.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/node_modules/tree-view/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/node_modules/tree-view/node_modules/pathwatcher/lib/main.js:218:4)
    at Module._compile (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:13:17)
    at Object.<anonymous> (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/node_modules/tree-view/lib/directory.js:433:4)
    at Module._compile (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:31:15)
    at Object.<anonymous> (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/node_modules/tree-view/lib/tree-view.js:1502:4)
    at Module._compile (/nix/store/3a7ll4f9j52r7m056b8dpwlw4xnwz93m-atom-1.15.0/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)

**Comment by NeQuissimus** [comment] 2017-04-05 00:51
Same issue, same versions as @Kendos-Kenlen.
Does not happen with 1.14.4, but immediately when starting 1.15.0 after an update or as a fresh install.

**Comment by Kikobeats** [comment] 2017-04-06 08:39
same problem here after the last release

**Comment by Luchanso** [comment] 2017-04-06 11:16
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-1


### Stack Trace

Failed to activate the tree-view package

```
At uri.match is not a function

TypeError: uri.match is not a function
    at Project.module.exports.Project.resolvePath (/app.asar/src/project.js:330:29)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:410:26)
    at TreeViewPackage.createOrDestroyTreeViewIfNeeded (/packages/tree-view/lib/tree-view-package.js:58:51)
    at TreeViewPackage.activate (/packages/tree-view/lib/tree-view-package.js:25:17)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-clock 0.1.6 
atom-ternjs 0.18.2 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
editorconfig 2.2.2 
file-icons 2.1.2 
git-blame 0.4.12 
git-control 0.9.0 
intentions 1.1.2 
javascript-snippets 1.2.1 
language-babel 2.57.2 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.2 
minimap 4.27.1 
multi-cursor-increment 0.1.1 
node-debugger 1.10.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
script 3.14.1 
split-diff 1.3.0 
sync-settings 0.8.1 
Zen 0.16.4 
```

**Comment by zenwalker** [comment] 2017-04-06 17:31
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.217.0-2


### Stack Trace

Failed to activate the tree-view package

```
At uri.match is not a function

TypeError: uri.match is not a function
    at Project.module.exports.Project.resolvePath (/app.asar/src/project.js:330:29)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:410:26)
    at TreeViewPackage.createOrDestroyTreeViewIfNeeded (/packages/tree-view/lib/tree-view-package.js:58:51)
    at TreeViewPackage.activate (/packages/tree-view/lib/tree-view-package.js:25:17)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
     -1:19.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
atom-jade 0.3.0 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.2 
gutter-shadow 0.7.0 
highlight-selected 0.13.1 
indentation-indicator 1.0.0 
intentions 1.1.2 
language-api-blueprint 1.0.2 
language-docker 1.1.7 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-restructuredtext 1.0.2 
language-vue 0.21.2 
linter 2.1.2 
linter-eslint 8.1.4 
linter-flake8 2.1.5 
linter-golinter 1.2.2 
linter-ui-default 1.2.2 
MagicPython 1.0.9 
markdown-writer 2.6.4 
minimap 4.27.1 
minimap-autohide 0.10.1 
react 0.16.2 
sepia-syntax 1.1.0 
sort-lines 0.14.0 
Stylus 3.1.0 
Zen 0.16.4 
```

**Comment by Ben3eeE** [comment] 2017-04-06 18:48
@zenwalker It looks like you are running a dev version of the `tree-view` instead of the version that is bundled with Atom do this:

1. Exit Atom
1. Open a command prompt
1. execute apm uninstall tree-view

This will ensure that you run the version that is bundled with Atom. The latest dev version only works with Atom 1.17.

Let me know if you have any questions.

**Comment by zenwalker** [comment] 2017-04-06 20:53
@Ben3eeE Wow, thanks! Now it works. I never knew that this version is dev, just always pressed the update button in packages 🤔

**Comment by riveraeu** [comment] 2017-04-07 17:31
@Ben3eeE worked for me, thanks!

**Comment by 50Wliu** [comment] 2018-08-02 22:06
The original exception hasn't happened to anyone else since it was reported, so I'm closing until it can be reproduced.

**Closed by 50Wliu** 2018-08-02 22:06 UTC
Labels: needs-reproduction, triaged, uncaught-exception
