### ISSUE TITLE
Using right click menu in Tree View or Reveal in Tree View causes Atom to crash.

### ISSUE THREAD

**Issue by scott-wilson** [atom/tree-view#317] opened 2015-01-08 01:16 UTC
OS: Windows 7
Atom Version: 0.168

Dump from atom.exe --wait:
```
/C:/Atom/resources/app/static/index.js (64)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at process.target._send (child_process.js:482:28)
  at process.target.send (child_process.js:415:12)
  at global.emit (c:\Atom\resources\app\src\task-bootstrap.js:54:22)
  at Object.console.error (c:\Atom\resources\app\src\task-bootstrap.js:20:21)
  at process.<anonymous> (c:\Atom\resources\app\src\task-bootstrap.js:67:22)
  at process.emit (events.js:107:17)
  at process._fatalException (node.js:251:26)
```

**Comment by kevinsawicki** [comment] 2015-01-08 01:17
I believe this a duplicate of https://github.com/atom/atom/issues/4904 thanks for the stack

**Closed by kevinsawicki** 2015-01-08 01:17 UTC
