### ISSUE TITLE
Does tree-view support searching filename in sidebar

### ISSUE THREAD

**Issue by hilojack** [atom/tree-view#836] opened 2016-05-16 09:33 UTC
I'm a vimer, and I usually search filename in tree-view as  the following:
![image](https://cloud.githubusercontent.com/assets/1781999/15279264/099da376-1b55-11e6-8801-c02c1bc92802.png)

Could tree-view support this function?

**Comment by Ben3eeE** [comment] 2016-06-07 18:09
Duplicate of https://github.com/atom/tree-view/issues/159 or #200?

**Comment by 50Wliu** [comment] 2016-06-07 20:17
Thanks @Ben3eeE.

**Closed by 50Wliu** 2016-06-07 20:17 UTC
