### ISSUE TITLE
Directories being marked as status-added when there are git-ignored children

### ISSUE THREAD

**Issue by Xapphire13** [atom/tree-view#1112] opened 2017-05-22 17:08 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom Tree-View is marking directories as `status-added` when the directory contains files not tracked by git.

### Steps to Reproduce

1. Add ignored files/extensions to your `.gitignore`
2. Cause ignored file to be generated (building a project generally causes this to happen)
3. See that almost all of your project folders are now green in Tree-View

**Expected behavior:** Ignored files shouldn't change the state of Tree-View

**Actual behavior:** Ignored files cause the status of directories to change

**Reproduces how often:** Always

See this picture of the simplest reproduction (note, I am showing ignored files so you get the full context, the issue is there with the ignored files turned off also):
![image](https://cloud.githubusercontent.com/assets/3392349/26320128/912898a0-3ed6-11e7-954f-924910054eb6.png)

### Versions

**OS**: Win 10
**Atom**: 1.17.0 x64
**Tree-View**: 0.217.0-7

### Additional Information

Looking at the Tree-View [code](https://github.com/atom/tree-view/blob/master/lib/directory.coffee#L86-L102) that is responsible for adding the status CSS, it seems like the root cause is likely in the built in Atom git repository code. Still filing this bug since Tree-View has the observable symptom.

**Comment by Xapphire13** [comment] 2017-07-10 20:45
Investigated further, I __think__ this may be caused by the following flag in [atom/git-utils](https://github.com/atom/git-utils/blob/master/src/repository.cc#L308). This was added by @kevinsawicki in [this](https://github.com/atom/git-utils/commit/e4bd7223f0d5ae8555239be47514e24610f3f000) commit. I'm wondering if this was unintentional.

**Comment by willpoorman** [comment] 2018-04-03 19:47
I'd like to plus one this. Running into the same issue. The Git tab shows my directory as clean because it's reading the .gitignore file properly but the tree view show a directory as green when I have a file in it that is ignored in the .gitignore file. The file itself shows as being greyed out though, same as in Xapphire13's picture, as it should since it's being ignored.

**Comment by Arcanemagus** [comment] 2018-04-06 06:33
@willpoorman Are you able to reproduce this on Atom v1.26.0-beta1? I just tried replicating this and it seems to no longer be possible on Atom v1.26.0-beta1.
![image](https://user-images.githubusercontent.com/427137/38406413-a6e78bc6-3929-11e8-9701-d31f427decc6.png)


For reference here's a permanent link of what @Xapphire13 linked above: [git flag in atom/git-utils](https://github.com/atom/git-utils/blob/a68918140eabeb1199723152255e91d90a7b1fa8/src/repository.cc#L308).

**Comment by 50Wliu** [comment] 2018-07-31 23:08
Closing due to lack of repo on Atom 1.26.

**Closed by 50Wliu** 2018-07-31 23:08 UTC
Labels: more-information-needed
