### ISSUE TITLE
"Hide VCS ignored files" not working with subdirectory of VCS root

### ISSUE THREAD

**Issue by pydolan** [atom/tree-view#585] opened 2015-10-01 13:21 UTC
I have a project using Git for VCS. If I open the root directory with Atom, all ignored files are hidden by Atom Tree View when "Hide VCS ignore files" is enabled.  If I open a subdirectory of this project, these files always show.  Having a .gitignore in the directory does help either.  

I haven't dug into the tree-view code, but I'm guessing it checks for a .git directory, and then ignores based on any .gitignore files. Ideally, it would look in parent/grandparent/etc. directories, but obviously that can get pretty costly, so **I do not propose that**. Instead, perhaps we simply check for a .gitignore file (and any other VCSs' equivalent ignore files).

Thoughts?

**Comment by snowcxt** [comment] 2015-10-07 02:17
+1

**Comment by izuzak** [comment] 2015-10-08 12:17
Thanks for the report, @pydolan -- I think this is a duplicate of https://github.com/atom/tree-view/issues/447 (the title of the issue mentions submodules, but I believe the problem is broader than that). See my comment here https://github.com/atom/tree-view/issues/447#issuecomment-106771377 which attempts to explain what's going on. I'm going to close this, but please let me know if this doesn't explain the behavior you observed.

**Comment by izuzak** [comment] 2015-10-08 12:17
And please feel free to add a comment to that issue :v: -- it's good to have all feedback in one place.

**Closed by izuzak** 2015-10-08 12:17 UTC
