### ISSUE TITLE
Deleting multiple files results in only a single file being deleted and the rest becoming deselected

### ISSUE THREAD

**Issue by adamreisnz** [atom/tree-view#1050] opened 2017-03-26 18:34 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Deleting a selection of multiple files results in only a single file being deleted and the rest of the files becoming deselected

### Steps to Reproduce

1. Select multiple files in tree view using shift click
2. Right click the selection and choose Delete
3. Observe that only one file remains selected when the confirmation dialog appears
4. Confirm the deletion

**Expected behavior:** [What you expect to happen]
All files that were selected are deleted

**Actual behavior:** [What actually happens]
Only one file gets deleted, the rest becomes unselected

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

OS X 10.12.3

Atom    : 1.16.0-dev-6f9a536
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.16.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.10.1

**Comment by 50Wliu** [comment] 2017-03-27 19:33
It looks like this is very similar to #1033.

**Comment by a7madgamal** [comment] 2017-04-16 14:08
@50Wliu agree, I think the main issue is losing multi-file selection on mouse click

**Comment by Endemoniada** [comment] 2017-05-22 07:47
I can confirm the issue as well. Also the related issue, which has been an issue from the beginning, from what I can tell. It's never worked for me.

macOS 10.12.4
Atom 1.17.0

**Comment by T-BriX** [comment] 2017-05-23 07:39
I noticed, that when have selected multiple files and you right-click on the filename directly, the wrong context menu opens. This is the one for a single file (`'.tree-view .full-menu'`) and not for multi selection (`'.tree-view .multi-select'`). This one only opens when you right-click beside the name.

**Comment by isalew** [comment] 2017-05-25 18:28
I am experiencing the same issue.
macOS 10.12.4
Atom 1.17.1 x64

**Comment by geovanisouza92** [comment] 2017-05-30 14:13
Same here,

Ubuntu 16.04
Atom ^1.16 x64

**Comment by T-BriX** [comment] 2017-05-30 15:06
When you're clicking on the file name directly, the context menu for a single file is opening. I found a workaround for this, by simply right click beside the name.
![0f01bb82-3f9d-11e7-913e-12f3b7a72550](https://cloud.githubusercontent.com/assets/21077695/26590223/472533a0-455a-11e7-8bde-35abb04b1408.png)

**Comment by rohan-deshpande** [comment] 2017-06-07 11:01
Had the same issue, using the delete key works but right clicking and selecting delete will only delete one file 

macOS Sierra 10.11
Atom 1.17.1

**Comment by fabouru1985** [comment] 2017-06-13 11:06
Here same problem mac os 10.12.4
Atom 1.17.2

**Comment by 50Wliu** [comment] 2017-07-21 04:38
Fixed by #1115.

**Closed by 50Wliu** 2017-07-21 04:38 UTC
Labels: bug
