### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by trololosha4real** [atom/tree-view#326] opened 2015-01-14 11:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.147.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /opt/atom/resources/app/src/project.js:355

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/opt/atom/resources/app/src/project.js:355:15)
  at Project.module.exports.Project.bufferForPath (/opt/atom/resources/app/src/project.js:332:63)
  at Project.module.exports.Project.open (/opt/atom/resources/app/src/project.js:286:19)
  at Workspace.module.exports.Workspace.openUriInPane (/opt/atom/resources/app/src/workspace.js:485:29)
  at Workspace.module.exports.Workspace.open (/opt/atom/resources/app/src/workspace.js:412:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/opt/atom/resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/opt/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
  8x -0:00.0 core:backspace (atom-text-editor#editor.fontSize.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment] 2015-01-14 12:38
Duplicate of atom/atom#4421.

**Closed by 50Wliu** 2015-01-14 12:38 UTC
