### ISSUE TITLE
Enhancement: Don't restrict “Add to project” to folders – enable for files also

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/tree-view#854] opened 2016-05-30 13:07 UTC
I'm a heavy user of the “multiple projects in `tree-view`” feature, but I'm missing the ability to also add individual files.

In a big project, I often have multiple repositories open at the same time – and they usually share some configuration files in their parent directory. I'd like to be able to “add to project” a single file.

Adding the entire parent directory is cumbersome, as that contains the child repositories and a bunch of uninteresting files and folders.

<img width="200" alt="screen shot 2016-05-30 at 15 05 33" src="https://cloud.githubusercontent.com/assets/2833514/15650329/0406c61c-2678-11e6-9b77-955bebe507cf.png">

Imagine in the above example (where all repositories are collapsed), below them, the files, eg. `.env` or `data.json`, both of which are used by the three repositories.

**Comment by BugZappr** [comment] 2016-10-21 03:18
This is said to be a duplicate of my issue; so I'd just mention here that my idea, as implied here, to say it in so many words, is that there be a project manager which does NOT pick up everything in some given directory, nor simply ignore things based on a certain pattern, but starts empty, and contains only what you add.  This is, after all, the way Git and Hg repositories work.

In one of my duplicates, but not mentioned here, I also suggest that it would be pretty handy to pick up a list of files for a project from Git or Hg.  This seems to be impossible with the project managers as we now have them; because repositories may not track some files; but these project managers, as far as I've been able to tell so far, only exclude files from a project if you add a specific pattern to ignore them.

**Closed** 2019-10-28 11:26 UTC
Labels: feedback
