### ISSUE TITLE
tree view highlighting files with accent characters in filename even if they are unchanged

### ISSUE THREAD

**Issue by johnmahoney** [atom/tree-view#663] opened 2015-12-01 15:23 UTC
In my tree view, I'm seeing orange highlights for folders containing binary files with accent characters in their filenames. The image files with accents in filenames show up green themselves, as if they haven't been added to a git repository yet. But they have already been committed to my repo and are unchanged. 

![image](https://cloud.githubusercontent.com/assets/4676206/11504898/986453fc-9815-11e5-80a5-cf62893e86e8.png)

![image](https://cloud.githubusercontent.com/assets/4676206/11504938/c60d1c1c-9815-11e5-9d8d-c5b190e984bc.png)

**Comment by jasonsperske** [comment] 2016-10-17 17:33
I am also having this issue, here is a public repo that triggers this issue: https://github.com/jasonsperske/game-db

**Comment by 50Wliu** [comment] 2016-10-20 16:55
This is a duplicate of atom/atom#1890 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-20 16:55 UTC
