### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Lartza** [atom/tree-view#863] opened 2016-06-07 08:20 UTC
Just opening Atom, since some time ago (at least in 1.7.4, probably before too) has resulted in the tree-view package failing to activate.
Someone mentioned this happening for them on Arch too here #675 and I am using the prebuilt tensor5 packages with electron version 1.2.1

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Failed to activate the tree-view package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Object.shouldAttach (/usr/lib/atom/node_modules/tree-view/lib/main.js:114:23)
    at Object.activate (/usr/lib/atom/node_modules/tree-view/lib/main.js:16:16)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
    at /usr/lib/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
    at /usr/lib/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:530:21)
    at /usr/lib/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib/atom/src/package-manager.js:489:46)
    at /usr/lib/atom/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "automaticallyUpdate": false,
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.13
minimap, v4.24.3
minimap-autohide, v0.10.1

# Dev
No dev packages
```

**Comment by tensor5** [comment] 2016-06-07 08:44
This problem happens when using Atom with the Electron 1.2, which is based on Node 6. After [this commit](https://github.com/nodejs/node/commit/08085c49b6e49ecfffd638c6cd46f4de639ae4f4), `path.basename()` only accept strings as input.

Steps to reproduce:

```
$ rm ~/.atom/storage/application.json
$ atom
```

Solution:

https://github.com/atom/tree-view/blob/e93c939bec8aad681df77f308479cb57a314aa0c/lib/main.coffee#L54 should not allowed to be `undefined`. When `undefined` it should be `'.'` instead. I can open a pull request if needed.

**Comment by alex94puchades** [comment] 2016-06-07 14:18
Same issue is present also in Fedora 24, [mosquito/atom](https://copr.fedorainfracloud.org/coprs/mosquito/atom/) copr

**Comment by lee-dohm** [comment] 2016-06-07 16:51
If this is caused by building Atom in an unsupported way, like on top of a version of Electron that we don't package for Atom yet, then I'm going to have to close this as `wontfix`. Please let me know if this is the case.

**Comment by lee-dohm** [comment] 2016-06-11 19:51
So far we've seen this only in versions of Atom that have been built with unsupported versions of Electron, such as the mostquito/atom copr. If you can reproduce this error in a supported build of Atom, please supply repro steps along with the output of `atom --version` and we'll reopen the Issue.

**Closed by lee-dohm** 2016-06-11 19:51 UTC
Labels: more-information-needed

**Comment by alex94puchades** [comment] 2016-06-12 11:48
So that you know, as of v1.8.0 this issue is no longer present in the mosquito/atom copr

**Comment by Yajo** [comment] 2016-06-13 14:48
Actually I just got hit by this with mosquito/atom when opening config folder from the settings tab. @1dot75cm

**Comment by tensor5** [comment] 2016-06-14 01:36
@Yajo  Is mosquito/atom using [this patch](https://github.com/atom/tree-view/pull/864)?

**Comment by IamAdamJowett** [comment] 2016-06-14 02:38
I am now getting this same error on Windows 10, Atom v1.8.0, cannot manually install and activate (for some reason the tree view disappeared this morning)

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.208.0


### Stack Trace

Failed to activate the tree-view package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Adam/.atom/packages/tree-view/lib/main.coffee:1:25)
    at Object.<anonymous> (file:///C:/Users/Adam/.atom/packages/tree-view/lib/main.coffee:1:1)
    at Module._compile (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:342:19
    at C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:328:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\Adam\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".unison",
      "CVS",
      ".AppleDouble",
      ".LSOverride",
      ".Spotlight-V100",
      ".Trashes",
      "desktop.ini",
      "*.lock",
      "*.sock",
      "*.pid",
      "*.sw?",
      ".unison*",
      "*~"
    ],
    "projectHome": "C:\\Users\\Adam\\dev",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.22.0
angularjs, v0.3.4
autocomplete-modules, v1.5.1
autocomplete-php, v0.3.7
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.14
jshint, v1.8.5
language-asp, v1.0.0
linter, v1.11.10
linter-csslint, v1.3.2
linter-jsonlint, v1.2.5
linter-less, v2.5.0
linter-php, v1.2.0
merge-conflicts, v1.4.4
minimap, v4.24.4
package-sync, v1.1.0
pigments, v0.29.2
project-manager, v2.9.7
sync-settings, v0.7.2
tabasco, v0.5.0
terminal-panel, v1.14.1
tool-bar, v0.4.0
tree-view, v0.208.0
tree-view-git-status, v1.0.0

# Dev
No dev packages
```

**Comment by Yajo** [comment] 2016-06-14 07:17
@tensor5 All I know is it's Atom 1.8.0. Not sure what patches it has. Its info is in https://copr.fedorainfracloud.org/coprs/mosquito/atom/.

@1dot75cm can help more here.

**Comment by nerdofsteel** [comment] 2016-07-18 03:45
I get this error on a brand new install of Atom v1.8.0 on Ubuntu 16.04 with no plugins installed.

**Comment by juba** [comment] 2016-07-18 09:29
@nerdofsteel Reinstall Atom following the instructions here : https://github.com/atom/atom/issues/12182

This fixed the problem for me on Ubuntu 16.04.

**Comment by djfm** [comment] 2016-07-18 18:02
@juba Same issue, fix worked for me too. That's a bit strange. Apparently installing atom 1.8 with dpkg when atom 1.8 is already installed messes things up :)

**Comment by Yajo** [comment] 2016-07-20 05:43
I finally got it working: https://github.com/atom/settings-view/issues/766#issuecomment-233382832
