### ISSUE TITLE
Slow loading single file in large folder

### ISSUE THREAD

**Issue by elneilios** [atom/tree-view#442] opened 2015-05-08 13:17 UTC
I'm new to Atom and would like to use it as my main text editor. However it becomes unusable if I try and open a single text file in a folder that contains many files (in my case the folder contains approx 4000 files). 

I think the problem stems from tree-view trying to load every single file in the parent folder as well as the one I am interested in. If I disable the tree-view package then my file loads instantly. I'd rather not have to disable the package as it is useful in other scenarios. 

I would have thought Atom would differentiate between loading a single file and the entire folder somehow? For example, I usually open the file via the Windows Explorer context menu. In that case I wouldn't expect the entire folder to be loaded, just the file. However if i right-click a folder in Windows Explorer then it would make sense for tree-view to load up the entire folder.

**Comment by izuzak** [comment] 2015-05-08 13:27
Thanks for the report, @elneilios -- this sounds like a duplicate of https://github.com/atom/atom/issues/1847, so I'm closing this in favor of that issue. Let me know if I misunderstood, though. :v:

**Closed by izuzak** 2015-05-08 13:27 UTC
