### ISSUE TITLE
Suggestion: Similar setting to code editor, ability to scroll past end of tree view

### ISSUE THREAD

**Issue by jack-newman** [atom/tree-view#1001] opened 2016-12-13 09:59 UTC
Similar setting to code editor, ability to scroll past end of tree view.

**Comment by Ben3eeE** [comment] 2016-12-13 10:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/811. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-13 10:11 UTC
