### ISSUE TITLE
Folders lost when using Open with Atom

### ISSUE THREAD

**Issue by marcong95** [atom/tree-view#788] opened 2016-03-27 09:14 UTC
Hi. When Atom is closed and I right-click a file and choose ```Open with Atom```, all folders in the tree-view will be replaced. How can I avoid this replacement?
Thanks,
Marco

**Comment by Zireael07** [comment] 2016-03-27 12:46
You can't for now. See atom/atom for explanations why, search for "launch story confusing"

**Comment by 50Wliu** [comment] 2016-03-28 12:59
Closing as a duplicate of atom/atom#10183 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-28 12:59 UTC
