### ISSUE TITLE
Does not open files in tree view when there is no dir in tree-view

### ISSUE THREAD

**Issue by rugk** [atom/tree-view#605] opened 2015-10-16 21:06 UTC
When I only open a few files (so no complete dir or repo) they show up the in the tree view. However the tree view displays them as directories and I cannot open them.
That's best to reproduce when you drag and drop these files into Atom.

Here is an example (executed in safe-mode):
![treeviewissue](https://cloud.githubusercontent.com/assets/11966684/10553357/4168c21a-745a-11e5-9ed2-f034d30ed2a5.gif)

Atom 1.0.19
Windows 7

**Comment by lee-dohm** [comment] 2015-10-17 02:44
How are you getting Atom into the state where there is no root directory?

**Comment by Tyriar** [comment] 2015-10-17 04:06
This looks like a duplicate of https://github.com/atom/tree-view/issues/471

**Comment by rugk** [comment] 2015-10-17 16:57
> How are you getting Atom into the state where there is no root directory?

Just open a new "New window" (at "file") and drag and drop the files in it. (You may close the automatically created untitled file before)

> This looks like a duplicate of #471

Yes, looks similar. You may close this issue if you like.

**Closed** 2015-10-17 16:57 UTC
Labels: needs-reproduction
