### ISSUE TITLE
Tree view won't open until a file is loaded

### ISSUE THREAD

**Issue by rjattrill** [atom/tree-view#268] opened 2014-12-04 22:25 UTC
Open a new session with no files open.

Press Ctrl+\ (or equivalent).

Tree view does not show.

Open a file via the File Menu.

Ctrl+\ now shows the tree view as expected.   If Ctrl+\ has already been pressed, the tree view shows automatically.

Version 0.150.0 on Windows 7

**Comment by apshoemaker** [comment] 2015-01-15 14:45
Eh - seems like a bug to me.  If I open a file, tree-view opens fine.  If I close that file (cmd+w) and am back to the untitled file, tree-view now opens and closes per normal.

Mac os x yosemite
atom 0.172.0
latest tree view from apm

**Comment by apshoemaker** [comment] 2015-01-15 14:57
Ok, maybe not a bug - just a doc issue.  I dug into the code and found this - 
https://github.com/atom/tree-view/blob/master/lib/tree-view.coffee:230

It's calling atom.project.getPaths which assumes a project in order to set root (https://atom.io/docs/api/v0.172.0/Atom#instance-getPaths).  

I'm new to atom (as in just started using it about 15 minutes ago - vim guy for the last 10 years), so I have a bit to learn about projects, apparently :-)

**Comment by apshoemaker** [comment] 2015-01-15 15:13
Ok - just to put this to bed :-)

If you open atom from cli in the directory that your project is located in, it places that directory into the project context - as a result, your tree-view reacts as you would expect.

https://atom.io/docs/v0.172.0/getting-started - Working With Files

**Comment by izuzak** [comment] 2015-03-04 20:26
I think this is a duplicate of a much older issue, so I'm closing this in favor of that one: https://github.com/atom/tree-view/issues/268. Thanks for the feedback, everyone -- please subscribe to the other issue for updates.

**Comment by izuzak** [comment] 2015-03-04 20:27
Aaand I used the wrong link, correct one: https://github.com/atom/tree-view/issues/68

**Closed by izuzak** 2015-03-04 20:26 UTC
Labels: enhancement
