### ISSUE TITLE
Failed to activate the tree-view package

### ISSUE THREAD

**Issue by vinyfc93** [atom/tree-view#865] opened 2016-06-09 16:41 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: linux 4.5.6-200.fc23.x86_64
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Failed to activate the tree-view package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at Object.shouldAttach (/usr/lib64/atom/node_modules/tree-view/lib/main.js:114:23)
    at Object.activate (/usr/lib64/atom/node_modules/tree-view/lib/main.js:16:16)
    at Package.module.exports.Package.activateNow (/usr/lib64/atom/src/package.js:183:20)
    at /usr/lib64/atom/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/lib64/atom/src/package.js:92:15)
    at /usr/lib64/atom/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/lib64/atom/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/src/package-manager.js:530:21)
    at /usr/lib64/atom/src/package-manager.js:511:29
    at Config.module.exports.Config.transactAsync (/usr/lib64/atom/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib64/atom/src/package-manager.js:506:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/lib64/atom/src/package-manager.js:489:46)
    at /usr/lib64/atom/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-06-09 20:09
This is a duplicate of #863 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-09 20:09 UTC
