### ISSUE TITLE
Vertical scrollbar instead of horizontal in Rename/Move/Duplicate dialog

### ISSUE THREAD

**Issue by dmongeau** [atom/tree-view#506] opened 2015-07-06 15:26 UTC
For some reason the Rename/Move/Duplicate dialog is working with a vertical scrollbar instead of an horizontal. I have resetted my config and still have this issue. Is it normal? Any idea? Because it's kind of annoying when I use the keyboard to navigate in the path, it doesn't scroll vertically and it took me sometimes to realize that the rest of path was under.

![scroll](https://cloud.githubusercontent.com/assets/124966/8525922/87ed5c70-23d1-11e5-8de8-01b7dd6bb19e.gif)

**Comment by dmongeau** [comment] 2015-07-06 15:29
Okay, I have disabled "SoftWrap" and it works as expected now. Not sure if it's a good thing to soft wrap a path in this dialog because if you use the keyboard without noticing the vertical scrollbar it looks like a bug.

**Comment by 50Wliu** [comment] 2015-07-07 00:38
Hey @dmongeau, this seems like a duplicate of #473 - could you please subscribe there for updates instead?  Thanks.

**Closed by 50Wliu** 2015-07-07 00:38 UTC
