### ISSUE TITLE
bug w/ how .gitignore files are processed with tree-view? does not accommodate for .gitignore excludes correctly?

### ISSUE THREAD

**Issue by skalfyfan** [atom/tree-view#432] opened 2015-04-27 15:30 UTC
Have started playing with the Atom editor and have noticed a problem in how the tree-view reads and processes .gitignore files when using exclusion. 

On some projects I setup my .gitignore files to initially ignore *everything*. I then selectively choose specific paths that should actually **not** be ignored and should be included. An example of this is a Wordpress build where the only things I want under source control are the *wp-contents/plugins* and the *wp-contents/themes* folders.

So my .gitignore file would look something like this where we ignore _everything_ in the wp-content folder except the plugins, and themes subfolders:

    # initially ignore everything in our root except for the "wp-content" directory
    /*
    !wp-content/

    # ignore everything in the "wp-content" directory, except:
    # "plugins" directory
    # "themes" directory
    wp-content/*
    !wp-content/plugins/
    !wp-content/themes/

The problem is that in Atom editor both the wp-content/plugins and wp-content/themes folders are marked with the *status-ignored* css selector, so they are incorrectly grayed out? If my local repo is up to date, both these folders are grayed out as if they are being *ignored*, even though in my .gitignore file I have set them up to be included (through exclusion).

The Atom tree-view appears to assume my entire project is ignored and does not correctly processes the .gitignore exclude calls.

Anyone else notice this?

**Comment by izuzak** [comment] 2015-04-27 15:33
@skalfyfan Thanks for the detailed report. :bow: This looks like a duplicate of https://github.com/atom/tree-view/issues/196. I'm going to close this, but let me know if I'm mistaken.

**Closed by izuzak** 2015-04-27 15:33 UTC
