### ISSUE TITLE
Ignored files and Collapse directories

### ISSUE THREAD

**Issue by MartinTrubelik** [atom/tree-view#1231] opened 2018-03-06 11:10 UTC
Hi,
I have a problem with the Collapse directories option ✔️. It doesn't work because of ignored files (in my case .DS_Store - it is hidden in the tree-view 👻) when I remove them everything works fine.
Ignored files are not ignored by the Collapse directories.

🙏 Please help 😭

**Comment by rsese** [comment] 2018-03-06 17:48
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/tree-view/issues/726 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-03-06 17:48 UTC
