### ISSUE TITLE
Support for inverse ignored git paths

### ISSUE THREAD

**Issue by kylehotchkiss** [atom/tree-view#329] opened 2015-01-16 16:13 UTC
In my gitignore I have something like this:

    wp-content/themes/*
    !wp-content/themes/theme/

Currently, tree view marks the `wp-content/themes/theme/` folder as being ignored by git, which makes sense, but is it possible it could also parse the `!` operator in the future?

**Comment by kevinsawicki** [comment] 2015-01-16 17:36
This looks like a duplicate of https://github.com/atom/tree-view/issues/196

**Closed by kevinsawicki** 2015-01-16 17:36 UTC
