### ISSUE TITLE
tree-view not showing git status / looses status

### ISSUE THREAD

**Issue by pabloab** [atom/tree-view#907] opened 2016-08-04 19:52 UTC
On Windows 8.1:

1. Run C:\Users\pbianchi\AppData\Local\atom\app-1.9.2\atom.exe --safe
1. Open the project showing modified files on tree view.
1. Focus on other application (alt+tab) and come back to Atom.

**Expected**: Still showing files modified in yellow on the tree view.
**What happen**: Everything gray as when commited.

This start happening when installed v1.9.2, I don't remember what version i had before (that was working). Opening the file show correctly at the left of the number the changed lines. Close and open Atom again fix the problem.. until you do alt+tab..

**Comment by 50Wliu** [comment] 2016-08-04 20:45
This is a duplicate of #906 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-04 20:45 UTC
