### ISSUE TITLE
feature: ctrl-drag files in tree view to copy

### ISSUE THREAD

**Issue by varesa** [atom/tree-view#816] opened 2016-04-20 22:21 UTC
I think it is standard UX nowdays that dragging a file moves it and ctrl-dragging copies it. It would be great if Atom could do the same.

![](http://i.imgur.com/ASjpdJ0.gif)

**Comment by anderoonies** [comment] 2016-05-10 15:51
this looks like it could be tacked on pretty painlessly to #793

**Comment by Ben3eeE** [comment] 2016-05-31 05:53
Is this a duplicate of https://github.com/atom/tree-view/issues/703?

**Comment by 50Wliu** [comment] 2016-05-31 11:45
Thanks @Ben3eeE.

**Closed by 50Wliu** 2016-05-31 11:45 UTC
Labels: enhancement
