### ISSUE TITLE
Option to not grey-out VCS hidden directories / files.

### ISSUE THREAD

**Issue by davidbarratt** [atom/tree-view#780] opened 2016-03-20 22:19 UTC
Sometimes it can be really hard to read folders and filenames that are ignored in the VCS.

It would be really helpful to have an option to not grey them out, but show them the same as non-ignored path.

Or perhaps some other visual indicator that does not affect the legibility of the title.

**Comment by simurai** [comment] 2016-03-29 01:31
It depends a bit on the theme, but adding the example below to your `styles.less` should work.

```less
@import "ui-variables";

// style ignored tree-view files
.tree-view .status-ignored .list-item {
  color: @text-color !important;
}
```

Or you could also use a different color, like `color: red !important;`.

**Comment by garygreen** [comment] 2016-08-24 10:50
@simurai that works wonderfully. The only problem is the icons. I use setui icons and they are all missing on those files. It replaces the css with:

```css
atom-workspace .entries.list-tree .file.status-ignored .icon:before {
    content: '\E02B';
}
```

Makes it difficult to disable this without some javascript? Not even sure what events I would listen to in order to make it work...

**Comment by simurai** [comment] 2016-08-25 06:00
@garygreen For the `seti-icons` package, this should work:

```less
// style ignored tree-view files
.tree-view .status-ignored .list-item,
.tree-view .status-ignored .icon:before {
  color: @text-color !important;
}
```

**Comment by garygreen** [comment] 2016-08-25 07:52
Your original css worked - I'm talking about the actual icons and how to
get them back.

On 25 Aug 2016 07:00, "simurai" <notifications@github.com> wrote:

@garygreen <https://github.com/garygreen> For the seti-icons package, this
should work:

// style ignored tree-view files.tree-view .status-ignored
.list-item,.tree-view .status-ignored .icon:before {
  color: @text-color !important;
}

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/atom/tree-view/issues/780#issuecomment-242288521>, or mute
the thread

**Comment by simurai** [comment] 2016-08-25 08:42
Ohh.. you mean you don't see an icon at all? Like there is just an empty space where the icon should be?

Hmm.. I can't reproduce that, in my case I can see an "eye with a line". If I disable the `content: '\E02B';`, it falls back to the "text icon":

![icons](https://cloud.githubusercontent.com/assets/378023/17962314/2bcf5aa8-6aeb-11e6-94df-e308141dc1fc.gif)

**Comment by garygreen** [comment] 2016-08-25 09:54
Yes that's exactly it.. there's no easy way to disable the `content: '\E02B';` so it makes it difficult to re-enable the set-ui icons.

My use case is this -- I actually develop my PHP packages inside the 'vendor' directory directly. I don't commit my vendor directory, so it's VCS ignored. I still want it to be coloured and look pretty whilst I develop inside it. Developing directly inside the vendor directory is pretty common within the PHP community imo.

It would be nice to have a dedicated option to re-enable all the colours / icons for VCS ignored files and not make it theme dependant.

![set-ui vcs](https://cloud.githubusercontent.com/assets/1702638/17964652/274c16ee-6ab2-11e6-8910-7e5355ba6fbf.gif)

**Comment by simurai** [comment] 2016-08-25 13:57
I see.. ya, that's trickier. Does this work in your `init.coffee` file:

```coffee
# Remove status-ignored classes
@ignoredClasses = document.querySelectorAll('.tree-view .status-ignored')
for i in [0...@ignoredClasses.length]
  @ignoredClasses[i].classList.remove("status-ignored")
```

It just removes the `.status-ignored` classes so the selector isn't valid anymore. Not sure if that has some other side effects, tough. :see_no_evil:

**Comment by garygreen** [comment] 2016-08-25 15:13
@simurai cheers buddy, I did have a go with some javascript similar to that but couldn't work out how to listen for the treeview events when directories are opened etc to remove the class from the parent - your code does seem to do the trick when directories are open, but it doesn't work for ones that are collapsed.

**Comment by AndreaGriffiths11** [comment] 2017-02-10 00:35
Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). This seems to be resolved so we are going to close it. For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Closed by AndreaGriffiths11** 2017-02-10 00:35 UTC
