### ISSUE TITLE
Files with åäö in filename always marked as new (green)

### ISSUE THREAD

**Issue by baelter** [atom/tree-view#1061] opened 2017-04-04 13:13 UTC
### Description

Files with åäö in filename always marked as new (green)

### Steps to Reproduce

1. Create file with åäö in name
2. Commit

**Expected behavior:** Not marked green

**Actual behavior:** Marked green
**Reproduces how often:** 100%

### Versions
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
OSX 10.12.3

**Comment by 50Wliu** [comment] 2017-04-04 15:29
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#1890. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-04-04 15:29 UTC
