### ISSUE TITLE
Copy and Paste Files in the same folder don't take the real names of the files.

### ISSUE THREAD

**Issue by Otaru22** [atom/tree-view#737] opened 2016-02-15 17:17 UTC
When i try to copy and paste a file into the same folder, i get a file with a split name in the first dot that the name has.

---Steps for the bug---

1. Copy a File, for example "Articles.controller.class.php" (Right Click and Copy).
2. Paste in the same folder i get "Articles0.controller".

---Atom Version---
I have 1.4.3, but i got the bug sice Many Versions Ago.

---Other---
I Know that Exist "Duplicate" but sometimes I want to use Copy and Paste...

Sorry for My bad English.

![img1](https://cloud.githubusercontent.com/assets/13713107/13055562/2eaa62cc-d3e2-11e5-822f-b315fa7dc251.jpg)
![img2](https://cloud.githubusercontent.com/assets/13713107/13055563/2eaeee14-d3e2-11e5-98c1-1ef8f98d315b.jpg)

**Comment by 50Wliu** [comment] 2016-02-15 18:05
This is a duplicate of #397 - please subscribe there for updates.

**Closed by 50Wliu** 2016-02-15 18:05 UTC
