### ISSUE TITLE
disabled by default in 0.206 atom build

### ISSUE THREAD

**Issue by iamstarkov** [atom/tree-view#467] opened 2015-06-05 11:28 UTC
I updated atom, and after restart I have no tabs and tree-view. I found that these two package was disabled

**Comment by iamstarkov** [comment] 2015-06-05 11:29
Here is an issue for tabs atom/tabs#162

**Comment by iamstarkov** [comment] 2015-06-05 11:54
for some reason package was disabled

**Comment by lee-dohm** [comment] 2015-06-05 15:26
For anyone else running into this, this is caused by having had sublime-tabs installed at the time of the upgrade. The sublime-tabs package disables the tree-view and tabs packages but does not re-enable them when it is deactivated. Since the functionality that sublime-tabs provided is now available in Atom Core, the sublime-tabs package can be removed ... and tree-view and tabs will need to be manually enabled.

Closing this as duplicate of the atom/tabs#162 issue.

**Closed by lee-dohm** 2015-06-05 15:26 UTC
Labels: bug
