### ISSUE TITLE
Uncaught Error: EBUSY: When moving folder in tree view

### ISSUE THREAD

**Issue by loboolsson** [atom/tree-view#527] opened 2015-07-21 11:40 UTC
1. Try to use cut and paste to move folder in tree. None of the files where open in atom
2. On paste error is thrown

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.177.0

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, rename 'd:\code\work\tgw-app\src\common\footer' -> 'd:\code\work\tgw-app\src\feed\footer'

```
At fs.js:680

Error: EBUSY: resource busy or locked, rename 'd:\code\work\tgw-app\src\common\footer' -> 'd:\code\work\tgw-app\src\feed\footer'
    at Error (native)
    at Object.fs.renameSync (fs.js:680:18)
    at Object.fsPlus.moveSync (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:269:17)
    at TreeView.module.exports.TreeView.pasteEntries (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\tree-view\lib\tree-view.js:976:32)
    at space-pen-div.atom.commands.add.tree-view:paste (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\tree-view\lib\tree-view.js:277:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:156:19)
    at jQuery.fn.trigger (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\src\space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (C:\Users\lobo\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:75:67)
```

### Commands

```
     -8:34.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -8:34.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -8:33.8.0 core:paste (atom-text-editor.editor.is-focused)
     -8:27.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:02.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -6:00.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:59.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -5:57.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:57.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:55.4.0 project-find:show (atom-text-editor.editor.is-focused)
     -5:51.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:09.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:09.0 project-find:show (atom-text-editor.editor.is-focused)
     -2:08.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:04.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -0:38.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true
  }
}
```

### Installed Packages

```coffee
# User
jshint, v1.3.7
minimap, v4.9.4
project-manager, v1.15.10
space-tab, v0.4.1

# Dev
No dev packages
```

**Comment by izuzak** [comment] 2015-07-22 11:50
Thanks for the report. I think this is a duplicate of https://github.com/atom/tree-view/issues/419, which was fixed in https://github.com/atom/tree-view/pull/514. That fix will be available in the next release of Atom.

**Closed by izuzak** 2015-07-22 11:50 UTC
