### ISSUE TITLE
Unable to drag file from tree to pane or tab.

### ISSUE THREAD

**Issue by chiangs** [atom/tree-view#1031] opened 2017-02-05 01:07 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Previous to 1.3, I was able to drag and drop from the tree to the main window/pane/tab bar and add a new pane or add the file to the pane. Now, even in safe mode, I cannot open the file without right clicking on it and selecting split right or just double clicking on it. I even used to be able to open a new pane by dragging and dropping in the far side of the active pane, for example if a had an html file open and i drag and drop my css in a right split pane. all I had to do was drag the css from the tree and drop it in the far right.

I have tried many different file types, changing themes and window sizes, no difference.

### Steps to Reproduce

1. Open Atom in normal or safe mode
2. Have only tree open and no other tabs or file open yet
3. Try to drag a file to where a pane would be.
4. Open a file by double clicking on the tree.
5. Try to drag another file from the tree to the active pane.

**Expected behavior:** Drag and drop working

**Actual behavior:** nothing, no + icon or anything to indicate it will open if i drop it there.

**Reproduces how often:** 100%

### Versions

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Mac OS X: El Capital 10.11.6
Macbook Pro 2012

### Additional Information

@lee-dohm

**Comment by lee-dohm** [comment] 2017-02-06 19:29
@ungb Can you reproduce this, verify it is a regression and add it to the appropriate list?

**Comment by chiangs** [comment] 2017-02-07 02:42
sorry i did mean 1.13. i know for sure it worked in 1.9. if you look at this page:

http://www.webupd8.org/2016/08/atom-190-released-with-drag-and-drop.html

there is an animated gif that shows the user dragging the tab to a section of the pane to split and open a new pane. That is one of the features I am missing along with the same behavior but from tree.

**Comment by lee-dohm** [comment] 2017-02-07 03:52
@chiangs Drag and drop to open a new pane still works in v1.13.x, I just checked it:


![drag-and-drop-panes](https://cloud.githubusercontent.com/assets/1038121/22677216/c8ee6c0c-eca5-11e6-8e91-3772a364bc76.gif)

**Comment by chiangs** [comment] 2017-02-07 04:05
@lee-dohm , check out my .gif. 
It works when I have two tabs open and i drag one to a new pane, but I can't drag from tree to create a pane, i have to double click it. furthermore, i can't add the file by dragging. I'm on SETI theme, but functionality doesn't change when i switch back to a standard atom theme.
![feb-06-2017 21-02-25](https://cloud.githubusercontent.com/assets/10984593/22677461/f507cbda-ecaf-11e6-95c5-990d95d24060.gif)

**Comment by lee-dohm** [comment] 2017-02-07 04:10
> but I can't drag from tree to create a pane

I don't think this has ever been implemented. I went searching for a PR that added this feature and only found https://github.com/atom/tree-view/issues/638, requesting to add the feature. I suspect this is a duplicate of #638.

**Comment by chiangs** [comment] 2017-02-07 04:14
Ok well if you don't have some functionality that I don't have in terms of tree and panes, then maybe I'm remebering wrong.  Odd, I feel like I remember being able to do this because I was surprised when the functionality wasn't there suddenly. sorry for the confusion!

**Comment by lee-dohm** [comment] 2017-02-07 04:14
It's quite alright :grinning: You may want to subscribe to #638 for updates 👍

**Closed by lee-dohm** 2017-02-07 04:14 UTC
