### ISSUE TITLE
Clicking on file in tree view that isn't open sets focus on editor

### ISSUE THREAD

**Issue by adambuczynski** [atom/tree-view#749] opened 2016-02-25 04:00 UTC
When I click a file in tree view that isn't open yet, focus is shifted to the editor (file contents). This is problematic, as I relied on clicking on a file for the focus to stay on the tree view, so that I could hit `m` to rename the file.

I suspect this may have to do with the refactoring around files not being opened as temporary files anymore?

Atom version 1.6.0-beta5, OS X 10.11.2.

**Comment by lee-dohm** [comment] 2016-02-25 20:48
This is a duplicate of https://github.com/atom/tree-view/issues/199. Please see the comments and suggested packages there. Let us know if you have any questions!

**Comment by adambuczynski** [comment] 2016-02-25 20:56
@lee-dohm no, it is not a duplicate of that issue.

That issue wants to prevent the files from opening, I don't mind the files being opened, I just want the _focus_ to go to the editor. 

This didn't use to happen in Atom 1.4.x and 1.5.x and earlier, it only started in 1.6.x.

**Comment by lee-dohm** [comment] 2016-02-25 21:01
My mistake. Thanks for the correction :grinning:

As an aside, including [repro steps](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) can help clarify these differences.

**Comment by adambuczynski** [comment] 2016-02-25 21:03
No worries, sorry I thought it was clear. Let me specify:

1. Open a project, close all file tabs
2. Single click on a file in the tree view
3. Press `m` to rename the file

Expected: the file rename dialog pops up

Actual: you type the letter `m` in the opened file on top, because after clicking the file focus is shifted to the editor window.

**Comment by adambuczynski** [comment] 2016-03-04 01:07
@lee-dohm have you had some time to look into this by any chance? It's impairing my productivity a lot, as I keep hitting `m` and having to erase the character and make sure I click the file name twice (not double click) before I rename it.

**Comment by billyjanitsch** [comment] 2016-03-20 21:39
Based on https://github.com/atom/tree-view/issues/740#issuecomment-185518512 it looks like this is actually intended behavior (introduced in e93148d5ec981ae69df788a3ab9dab6dcd389c0e, see also #742 and #682). The rationale seems to be "you can click on a file and immediately start editing it". However, I agree with @adambuczynski that this is undesirable.

The old behavior (single click to gain focus/preview, double click to open and transfer focus to the editor) aligns with Windows/OSX file explorers, most email clients, Dropbox/Drive, Sublime, etc. It's strange for Atom to diverge from such a common UX standard.

Even ignoring consistency, it seems counterintuitive that if I click on an item in a list, the list immediately loses focus, preventing me from doing anything with it (e.g. renaming/deleting/duplicating, navigating the list with arrow keys). It also introduces an awkward inconsistency in the behavior between clicking on files (editor gains focus) and folders (tree view retains focus).

@kuychaco, perhaps you could shed some light on this?

**Comment by monsterkodi** [comment] 2016-03-21 10:30
"The tree-view losing focus on click is actually the intended behavior." Really?
I agree the above, the usability of the tree-view is completely broken by this "feature".

**Comment by BinaryMuse** [comment] 2016-03-21 16:38
Thanks for bringing up this issue again, all. @kuychaco and I chatted about this last night and would love to explore some options.

To set context, the current behavior is predicated on the assumption that the thing you *probably* want to do with a file after opening it is edit its contents. With the changes to pending pane items that landed in Atom 1.6, both single-clicking and double-clicking a file in the tree view opens the file for editing, but now in different states (i.e. pending vs. permanent). However, it's obvious here that the goal of clicking on a file is not always to edit it, but sometimes to manipulate it in other ways. We'd like to support the best of both worlds if we can.

Here are a few things we brainstormed; we're not super set on any of them, and some of them may be terrible ideas. :P We're also open to other suggestions.

1. Retain the old behavior (single-click to open a file and retain tree view focus, double-click to open a file and focus the editor) if pending pane items is disabled (via `core:allowPendingPaneItems`). I'm particularly curious if people who would prefer the old single-click behavior of keeping focus in the tree view even use/care about pending pane items. This would be trivial to implement.
2. Change single- or double-clicking on a tree view file to dispatch an action instead of directly calling `Workspace::open` (e.g. `tree-view:open-selected-file` and `tree-view:open-selected-file-alternate`). Then a small snippet of code inside `init.coffee` would allow folks to re-focus the tree view easily after the single-click action has been dispatched. This provides additional flexibility as people could overwrite a lot of behavior by hooking into the command dispatch, but requires people to edit their init script to get the old behavior, and is pretty complicated overall.
3. Add an option for tree view along the lines of "Focus editor upon opening a file." However, as mentioned, there are now two states a pane item can be in after opening, triggered differently by single- or double-clicking, so I'm not sure if we'd need additional options there. Perhaps something like "Focus editor upon opening a file in a pending state"? (This could go hand-in-hand with option 1.)

For simplicity and flexibility, I'm personally favoring the "Focus editor upon opening a file in a pending state" option along reverting to the old behavior if pending tabs is completely disabled; in short, it means that single-clicking would always retain tree veiw focus and double-clicking would always focus the editor, no matter whether pending items are enabled or not. Then, if and only if pending items *are* enabled *and* the new option is checked, single-clicking a file will focus the editor (the current 1.6 behavior):

* With pending tab items *enabled*:
  * Single-clicking a tree view entry opens the file in pending mode
    * With the new option *enabled*, the editor is focused
    * With the new option *disabled*, the tree view is focused
  * Double-clicking a tree view entry opens the file in permanent mode
    * The editor is always focused
* With pending tab items *disabled*:
  * Single-clicking a tree view entry opens the file in permanent mode
    * The tree view is always focused
  * Double-clicking a tree view entry opens the file in permanent mode
    * The editor is always focused

Thoughts?

**Comment by monsterkodi** [comment] 2016-03-21 16:50
> On 21 Mar 2016, at 17:38, Michelle Tilley <notifications@github.com> wrote:
> 
> Thanks for bringing up this issue again, all. @kuychaco <https://github.com/kuychaco> and I chatted about this last night and would love to explore some options.
> 
> To set context, the current behavior is predicated on the assumption that the thing you probably want to do with a file after opening it is edit its contents. With the changes to pending pane items that landed in Atom 1.6, both single-clicking and double-clicking a file in the tree view opens the file for editing, but now in different states (i.e. pending vs. permanent). However, it's obvious here that the goal of clicking on a file is not always to edit it, but sometimes to manipulate it in other ways. We'd like to support the best of both worlds if we can.
> 
> Here are a few things we brainstormed; we're not super set on any of them, and some of them may be terrible ideas. :P We're also open to other suggestions.
> 
> Retain the old behavior (single-click to open a file and retain tree view focus, double-click to open a file and focus the editor) if pending pane items is disabled (via core:allowPendingPaneItems). I'm particularly curious if people who would prefer the old single-click behavior of keeping focus in the tree view even use/care about pending pane items. This would be trivial to implement.
> Change single- or double-clicking on a tree view file to dispatch an action instead of directly calling Workspace::open (e.g. tree-view:open-selected-file and tree-view:open-selected-file-alternate). Then a small snippet of code inside init.coffee would allow folks to re-focus the tree view easily after the single-click action has been dispatched. This provides additional flexibility as people could overwrite a lot of behavior by hooking into the command dispatch, but requires people to edit their init script to get the old behavior, and is pretty complicated overall.
> Add an option for tree view along the lines of "Focus editor upon opening a file." However, as mentioned, there are now two states a pane item can be in after opening, triggered differently by single- or double-clicking, so I'm not sure if we'd need additional options there. Perhaps something like "Focus editor upon opening a file in a pending state"? (This could go hand-in-hand with option 1.)
> For simplicity and flexibility, I'm personally favoring the "Focus editor upon opening a file in a pending state" option along reverting to the old behavior if pending tabs is completely disabled; in short, it means that single-clicking would always retain tree veiw focus and double-clicking would always focus the editor, no matter whether pending items are enabled or not. Then, if and only if pending items are enabled and the new option is checked, single-clicking a file will focus the editor (the current 1.6 behavior):
> 
> With pending tab items enabled:
> Single-clicking a tree view entry opens the file in pending mode
> With the new option enabled, the editor is focused
> With the new option disabled, the tree view is focused
> Double-clicking a tree view entry opens the file in permanent mode
> The editor is always focused
> With pending tab items disabled:
> Single-clicking a tree view entry opens the file in permanent mode
> The tree view is always focused
> Double-clicking a tree view entry opens the file in permanent mode
> The editor is always focused
> Thoughts?
> 

This sounds like a good solution to me. It should make everybody happy :)

**Comment by billyjanitsch** [comment] 2016-03-21 20:25
@BinaryMuse thanks for the detailed follow up. :blush: 

> To set context, the current behavior is predicated on the assumption that the thing you probably want to do with a file after opening it is edit its contents.

I think this assumption is correct, but you're further assuming that users conceptualize single-clicking a file in a list as *opening* it rather than *selecting* it, which I think is generally false (again, think of how file explorers, email clients, etc. typically behave).

> Add an option for tree view along the lines of "Focus editor upon opening a file."

That sounds great -- though I'd suggest that it be disabled by default. (The Windows file explorer has a similar option to open files on single-click, also disabled by default.)

**Comment by adambuczynski** [comment] 2016-03-21 23:58
I'm of the opinion that if you want to edit a file, you are already going
to double click it, so when single clicking it's either to preview a file
or to perform a tree view action on it.

Following that logic, it doesn't make sense to me to focus the editor in
those cases.

So my preferred solution would be option 1, and simply to revert to how it
was. There is already a multitude of ways to focus the editor on a file,
double clicking in tree view, using the fuzzy finder, opening a file
externally, etc. So I don't see an urgent need to make effort to add a
fourth way, even if it's configurable. But if it doesn't take too much
effort and if it would make some users happy to have single click focus the
editor, then option 1+3 would be ok.

Has anyone ever asked for this feature at all?

**Comment by billyjanitsch** [comment] 2016-03-22 00:32
@adambuczynski I think you misread option 1 -- it only reverts to the previous behavior iff the global pending pane option is disabled.

**Comment by adambuczynski** [comment] 2016-03-22 01:30
Sorry, in that case having it fully configurable (or otherwise to be able
to emulate the old behaviour) would be my preferred choice.

**Comment by kankaristo** [comment] 2016-03-23 22:14
> I think this assumption is correct, but you're further assuming that users conceptualize single-clicking a file in a list as opening it rather than selecting it, which I think is generally false (again, think of how file explorers, email clients, other text editors, etc. typically behave).

+1, Atom is *really* weird in this regard. In pretty much every other desktop application, single-clicking a file only selects it, double-clicking opens it. The behavior users are used to seeing in other applications should at least be a configurable option, if not the default.

I don't mean to hijack the issue (https://github.com/atom/tree-view/issues/199 is already closed, because a community package exists as a work-around), but if changes are being made regarding single-clicking in tree-view, please consider this as well.

**Comment by billyjanitsch** [comment] 2016-04-03 20:11
@BinaryMuse until the Atom team has more time to sort out a more nuanced solution, would you accept a PR that simply reverts the behavioral change?

**Comment by adambuczynski** [comment] 2016-04-03 20:32
I'd be in favour of that :+1:

**Comment by BinaryMuse** [comment] 2016-04-04 16:46
@billyjanitsch Thank you, but I'm loathe to simply change the default behavior again. I'm discussing things with a few folks and will be looking at this this coming week.

**Comment by kuychaco** [comment] 2016-04-08 05:20
This will be resolved next week. Stay tuned!

**Comment by adambuczynski** [comment] 2016-04-08 08:31
@kuychaco great, thank you

**Closed** 2016-04-12 03:44 UTC
Labels: atom, feedback

**Comment by adambuczynski** [comment] 2016-04-20 03:14
I can confirm that it's working properly now in Atom 1.9.0

**Comment by peoronoob** [comment] 2016-07-31 21:51
I'm against this feature.

In most cases (like more than 99% of the times) I want to open a file and use it straight ahead.

For the few times that I want interact with the treeview right clicking is better for me.

Is there any way to revert this feature or to turn it into an option?

**Comment by adambuczynski** [comment] 2016-07-31 21:55
I would definitely argue against outright reverting, as my workflow does use the tree view + keyboard shortcuts extensively and it would make it harder to work like that. But if it can be turned into an option so as to accommodate other preferences that would be great.

**Comment by nsiniakevich** [comment] 2016-08-16 08:38
Is there a way to do the same thing, but using keyboard shortcut instead of single click?
In example in Intellij Idea I can use just `arrow keys` and `enter` to observe project files, focus is always stay on the tree view.

**Comment by sethvoltz** [comment] 2016-09-12 21:41
An option would be very helpful. I'm trying to switch from Sublime and this is a big sticky piece for me. Understanding that there are two major workflows: click to open file and click to select file, it seems reasonable for there to be an option to specify which one is used.
