### ISSUE TITLE
Only open files with double click [temporary tabs]

### ISSUE THREAD

**Issue by Stanzilla** [atom/tree-view#444] opened 2015-05-10 19:56 UTC
So everyone know this problem, you are skimming through your project files because you forgot where the piece of code that you are looking for actually is, so you click file after file in the tree-view and when you finally end up finding what you looked for, you have like 200 tabs open in Atom. Now have fun closing all of them when you can't use the "close everything to the right" and similiar functions because you have some other tabs open that you really need.

Sublime does this really cool thing where tabs open only temporary, so you can look through the file's content and they close again after you click a different file. The indication that this tab is only temporary is that the tab name is italic. When you actually found the file that you are looking for, you can double click the file name and it will become a permanent tab.

As a person that can't remember things for longer than 10s and that is constantly looking through files, I'd really love this feature get implemented in Atom, too.

**Comment by lee-dohm** [comment] 2015-05-10 20:00
Duplicate of #3. Please subscribe there for updates.

**Closed by lee-dohm** 2015-05-10 20:00 UTC
