### ISSUE TITLE
Tree-view colors don't change for staged

### ISSUE THREAD

**Issue by pbiggar** [atom/tree-view#908] opened 2016-08-05 00:48 UTC
In tree-view, a modified file/directory will show up identically regardless of whether it is modified in the working directory, or in the index. That is, the file will appear orange in both cases.

This is quite different from the expectation I have from git. In the git cli, modified files show as a red Ms, and modified-but-in-the-index show as green Ms.

I believe a modified-but-in-the-index file should be green in tree-view, instead.

I propose the following change:
- files which have a red M in the git cli should be orange in tree-view
- files which have a green M in the git cli should be green in tree-view

I believe this should be straightforward to do for just modified files (see references below), and I volunteer to do it. Would this change be accepted?

Reference:
- the statuses are [here in libgit2] (https://github.com/libgit2/libgit2/blob/HEAD/include/git2/status.h#L32-50)
- the status are [here in git-utils](https://github.com/atom/git-utils/blob/master/src/git.coffee)
- the statuses are converted into CSS classes in [file.coffee](https://github.com/atom/tree-view/blob/master/lib/file.coffee#L54) and in [file-view.coffee](https://github.com/atom/tree-view/blob/master/lib/file-view.coffee#L29)

Proposed implementation:
- split status-modified into more statuses: probably status-staged-modified and status-modified
- status-modified-staged would be green, not orange.
- if it has both status-staged-modified and status-modified (eg `MM` in the git cli), we would use a different indicator, maybe a gradient between orange and green.

**Comment by mnquintana** [comment] 2016-08-05 00:54
This looks like a duplicate of https://github.com/atom/tree-view/issues/430 – closing this out in favor of that issue. Feel free to leave this as a comment there though!

**Closed by mnquintana** 2016-08-05 00:54 UTC
