### ISSUE TITLE
In auto-reveal focus tree view instead my file at tab change.

### ISSUE THREAD

**Issue by grodrigo** [atom/tree-view#973] opened 2016-11-03 22:21 UTC
When I set auto-reveal, if I change the tab file focus, atom focuses in my tree-view instead in editing my file (default without setting auto-reveal)
Isn't bad at an option to select what happen when I change the tab focus, if I want to focus in my tab or in the tree view, but at now it change the approach without asking me.
tree-view 0.203.2

**Comment by Ben3eeE** [comment] 2016-11-04 06:58
This is a duplicate of https://github.com/atom/tree-view/issues/858. Feel free to subscribe there for updates. As a temporary workaround you can disable the `Focus On Reveal` configuration option in the `tree-view` package settings.

**Closed by Ben3eeE** 2016-11-04 06:58 UTC
