### ISSUE TITLE
"Show On Right Side" Button doesn't changed the view side.

### ISSUE THREAD

**Issue by buchansm** [atom/tree-view#1099] opened 2017-05-17 13:34 UTC
When I go into the Tree View settings the "Show On Right Side" is checked but the view side is on the left. When I uncheck the button it does nothing.

**Comment by Zireael07** [comment] 2017-05-17 13:48
Duplicate of #1084. See the gif in comments for solution.

**Closed** 2017-05-17 13:51 UTC
