### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by jappre** [atom/tree-view#308] opened 2015-01-06 06:17 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At /Applications/Atom.app/Contents/Resources/app/src/project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:462:15)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:439:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app/src/project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:383:18)
  at tree-view-file.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
  2x -0:00.0 core:copy (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "html2jade",
      "linter",
      "script",
      "autocomplete",
      "tabs-to-spaces"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
atom-color-highlight, v3.0.1
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
command-logger, v0.20.0
editor-stats, v0.16.0
git-log, v0.2.0
git-tab-status, v1.3.0
go-plus, v3.0.11
language-haskell, v1.0.0
language-jade, v0.3.0
language-stylus, v0.1.0
language-swift, v0.3.0
minimap, v3.4.9
project-manager, v1.14.1

# Dev
No dev packages
```

/cc @atom/core

Just don`t show the error dialog, give us a tip.

**Comment by lee-dohm** [comment] 2015-01-06 07:01
Duplicate of atom/atom#4421 and atom/atom#307.

**Closed by lee-dohm** 2015-01-06 07:01 UTC
