### ISSUE TITLE
Atom does not update when doing git init after opening

### ISSUE THREAD

**Issue by OmgImAlexis** [atom/tree-view#1040] opened 2017-03-04 03:23 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If I open Atom before doing `git init` the treeview doesn't update it's highlighting, etc. until I close and reopen Atom.

### Steps to Reproduce

1. Open dir without git in atom `mkdir test && cd test && atom .`.
2. In dir use `git init`.
3. Check Atom

**Expected behavior:** Tree view updates

**Actual behavior:** Tree view does not update

**Reproduces how often:** 100% of my tests

### Versions

```
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.0
```

### Additional Information

This may be related to https://github.com/atom/tree-view/issues/1036.

**Comment by AndreaGriffiths11** [comment] 2017-03-10 16:30
Thank you for contributing!

We noticed that this is a duplicate of https://github.com/atom/tree-view/issues/1036. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by AndreaGriffiths11** 2017-03-10 16:30 UTC
