### ISSUE TITLE
"Merge" folders that contain only one folder inside into one "folder"

### ISSUE THREAD

**Issue by nunocastromartins** [atom/tree-view#640] opened 2015-11-05 12:47 UTC
The title has the word "folder" too many times in it, so let me explain what I mean.
Instead of showing something like:
```
> folder1
  > folder2
    > folder3
      >file1
      >folder4
```
Show:
```
> folder1/folder2/folder3
  > file1
  > folder4
```
The way this is currently handled forces the user to click quite a bit when they have a somewhat long chain of such folders, possibly hiding the files in the last folder and forcing the user to scroll right (depending on the width of the tree view).

Such chains of folders are unfortunately common when using, for instance, Maven.

Eclipse uses the second approach to display such folders. Both GitHub and BitBucket also do this when displaying repositories in their websites.

Problems might appear when attempting to rename folders or trying to add files/folders to the middle folders. However, given the way renaming and addition of a new file work (with a popup window that asks us to specify the new path), they should be solvable.

**Comment by mnquintana** [comment] 2015-11-05 12:58
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/tree-view/issues/125, which has been implemented for the next release of Atom.

**Closed by mnquintana** 2015-11-05 12:58 UTC
