### ISSUE TITLE
tree-view:collapse-all does not always work

### ISSUE THREAD

**Issue by edahlseng** [atom/tree-view#1285] opened 2018-11-07 02:53 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sending the `tree-view:collapse-all` command does not collapse everything in some cases.

### Steps to Reproduce

1. Set up a custom command.

```javascript
atom.commands.add('atom.workspace', 'example:collapse', () => {
    atom.workspace.getLeftDock().getPaneItems().forEach(paneItem => {
        atom.commands.dispatch(paneItem.element, 'tree-view:collapse-all');
    })
})
```
2. Expand a few items in the tree view.
3. Open the search-all results (cmd-shift-f and search for something)
4. Run the `example:collapse` command.

**Expected behavior:** [What you expect to happen]

For the tree view to collapse all items.

**Actual behavior:** [What actually happens]

The tree view does not collapse anything.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15
git 2.19.1

macOS 10.14.1

### Additional Information

Running the example command from an editor seems to work as expected in every case that I've tried so far.

**Comment by thomasjo** [comment] 2018-11-07 11:29
The event 'tree-view:collapse-all' is not part of the package's public commands. It's a private command, so what you're doing is not something that is officially supported.

My guess is that you're either not dispatching the command on the correct element, or something is preventing the collapse. Have you tried printing some debugging information to the developer console to ensure you're dispatching on the correct element?

Since this is not an officially supported use case, and is ultimately a user customization, I'm going to close this for the time being because this is not an actionable issue. Your best bet in tracking down the problem might be to ask for help on [Discord](https://discuss.atom.io/) or in our [Slack](https://discuss.atom.io/t/join-us-on-slack/16638). If you figure out that is an actual bug on our end, feel free to re-open the issue and providing all necessary details needed to reliably reproducing the problem.

**Closed by thomasjo** 2018-11-07 11:29 UTC
