### ISSUE TITLE
The following file couldn't be moved to trash

### ISSUE THREAD

**Issue by medmr1** [atom/tree-view#1019] opened 2017-01-08 19:05 UTC
### Prerequisites

*  [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have a freshly installed atom.io on win7 and it can't delete files from the project folder I made, despite every user having full permissions to the folder.

### Steps to Reproduce

1. Create file in tree view
2. attempt to delete file from tree view
3. "The following file couldn't be moved to trash" error message

**Expected behavior:** File is deleted.
**Actual behavior:** File is not deleted, error message.
**Reproduces how often:** 100%

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Windows 7, Fresh install

**Comment by medmr1** [comment] 2017-01-08 19:23
I figured it out. Enabling the recycling bin on that drive allowed me to delete the file and send it to the recycling bin.
PLEASE fix this behavior. It should not care 1 bit whether I have recycling bin enabled, it should just delete the file...

**Comment by 50Wliu** [comment] 2017-01-09 02:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #856. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

---

We use Electron's `shell.moveItemToTrash()` function for deleting files.  If you follow the link I gave you, that issue has another link to the related Electron bug.  In addition, future Atom versions will give you a more helpful warning message regarding the Recycle Bin until this bug is fixed.

**Closed by 50Wliu** 2017-01-09 02:34 UTC
