### ISSUE TITLE
Feature request: re-select file after rename

### ISSUE THREAD

**Issue by ebardajiz** [atom/tree-view#1158] opened 2017-08-09 10:37 UTC
When using keyboard shortcuts to navigate the tree view (j/k for up/down) and renaming a file (m), the renamed file looses focus. If your tree is big, you can lose a lot of time navigating back to the file.

Suggestion: after renaming a file, have the newly created file gain focus.

**Comment by rsese** [comment] 2017-08-09 21:08
Thanks for taking the time to contribute!

We noticed that this looks basically a duplicate of https://github.com/atom/tree-view/issues/824 You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-08-09 21:08 UTC
