### ISSUE TITLE
Renaming file caused error

### ISSUE THREAD

**Issue by doover** [atom/tree-view#124] opened 2014-04-21 16:14 UTC
I had a folder open on tree-view, right clicked the file and selected "Rename".

I added "_old" to the filename (is a temporary move to force a system error).

The "Enter new path for file" pop-up dialog box flashed red and indicated "EACCESS Permission Denied".
I was able to open a Finder window and rename the file with no problems.

I _think_ I have found part of the source of the problem.

I can recreate the problem with the following steps:
1- Left click on filename (opens the file).
2- Right click on filename, select "Rename"
3- Rename file and hit enter.

I seem to get the error every time if the file is open. Unfortunately, I sometimes get it when the file is closed also (perhaps a pointer in the "File/Reopen" dialog is holding the resource open?).

(quick search did not indicate this was a previously posted bug... apologies if it is a repost).

**Comment by kevinsawicki** [comment] 2015-08-06 23:59
Closing this out since I think this may have been fixed over the last year, please comment if you can still reproduce it on Atom 1.0.5+.

**Closed by kevinsawicki** 2015-08-06 23:59 UTC
Labels: bug
