### ISSUE TITLE
Sidebar pane(s) files/folders container is not full height

### ISSUE THREAD

**Issue by albinekb** [atom/tree-view#1107] opened 2017-05-19 00:03 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With a single pane in tree-view, only the part with files are right-clickable to create files and folders:

![image](https://cloud.githubusercontent.com/assets/5027156/26228044/99273dba-3c36-11e7-9b84-793965eebb74.png)

![image](https://cloud.githubusercontent.com/assets/5027156/26228050/9e22175e-3c36-11e7-8ab3-f123d8107fcd.png)

Here you can see the area:
![image](https://cloud.githubusercontent.com/assets/5027156/26228035/8a598fea-3c36-11e7-990a-4dbe7c05189f.png)

I think this was changed in this commit: https://github.com/atom/tree-view/commit/1e23411f8a604f0d74151effeeeaea54b3be9aeb

Is there a reason behind this? Maybe we can attach the context-menu to the `<atom-pane />` element (which fills the pane)? 

If that's OK I can submit a PR.

### Steps to Reproduce

1. Open a project folder in atom
2. Right click the sidebar below the last file/folder
3. You don't get the option to create a new file/folder etc

**Expected behavior:** I should be able to right click anywhere in the sidebar to create files/folders

**Actual behavior:** I need to click on the top part

### Versions

```sh
❯ atom-beta --version
Atom    : 1.17.0-beta5
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```sh
❯ apm-beta --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

**Comment by 50Wliu** [comment] 2017-05-19 00:16
This is a duplicate of #1073.  You might want @simurai's input for how to fix this.

**Closed by 50Wliu** 2017-05-19 00:16 UTC

**Comment by albinekb** [comment] 2017-05-19 02:22
Ah sorry @50Wliu didn't find that one 🙏
