### ISSUE TITLE
Open file on click , keep them open on double-click (like Sublime Text)

### ISSUE THREAD

**Issue by dj-hedgehog** [atom/tree-view#347] opened 2015-01-29 20:48 UTC
In Sublime Text it opens a file in the editor when you click on it in the tree view. If you click on another file it opens that one in the editor but closes the one opened before. It only keeps the file opened when you double-click on it.

Is it possible to implement this feature?
It would be a great usability enhancement.

**Comment by 50Wliu** [comment] 2015-01-29 21:41
Duplicate of #3, please subscribe there for updates.

**Closed by 50Wliu** 2015-01-29 21:41 UTC
