### ISSUE TITLE
Fold transpiled files of Typescript

### ISSUE THREAD

**Issue by betanubark** [atom/tree-view#571] opened 2015-09-14 22:05 UTC
Hi all
I wonder if it's possible to implement a folding option for TypeScript like [WebStorm's one](https://www.youtube.com/watch?v=Sl1Uk3zT5Fg&t=33) so transpiled files are somehow more navigable and get a cleaner tree view.
Thanks in advance!

**Comment by tebanep** [comment] 2015-09-14 22:12
This definitely would make Atom the best Editor/IDE for TypeScript!

**Comment by lee-dohm** [comment] 2016-02-08 18:36
I'm going to mark this as a duplicate of the more comprehensive #572. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-08 18:36 UTC
