### ISSUE TITLE
After updating to Atom 1.17, tree-view no longer works on the right side

### ISSUE THREAD

**Issue by mattpker** [atom/tree-view#1114] opened 2017-05-22 19:02 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After updating to Atom 1.17, tree-view no longer works on the right side

### Steps to Reproduce

1. Update to Atom 1.17
2. Go to the settings page for tree-view
3. Checkmark `Show on Right Side`
4. It stays on the left side

**Expected behavior:** [What you expect to happen]
It should show up on the right side of Atom

**Actual behavior:** [What actually happens]
It stays on the left side of Atom

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
 ~  atom --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
 ~  apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.11
git 2.9.0
```

tree-view: 0.217.0-7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

On macOS 10.12.4

**Comment by Zireael07** [comment] 2017-05-22 19:04
Duplicate of #1084 

Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762/1

**Comment by mattpker** [comment] 2017-05-22 19:31
Lol, I even did a search for `right side` but didn't check closed issues.

I see what I need to do, drag it over to the right. Even though for some reason I can't get it to drag to the other side...

Probably need to get that setting removed to avoid further confusion.

**Comment by mattpker** [comment] 2017-05-22 19:43
I can't get the drag and drop to work even in safe mode. I watched how the gif did it and everything. The chevron does not appear on the right hand side.

**Comment by 50Wliu** [comment] 2017-05-22 19:45
We can't really remove the setting, but you can manually remove it from your `config.cson`.  Does the chevron appear in safe mode (`atom --safe`)?  Did you perhaps edit your `styles.less` file or change a setting to remove the chevron?

**Comment by mattpker** [comment] 2017-05-22 19:53
So yes, removing tree-view settings from my config.cson removed the option for the right side in settings. I launched atom using `atom --safe` and still not able to move it to the right side. I checked my `styles.less` file but there are no changes in it.

**Comment by mattpker** [comment] 2017-05-22 20:12
I did the `mv ~/.atom ~/.atom-backup` and that fixed it, so something I have changed is causing it. Ill keep going through my stuff and see if I can find the exact cause.

**Comment by mattpker** [comment] 2017-05-22 20:25
In my `config.cson`:
```
 tabs:
     addNewTabsAtEnd: true
     alwaysShowTabBar: false
     enableVcsColoring: true
```
The `alwaysShowTabBar` option was causing the issue. Removing it from the file allows moving the tree-view around.

**Comment by mattpker** [comment] 2017-05-22 20:29
You can duplicate this behavior easily by going to Settings -> Packages -> Tabs -> Uncheck `Always Show Tab Bar`. Now you should not be able to move tree-view around.

**Comment by 50Wliu** [comment] 2017-05-23 05:11
Ah yes, that would do it.

💭 @matthewwithanm do you know if it's possible to move docks (through a command maybe) if that option is disabled?

**Closed by 50Wliu** 2017-05-23 05:11 UTC
