### ISSUE TITLE
Add file text editor toolbar blocks the text in Windows

### ISSUE THREAD

**Issue by Trudko** [atom/tree-view#373] opened 2015-02-16 11:28 UTC
Hi :),

if I add long string in tree-view:add new file, horizontal bar blocks the text. This happens on Windows in safe mode, I couldn't reproduce the same in Ubuntu.

![new-file](https://cloud.githubusercontent.com/assets/3289225/6211120/2258b1ce-b5d7-11e4-851e-1ad53b616dc3.png)

**Comment by izuzak** [comment] 2015-02-16 11:30
Looks like a duplicate of https://github.com/atom/atom/issues/5548. Should be fixed in the next version -- thanks for the report!

**Closed by izuzak** 2015-02-16 11:30 UTC

**Comment by Trudko** [comment] 2015-02-16 11:50
Yeah should be it, thank you for quick answer! :)
