### ISSUE TITLE
Renaming project folder does nothing

### ISSUE THREAD

**Issue by wewark** [atom/tree-view#1184] opened 2017-09-23 19:25 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Trying to rename the project folder you're working in inside atom just shows nothing

### Steps to Reproduce

1. Open any project
2. Right click the project folder in the tree view (which is the top one in the tree)
3. Click rename

**Expected behavior:** It should allow me to edit the name of the folder to rename it.

**Actual behavior:** Nothing at all.

**Reproduces how often:** 100%

### Versions

Atom    : 1.19.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10 64bit

**Comment by 50Wliu** [comment] 2017-09-23 20:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #179. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-09-23 20:28 UTC
