### ISSUE TITLE
Show open files above tree, Sublime-style

### ISSUE THREAD

**Issue by dbkaplun** [atom/tree-view#639] opened 2015-11-03 19:15 UTC

**Comment by kevinsimper** [comment] 2015-11-04 16:42
@dbkaplun I think you have to provide a screenshot :)

**Comment by mnquintana** [comment] 2015-11-04 16:53
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/tree-view/issues/36 - feel free to subscribe there for updates. :smile:

**Closed by mnquintana** 2015-11-04 16:53 UTC
