### ISSUE TITLE
When "Open with atom" a file, tree view reset project folder list

### ISSUE THREAD

**Issue by KSXGitHub** [atom/tree-view#661] opened 2015-11-28 06:32 UTC
Hello everyone, I'm using Atom in Windows 10. Here's my problem:

When I open a file (an individual file, Atom is not yet opened) by 3 ways below (they're technically the same), atom reset the list of my projects which I added before, these 3 ways are:
- Open File Explorer, double click a file (Atom is set as default opener for that kind of file)
- Open File Explorer, right click, then "open with atom"
- Open Command Prompt, type "atom myfile"

Here's my screenshot:

Before "open with atom"
![image](https://cloud.githubusercontent.com/assets/11488886/11450487/d528cc1c-95d3-11e5-9e68-eb65ea977cd0.png)

After I close Atom, then "open with atom"
![image](https://cloud.githubusercontent.com/assets/11488886/11450490/0837e188-95d4-11e5-8b60-7e3937a0271b.png)

I don't know if it was an issue of Tree View or Atom itself but I need help. I also discovered that all project folders I added is located at `C:\Users\%USERNAME%\.atom\storage\application.json`.

How can I fix this right now?
Thanks.

**Comment by alessors** [comment] 2016-02-22 11:17
Confirmed on Windows 8.1, Atom version 1.6.0 beta3, all packages disabled except the core ones.

**Comment by lee-dohm** [comment] 2016-02-22 23:03
I'm confused, specifically this line:

> After I **close Atom**, then "open with atom"

(emphasis mine)

This leads me to believe that this should be the expected behavior. If I:

1. Open Atom (doesn't matter how)
1. Do some stuff
1. Close Atom
1. Open Atom in some other location or with some other file

I wouldn't expect to see the stuff from step number 2. Am I misunderstanding?

**Comment by KSXGitHub** [comment] 2016-02-23 01:53
@lee-dohm 

1. Just open Atom

2. Add many project folders to your tree-view, then close Atom

3. Open a random file (or directory) by Atom, do either:
 - Right-click at a file/dir, then select "Open with Atom"
 - Use command line: `atom C:\path\to\file\or\dir`

**Comment by lee-dohm** [comment] 2016-02-23 02:48
Yes, it wasn't the repro steps that I wasn't understanding. I'm trying to understand why the behavior you are describing is a problem? What are you expecting to see that you are not seeing?

**Comment by KSXGitHub** [comment] 2016-02-23 03:26
@lee-dohm 

The problem is Atom remove all of previous added project folders from tree-view.
(When I open that file/dir while Atom is opening, tree-view is not modified)

My request is:

 1. If I open a folder by Atom, Atom should add that folder to tree-view instead of reset

 2. If I open a file, Atom should do nothing rather than create a tab for that file

**Comment by Zireael07** [comment] 2016-02-23 09:38
Ahah! I think in screenshot number 2, the file is displayed as a folder! That cannot be working as intended...

**Comment by KSXGitHub** [comment] 2016-02-23 10:45
@Zireael07 That makes no problems

**Comment by Ben3eeE** [comment] 2016-06-09 12:10
This is probably a duplicate of https://github.com/atom/tree-view/issues/471.

**Comment by KSXGitHub** [comment] 2016-06-09 13:08
@Ben3eeE They might be related, but not duplicate

**Comment by Ben3eeE** [comment] 2016-06-09 13:38
You say that you close Atom in your steps. Are you completely closing Atom before opening the new file? Then this is the expected behavior, if we remove the #471 issue which has been fixed in Atom 1.8.0.

See https://github.com/atom/tree-view/issues/852#issuecomment-222904528 for a recent explanation.

**Comment by KSXGitHub** [comment] 2016-06-09 16:12
@Ben3eeE Thanks for pointed it out.

The comment said

> Atom's notion of a project workspace is based on the current working directory that Atom is launched from.

So this is indeed expected behaviour. If I "Open with Atom" while Atom is opening, a new window (instance) of Atom would appear with that file/folder in Tree View.

**But still**, I would then suggest: While Atom is not running, if I do "Open with Atom", shouldn't Atom avoid using data (which defines the "original" workspace) of the "original" Atom instance and create a temporary data instead? It seems to be a feature request, should I open a new proposal btw?

**Comment by Ben3eeE** [comment] 2016-06-10 10:03
@KSXGitHub The original workspace is never lost, it is stored with that folder.

Example:
- You are working with `FolderA` and have a bunch of tabs open.
- Every time you close and start Atom (By double clicking the exe) `FolderA` will be restored and tabs in `FolderA` reopened.
- You do "Open with Atom" in `FolderB`. `FolderB` is now opened.
- Every time you close and start Atom (By double clicking the exe) `FolderB` will be restored and tabs in `FolderB` reopened.

To open and restore the state and opened tabs in `FolderA` simply do "Open with Atom" from or on that folder or you can open the folder using `ctrl-shift-o` from within Atom.

I see in your original image that you have multiple folders opened and I can't say how Atom works in this case because I never use it. For further support or questions regarding how this works I recommend that you open a topic on https://discuss.atom.io and getting help there before opening a new proposal here.

**Comment by Ben3eeE** [comment] 2016-07-07 07:55
@KSXGitHub I also found https://github.com/atom/atom/issues/9643 which seems similar to the feature request you describe.

**Comment by Ben3eeE** [comment] 2016-12-15 15:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/9643. In Atom 1.13 we also provide a menu for reopening recent projects.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-15 15:52 UTC
Labels: more-information-needed
