### ISSUE TITLE
Expand folder sometimes adds visual artifacts

### ISSUE THREAD

**Issue by gion** [atom/tree-view#541] opened 2015-07-29 08:35 UTC
This isn't happening all the time and unfortunately I didn't figure out certain steps to reproduce this bug. However, sometimes, after expanding a folder, the old list (next folder/files) isn't completely erased and the new files in folder overlap the old ones. This might be related to some sort of repaint not triggering correctly, but it's just a wild guess.  
Here's a screenshot with the issue: 
<img width="438" alt="screen shot 2015-07-29 at 10 58 23" src="https://cloud.githubusercontent.com/assets/810579/8953255/c5397750-35e5-11e5-9c6b-c4b85990475e.png">

PS: The plugin version is 0.177.0 running on Atom 1.0.2 on OSX 10.10.4

**Comment by mnquintana** [comment] 2015-07-29 11:12
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4924 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-29 11:12 UTC

**Comment by gion** [comment] 2015-07-29 12:33
@mnquintana Ok, thx!
