### ISSUE TITLE
 Highlight others modified files from git pull.

### ISSUE THREAD

**Issue by trainking** [atom/tree-view#882] opened 2016-07-07 08:40 UTC
I just had a git pull.But tree-view  highlight others all modified files.
I need to open one by one to cancel the highlight.

I'm going crazy.

**Comment by Ben3eeE** [comment] 2016-07-07 09:28
https://github.com/atom/tree-view/issues/870?

**Comment by thomasjo** [comment] 2016-07-07 09:34
Duplicate of #870.

**Closed by thomasjo** 2016-07-07 09:34 UTC
