### ISSUE TITLE
Irregular Rendering on TreeView

### ISSUE THREAD

**Issue by mizchi** [atom/tree-view#327] opened 2015-01-16 02:58 UTC
Mac OSX 10.9 and Atom 0.169.0

![](http://i.gyazo.com/bef7a9f97e6fb5922c18d62ea948e5c5.png)
It restores by reopen.

It may be caused by TreeView or Chrome Renderer.
Sorry for reporting trivial issue :(

(adding) It perhaps occurs at shadow dom

**Comment by 50Wliu** [comment] 2015-01-16 13:48
Duplicate of atom/atom#4924, please subscribe there for updates.

**Closed by 50Wliu** 2015-01-16 13:48 UTC
