### ISSUE TITLE
files with umlaut in title colored green

### ISSUE THREAD

**Issue by Kamik423** [atom/tree-view#1149] opened 2017-07-17 14:29 UTC
Files in tree view are shown in green when the filename contains umlauts (ä, etc.), even though they are committed, pushed and everything. This has been mentioned in #213.
Probably something with comparing the list of files with the list of committed files and parsing umlauts differently.

**Comment by 50Wliu** [comment] 2017-07-17 14:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#1890. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-07-17 14:34 UTC
