### ISSUE TITLE
Tree-view only treats directory as repository if it's a parent node in the tree

### ISSUE THREAD

**Issue by cbcoutinho** [atom/tree-view#1192] opened 2017-10-13 16:41 UTC
First off, thanks for the amazing package.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree view only treats a directory as a git repository if the parent node is a git repository. I have a directory that contains somewhat related projects that are each git repositories, but they are not related enough to put them into a single repository or make them submodules. Currently `tree-view` is not respecting the .gitignore files in each of the directories - only if the repositories are the parent node.

The directories highlighted below in red are all git repositories, contained within a directory called `src`:

![pic](https://user-images.githubusercontent.com/12901868/31556566-df778fda-b045-11e7-81c7-02d4ce74adfa.png)

### Steps to Reproduce

1. Create a directory
2. Put some git repositories into it
3. Open the first directory in Atom

I'm having trouble reading through the list of open/closed issues related to this project. I'm sure this has been addressed before, but I thought I would ask anyways.

**Comment by rsese** [comment] 2017-10-13 22:46
Thanks for the report @cbcoutinho!

> I'm having trouble reading through the list of open/closed issues related to this project. I'm sure this has been addressed before, but I thought I would ask anyways.

Thanks for opening this, we do have quite a few issues spread across many repositories so it's understandable that issues can be hard to find sometimes.  In this particular case, the issue was in atom/atom so I'll close this as a duplicate of https://github.com/atom/atom/issues/2203 and you can subscribe there for updates if you'd like.  

> First off, thanks for the amazing package.

✨ 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-13 22:46 UTC

**Comment by cbcoutinho** [comment] 2017-10-14 11:06
Thanks for the tip @rsese, I'll stay posted on the issue you mentioned - thanks for redirecting my issue.
