### ISSUE TITLE
Atom tree view doesn't stick to the right on restart

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [atom/tree-view#1256] opened 2018-06-06 15:36 UTC
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Tree view moves back to left on restart.

[Description of the issue]
Tree view when moved to the right side using drag n drop comes back to the left on restart.

### Steps to Reproduce

1. Start Atom
2. Drag n Drop tree view to the right
3. Restart Atom
4. Tree view is on the left side

**Expected behavior:**  Tree view should still be on the right.
**Actual behavior:** Tree view is on the left

**Reproduces how often:**  100%

### Versions
Atom 1.27.1
Ubuntu 18.04

As discussed with @rsese  on https://github.com/atom/tree-view/issues/1084#issuecomment-392884408

**Comment by rsese** [comment] 2018-06-06 17:43
Thanks for opening a new issue - I'm unable to reproduce with 1.27.1 on Ubuntu 18.04.  If you temporarily reset to factory defaults, does the tree-view stick after dragging it over to the right?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by ankitsinghaniyaz** [comment] 2018-06-06 18:47
Nope, that doesn't fix it. I've even tried to remove and re-install atom completely.

**Comment by ankitsinghaniyaz** [comment] 2018-06-06 18:50
I guess this has something to do with opening atom using sudo. I had to edit some `/etc` config files so I opened that using `sudo atom` and that seems to have messed the configuration.

Is there any place where the config is stored?

**Comment by ankitsinghaniyaz** [comment] 2018-06-06 18:58
I can confirm that the issue not there if I open atom using sudo.

1. `sudo atom` - wroks fine as expected
2. `atom` - tree view doesn't sticks

**Comment by rsese** [comment] 2018-06-07 02:34
Ahhh yeah that's probably it, running Atom with `sudo` [causes issues](https://github.com/atom/atom/issues/10566)  - since resetting to factory defaults didn't fix things up for you, I don't think it's your `config.cson` file.  I poked around a bit more and see that [clearing saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) didn't reset the location of tree view either if I had dragged it to the right side.

Finally found that it's stored in `~/.config/Atom/IndexedDB/` so I wonder if that directory or a file in the directory is owned by `root` and you just need to `chown` it?   I did think that clearing saved state would clear that info though.

You could also rename the directory so next time you start Atom without `sudo` things should be ok.

**Comment by ankitsinghaniyaz** [comment] 2018-06-07 07:13
Thank you so much. I just deleted that directory and now it works again. :)

**Comment by rsese** [comment] 2018-06-07 17:19
Great glad that worked :zap:, I'll go ahead and close this out.

**Closed by rsese** 2018-06-07 17:19 UTC
Labels: more-information-needed
