### ISSUE TITLE
"Search in this directory" not working when folder/path is specified

### ISSUE THREAD

**Issue by clintharris** [atom/tree-view#142] opened 2014-05-12 14:43 UTC
Doing a full-text search for files in a project (aka "Search in this directory") seems to break if you actually specify a path.

Steps to reproduce:

1. Create an Atom project with several sub-folders containing text files.
2. Right-click on a folder in the tree pane and select "Search in this directory"
3. Search for some string of text known to exist in one of the files.
    - **Result/Issue: text is not found**
4. Clear the folder path from the "File/directory pattern..." field and search again.
    - Result: text is found

**Comment by yuvilio** [comment] 2015-01-07 18:23
Same here. Not working for me on Atom 0.166.0 on Ubuntu. Seems like a relatively recent break.

**Comment by csdco** [comment] 2015-02-02 18:12
This breaks for me as well if any folders in the path contain periods in their names.

**Comment by izuzak** [comment] 2015-02-12 14:51
Closing in favor of https://github.com/atom/find-and-replace/issues/309 which has steps to reproduce and is in the package related to the problem.

**Closed by izuzak** 2015-02-12 14:51 UTC
Labels: bug

**Comment by cauerego** [comment] 2015-09-15 02:30
This happens if the folder isn't on the root. In the gif, you could try typing `fixtures` straight on, instead of using that context menu. ;)

And thank you for the gif, @izuzak ! :+1:

**Comment by izuzak** [comment] 2015-09-15 09:51
@cauerego Not sure I understand your comment -- are you still seeing this issue? If so, would you mind sharing the exact steps which reproduce the problem for you in Atom 1.0.11 and also a GIF which demonstrates the problem?

**Comment by cauerego** [comment] 2015-09-15 10:25
Yes, still happens. There must be another obvious way around it, I just couldn't figure out. Here's your gif:

![sep 15 2015 10 59 atom find in directory](https://cloud.githubusercontent.com/assets/560418/9874111/156c615c-5b9c-11e5-8350-14691cf1f27a.gif)

**Comment by izuzak** [comment] 2015-09-15 11:45
@cauerego Would you mind being a bit more precise about which part of that GIF actually reproduces the problem reported in this issue? As far as I can tell, when you entered the correct path in the "File/directory" patterns -- everything works as expected. When you entered just "bootstrap" -- that didn't return anything because you didn't enter the complete path.

**Comment by cauerego** [comment] 2015-09-15 11:49
If there is no other `bootstrap` folder, it's only natural to expect it will find that folder and use it. Think of it like `find grep`: we could just `find . | grep /bootstrap` and it would most likely filter out all other results while `grep /bootstrap/` would be flawless if there's no other directory with the same name.

Even more: maybe we do want to find only within all directories with same name. So this is even an added bonus feature! ;)

**Comment by izuzak** [comment] 2015-09-15 11:55
@cauerego While I understand why you think this would be possible, what you observed is expected behavior for now and your report doesn't seem to be related to this issue. Recommendation: open a new issue which would be a feature request to add this new functionality. Does that sound good?

**Comment by cauerego** [comment] 2015-09-15 12:15
Nope. That actually pissed me off. Expected behaviour doesn't mean it is or ever was right.

I don't want to request or suggest a new feature, I think it is broken as it is and I think if it's not the same thing @clintharris meant, he wasn't clear enough. The ambiguity is there and this is completely related.

Granted, all this is highly subjective. But that's all how I feel anyway.

Sorry if I caused you any trouble, I'll be gone for now.

Cheers.

**Comment by martuico** [comment] 2016-07-20 07:54
Find and replace in folder is not working. It searches to all project folders instead

**Comment by piyush-dholariya** [comment] 2016-09-30 11:38
Find and replace in folder is not working. It searches to all project folders instead

**Comment by phonggenix** [comment] 2016-11-17 13:22
I'm facing the same problem.

OSX 10.11.6
Atom 1.12.3

**Comment by phonggenix** [comment] 2016-11-17 13:29
I opened the Scripts folder, pressed CMD+Shift+F, entered any keyword, it always returned "No results found for...". Only when I explicitly entered "Scripts" in the 3rd text then the search worked.

![screen shot 2016-11-17 at 8 27 01 pm](https://cloud.githubusercontent.com/assets/14937764/20391060/403614fe-ad04-11e6-84ee-39d388ad95d5.png)

**Comment by hubletkoresh** [comment] 2017-01-11 08:02
Same thing here. Windows 10 Pro N x64. If I put the directory pattern in no results are ever shown.

**Comment by VukanJ** [comment] 2019-02-22 13:03
I am facing the same problem on 4.20.10-arch1-1-ARCH and atom 1.34.0.
Searching in directories as well as "project folders" does not work. Neither with absolute, nor with relative paths.

**Comment by ohgodspidersno** [comment] 2020-04-07 16:51
Any solutions to this yet?
