### ISSUE TITLE
select multiple files with shift+arrows

### ISSUE THREAD

**Issue by miroshko** [atom/tree-view#875] opened 2016-06-27 08:51 UTC
It is possible right now to change the selected file in the tree view with keyboard arrows, but it would help if doing this with the pressed "Shift" key would select multiple files, like it's usually done in operating systems (at least Ubuntu and Windows). This will allow to operate with multiple files using keyboard only.

**Comment by 50Wliu** [comment] 2016-07-15 12:35
This is a duplicate of #575 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-15 12:35 UTC
Labels: enhancement
