### ISSUE TITLE
tree-view on atom 1.5 beta incorrectly shows subtrees as "new" git files

### ISSUE THREAD

**Issue by chrishiestand** [atom/tree-view#717] opened 2016-02-03 21:16 UTC
This problem only occurs when you tell atom to open a sub-folder of a git repository.

To reproduce:

1. Install atom 1.5 beta
2. `git clone git@github.com:atom/tree-view.git`
3. `atom-beta tree-view/spec` (alternatively use the gui and open this subfolder) 

Note that "git clean" files and folders are shown in green on tree-view. Sometimes when you open the file in atom the green will refresh to gray.

**Comment by lee-dohm** [comment] 2016-02-04 21:42
Which OS are you experiencing this on?

**Comment by chrishiestand** [comment] 2016-02-04 23:33
OS X

**Comment by alooffool** [comment] 2016-02-09 22:43
I see similar behavior in Atom 1.5.0 on Windows 10.

If I click on a green file, the file opens and the tree colors are updated correctly, but when i restart Atom, the file colors revert to green.

I tried a few different UI themes and the issue persists.

**Comment by chrishiestand** [comment] 2016-02-10 20:29
Looks like this may have been handled in atom/atom#10746. I'm still experiencing the issue on 1.5 and 1.6beta, but after the next release I'll update this issue about whether or not it's been fixed.

**Comment by lee-dohm** [comment] 2016-02-10 20:33
@chrishiestand Yeah, I strongly suspect this is a duplicate of that Issue.

Also, the fix is in https://github.com/atom/atom/pull/10758 and we're working on putting out a hotfix for it today.

**Comment by chrishiestand** [comment] 2016-02-10 20:34
@lee-dohm awesome, thanks!

**Comment by alooffool** [comment] 2016-02-10 20:35
Thanks much!

**Comment by joshaber** [comment] 2016-02-10 21:30
We just released 1.5.1 which fixes this. Thanks for all the reports and sorry for the hassle!

![](http://www.reactiongifs.com/r/swag.gif)

**Closed by joshaber** 2016-02-10 21:30 UTC
Labels: needs-reproduction

**Comment by chrishiestand** [comment] 2016-02-10 21:53
@joshaber confirmed fixed, thanks!

**Comment by alooffool** [comment] 2016-02-10 23:39
Same here--thanks again for the speedy response! :)
