### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by xi3** [atom/tree-view#315] opened 2015-01-07 16:57 UTC
Uncaught TypeError: Cannot read property 'destroy' of null

**Atom Version**: 0.158.0
**System**: Mac OS X 10.9.5
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.138.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:350

TypeError: Cannot read property 'destroy' of null
  at TreeView.module.exports.TreeView.detach (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:350:17)
  at TreeView.module.exports.TreeView.onSideToggled (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:1018:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:316:24
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:581:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:556:29)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:189:14)
  at toggleConfig (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:37:24)
  at TreeView.module.exports.TreeView.toggleSide (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/tree-view.js:984:14)
  at atom-workspace.disposables.add.atom.commands.add.tree-view:toggle-side (/Applications/Atom.app/Contents/Resources/app/node_modules/tree-view/lib/main.js:59:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-01-07 17:51
This is a duplicate of https://github.com/atom/tree-view/issues/272 which has been fixed and released.

This error should go away when you upgrade to Atom 0.166 or later.

**Closed by kevinsawicki** 2015-01-07 17:51 UTC
