### ISSUE TITLE
Rename dialog for a long path does not show the file

### ISSUE THREAD

**Issue by izuzak** [atom/tree-view#592] opened 2015-10-12 15:09 UTC
_From @oxo42 on October 6, 2015 10:12_

When trying to rename a file `environments\production\modules\ltuk\files\users\oxle019\oxle019.bash_profile` the rename dialog shows up to the end of the first `oxle019`.

![image](https://cloud.githubusercontent.com/assets/572079/10305889/07266982-6c1b-11e5-91ff-57a4664b224a.png)

It would make more sense to have the text box scrolled to the end, so you can see the file that has been highlighted.

_Copied from original issue: atom/atom#9057_

**Comment by simurai** [comment] 2015-10-13 06:44
This looks like the issue when "soft wrap" is enabled in the settings. Here a quick fix: https://github.com/atom/tree-view/issues/473#issuecomment-131388489

Proper fix might be to never wrap text in mini editors.

**Comment by mnquintana** [comment] 2015-10-24 17:08
I think this is a duplicate of https://github.com/atom/tree-view/issues/473 - closing this out in favor of that issue.

**Closed by mnquintana** 2015-10-24 17:08 UTC
