### ISSUE TITLE
Delete file function fails

### ISSUE THREAD

**Issue by joshas** [atom/tree-view#762] opened 2016-03-07 21:38 UTC
Opened new project folder, trying to delete one file. Pressing delete button or selecting "Delete" from context menu displays "Are you sure you want to delete selected item?" dialog. Clicking "Move to trash" does nothing. Dialog closes, but file is still in tree-view panel and in filesystem.
Using standalone atom-windows.zip version 1.5.4 on Windows 7 64-bit OS. tree-view version 0.198.1
Tested in normal and safe modes.

**Comment by 50Wliu** [comment] 2016-03-07 21:44
This is a duplicate of #666 and will be fixed in Atom 1.7.0.  Sorry for the inconvenience.

**Closed by 50Wliu** 2016-03-07 21:44 UTC
