### ISSUE TITLE
"Hide VCS Ignored Files" doesn't respect .gitignore negated patterns

### ISSUE THREAD

**Issue by Ajedi32** [atom/tree-view#764] opened 2016-03-10 18:32 UTC
My `.gitignore` file contains a statement similar to the following:

```
# Ignore everything in some_folder...
some_folder/*

# Except somefile...
!some_folder/somefile
````

This incorrectly results in `some_folder` being entirely hidden from tree-view when "Hide VCS Ignored Files" is enabled, even though not all files in it are ignored by git.

When "Hide VCS Ignored Files" is off, tree-view does correctly show that `somefile` is not ignored by git (it's not grayed out like the other files in that folder are). However, `some_folder` is shown as ignored even though it shouldn't be.

Please see the [git documentation for negated ignore patterns](https://www.kernel.org/pub/software/scm/git/docs/gitignore.html#_pattern_format) for more information on how this works.

Relevant quote:

> * An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\") in front of the first "!" for patterns that begin with a literal "!", for example, "\!important!.txt".

(Note that excluding a directory is not treated the same by git as excluding all the files in that directory.)

**Comment by lee-dohm** [comment] 2016-03-10 19:03
This is a duplicate of https://github.com/atom/tree-view/issues/196. You may want to subscribe there for updates or add any clarifications that you think the developers should understand.

Thanks for reporting!

**Closed** 2016-03-10 19:04 UTC
Labels: duplicate
