### ISSUE TITLE
Messy tree when open files out of it

### ISSUE THREAD

**Issue by dsambugaro** [atom/tree-view#852] opened 2016-05-26 19:17 UTC
First, sorry my bad english..

So, let's go..

When open a file with Atom and this file is out of tree, all folders that were on the tree disappear!
And stay only a folder that open file!
The correct would open the file without changing the tree!
No exclusions. No additions.

Thanks very much.

**Comment by Ben3eeE** [comment] 2016-05-31 12:11
Are you using Windows? If I am understanding this correctly it might be a duplicate of https://github.com/atom/tree-view/issues/471?

**Comment by dsambugaro** [comment] 2016-06-01 00:40
No. I'm using a linux distribution (this linux distribution<http://distrowatch.com/table.php?distribution=antergos>)

My problem is like this, but not the same.

Look a simple gif (I hope you understand):

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/13372649/15694882/0dbd9b80-2778-11e6-9e54-50b858672195.gif)

**Comment by thomasjo** [comment] 2016-06-01 06:28
You are closing Atom, and opening a new instance which is then rooted in a different directory than the one you used to create the original instance in. This is expected behavior. Atom's notion of a *project workspace* is based on the current working directory that Atom is launched from. There are two (very similar) ways to "fix" your issue;
  1. Don't close/exit Atom before opening the file.
  2. If you exit Atom, but want to retain the previous workspace, then open Atom directly (not via opening a file), then open the file.

Regardless, this is not a bug in the tree-view package, or with Atom itself, so I'm closing this. If you have further concerns, feel free to post a question on [Discuss](https://discuss.atom.io/) or Slack.

**Closed by thomasjo** 2016-06-01 06:28 UTC

**Comment by Yopai** [comment] 2016-08-16 12:47
Would there be a way to retain opened project folders, then ?
(My personal method is to put .atom/storage/application.json under git.)
