### ISSUE TITLE
Find and replace in folder is not working. It searches to all project folders instead

### ISSUE THREAD

**Issue by piyush-dholariya** [atom/tree-view#947] opened 2016-09-30 11:39 UTC
Find and replace in folder is not working. It searches to all project folders instead

**Comment by AndreaGriffiths11** [comment] 2017-02-03 23:20
Thanks for taking the time to contribute!

I tried to reproduce this using Atom v1.13.1 on Mac OS X 10.12.3. I could not reproduce it and we had no reports of similar problems. So I'm going to close this if you have more information to share please open a new issue and fill out the template. Thanks again.

**Closed by AndreaGriffiths11** 2017-02-03 23:20 UTC
