### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by yaoduren123** [atom/tree-view#313] opened 2015-01-07 06:32 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Unknown Windows Version
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.139.0

### Stack Trace

Uncaught Error: Atom can only handle files < 2MB for now.

```
At c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\src\project.js:462

Error: Atom can only handle files < 2MB for now.
  at Project.module.exports.Project.buildBuffer (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\src\project.js:462:15)
  at Project.module.exports.Project.bufferForPath (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\src\project.js:439:63)
  at Project.module.exports.Project.open (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\src\project.js:393:19)
  at Workspace.module.exports.Workspace.openUriInPane (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:482:29)
  at Workspace.module.exports.Workspace.open (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:409:19)
  at TreeView.module.exports.TreeView.openSelectedEntry (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\node_modules\tree-view\lib\tree-view.js:639:31)
  at TreeView.module.exports.TreeView.entryClicked (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\node_modules\tree-view\lib\tree-view.js:383:18)
  at tree-view-file.<anonymous> (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\node_modules\tree-view\lib\tree-view.js:171:26)
  at space-pen-div.jQuery.event.dispatch (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4676:9)
  at space-pen-div.elemData.handle (c:\Users\xingfeng\AppData\Local\atom\app-0.165.0\resources\app\node_modules\archive-view\node_modules\atom-space-pen-views\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
     -2:52.1 dev-live-reload:reload-all (input.hidden-input)
     -1:07.4 command-palette:toggle (atom-pane.pane.active)
     -1:06.2 editor:consolidate-selections (input.hidden-input)
     -1:06.2 core:cancel (input.hidden-input)
     -0:27.6 editor:toggle-line-comments (input.hidden-input)
     -0:13.3 core:undo (input.hidden-input)
     -0:05.6 core:save (input.hidden-input)
     -0:00.0 pane:reopen-closed-item (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "tree-view": {
    "hideIgnoredNames": true,
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
editor-stats, v0.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by lee-dohm** [comment] 2015-01-08 05:48
Duplicate of atom/atom#4421 and atom/atom#307.

**Closed by lee-dohm** 2015-01-08 05:48 UTC
