### ISSUE TITLE
Files with git conflicts appear as if they were unmodified

### ISSUE THREAD

**Issue by bronson** [atom/tree-view#1174] opened 2017-09-04 20:37 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree View displays files with git conflicts as if they were unchanged files.

Here's a screenshot: The file `test-spec.coffee` is conflicted, and has conflict markers, but the tree view is showing it as if there are no changes.  (this is in --safe mode)

![screen shot 2017-09-04 at 1 17 01 pm](https://user-images.githubusercontent.com/1776/30038083-ff717d6c-9175-11e7-92bb-533566ddd92e.png)

### Steps to Reproduce

1. generate a git conflict
2. look at the conflicted file in the tree view

**Expected behavior:** [What you expect to happen]

I'd expect the file to be displayed in a vibrant "conflicted" color...  maybe the purpley-pink used by the github package.

Or, at the very least, for it to be displayed the same as other locally-modified files.

**Actual behavior:** [What actually happens]

The file is shown as if it were unchanged, even though it actually is modified.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Both release and beta.

```
$ atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.14.0
$ atom-beta --version
Atom    : 1.20.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm-beta --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.14.0
```

**Comment by 50Wliu** [comment] 2017-09-04 20:44
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/atom#11092. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-09-04 20:44 UTC

**Comment by bronson** [comment] 2017-09-04 21:24
Wow, surprised I couldn't find that.  Thanks, subscribing!

**Comment by 50Wliu** [comment] 2017-09-04 22:09
No problem - even I had some trouble finding it, considering that I filed the issue :P.

**Comment by evilsideburns** [comment] 2019-06-06 14:35
Issue https://github.com/atom/atom/issues/11092 is now "stale" and this issue persists to this day.

**Comment by mrinalwadhwa** [comment] 2021-01-03 04:33
This is still an issue.
