### ISSUE TITLE
Windows keybinding problems

### ISSUE THREAD

**Issue by jraulmont** [atom/tree-view#904] opened 2016-08-02 15:37 UTC
With spanish keyboard (Latin american) on windows, can't write the character "\" because ctrl+alt+[key with \] is needed, and the event is fired instead of writing the char, I need an option to disable keybindings

**Comment by 50Wliu** [comment] 2016-08-02 16:05
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-02 16:05 UTC
