### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, rename '[filepath]/file' -> '[filepath]/file'

### ISSUE THREAD

**Issue by danShumway** [atom/tree-view#443] opened 2015-05-09 17:35 UTC
[Enter steps to reproduce below:]

1. cut a folder in the tree view
2. paste it in itself

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.171.0

### Stack Trace

Uncaught Error: EBUSY: resource busy or locked, rename 'C:\Users\shumw_000\Documents\Code\vAnalyze.js\depreciated' -> 'C:\Users\shumw_000\Documents\Code\vAnalyze.js\depreciated\depreciated'

```
At fs.js:680

Error: EBUSY: resource busy or locked, rename 'C:\Users\shumw_000\Documents\Code\vAnalyze.js\depreciated' -> 'C:\Users\shumw_000\Documents\Code\vAnalyze.js\depreciated\depreciated'
  at Error (native)
  at Object.fs.renameSync (fs.js:680:18)
  at Object.fsPlus.moveSync (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:269:17)
  at TreeView.module.exports.TreeView.pasteEntries (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:969:32)
  at space-pen-div.atom.commands.add.tree-view:paste (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\tree-view\lib\tree-view.js:277:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\atom.asar\renderer\api\lib\remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:149:33)
  at HTMLDocument.handler (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\shumw_000\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
  5x -4:37.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -4:35.1.0 core:save (atom-text-editor.editor.is-focused)
     -3:03.3.0 core:copy (atom-text-editor.editor.is-focused)
  5x -3:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:59.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:59.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:59.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:59.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:58.9.0 core:paste (atom-text-editor.editor.is-focused)
     -2:57.1.0 core:save (atom-text-editor.editor.is-focused)
  4x -2:50.1.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:48.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -2:46.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:44.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:24 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:23.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "project-ring"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.13.1
docblockr, v0.6.3
jshint, v1.3.6
linter, v0.12.2
minimap, v4.8.0
minimap-bookmarks, v0.1.0
minimap-color-highlight, v4.1.3
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
pain-split, v1.4.0
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-05-09 18:51
Duplicate of #419, please subscribe there for updates.

**Closed by 50Wliu** 2015-05-09 18:51 UTC
