### ISSUE TITLE
Screen corruption when scrolling on Mac

### ISSUE THREAD

**Issue by bronson** [atom/tree-view#494] opened 2015-06-26 21:10 UTC
When scrolling, some of the treeview entries get drawn on top of each other.

![bug3](https://cloud.githubusercontent.com/assets/1776/8387357/b65f24fc-1c0c-11e5-920c-a5a646d08169.gif)

This seems pretty new...  At least, I never noticed it before.  Also, it only seems to affect the tree-view.  I haven't seen it while editing yet.

Atom 1.0, tree-view 0.172.0.  OSX Yosemite, retina iMac, editor window fullscreened.  No errors appear in the console.

**Comment by mnquintana** [comment] 2015-06-28 02:10
This is a duplicate of https://github.com/atom/atom/issues/4924 – please subscribe there for updates.

**Closed by mnquintana** 2015-06-28 02:10 UTC
